### ISSUE TITLE
Aligning DEX and Oracle prices by dynamic distribution of profit and introduction of locked vaults

### ISSUE THREAD

**Issue by Berioldir** [DeFiCh/ain#1002]
#### What would you like to be added:

Introduction of lockedVaults and dynamic distribution of profit to bring DEX prices closer to oracle prices to attract more investors to the DeFiChain.

#### Why is this needed:

**Full paper is attached as a PDF. A summary of the proposal based on an example:**

Currently, the demand for dTokens is very high due to the high profit distributions in liquidity mining, but the supply is low. For this reason, dTokens are highly overvalued.
To solve the problem of large differences between the prices of dTokens and the prices of the Oracle, lockedVaults with dynamic profit distribution are introduced. This leads to such an adjustment of supply and demand that the prices between DEX and Oracle align. 
Explanation of the lockedVault using the example of the dTSLA token: a user creates a lockedVault with the desired security model. He mines the token of his choice, here dTSLA. The property of the lockedVault is that this dTSLA token is immediately sold on DEX against dUSD. This increases the supply and decreases the price. The sale revenues dUSD are also locked into the lockedVault. The user can therefore neither dispose of the mined dTSLA token nor of the sale revenue dUSD. He is short on dTSLA. As an incentive, profits are distributed for the lockedVaults in the form of DFI. **So it is not only liquidity mining that is rewarded, but also the creation of tokens.**

For this purpose, the payout, which is currently reserved for liquidity mining, will be extended to these lockedVaults. The distribution of the payout between liquidity mining and lockedVaults is determined by the blockchain through a dynamic distribution key. Depending on whether the prices of the respective asset are currently overvalued or undervalued, the blockchain changes the dynamic distribution key in the necessary direction. If an asset is overvalued, the distribution is increased for the lockedVaults and reduced for liquidity mining. If the asset is undervalued, the opposite occurs. In this way, either mining and selling tokens (=increasing supply) or buying for liquidity mining (=increasing demand) is made more attractive.

Closing the lockedVault using the example of the dTSLA token: the user is short on the asset dTSLA. To repay the loan, the blockchain sells the entire locked-in sale proceeds dUSD.
Now there are the two cases: a) the dTSLA price has fallen b) the dTSLA price has risen. In case a), the user gets more dTSLA for his dUSD, so in addition to the distributed DFI, he also makes a profit from the price change. In case b) he gets less dTSLA for his dUSD. The loan cannot be repaid in full, so the user has to buy dTSLA on DEX and can only then repay the loan, which reduces his profit. Repayment with dTSLA bought on DEX is only possible when the entire locked-in sales revenues of dUSD have been used up.

Parallel to the lockedVault, the user can continue to use the existing functionalities. If they want to operate LM, they can either buy the respective tokens with NEW capital on the DEX and put them into LM, or they use the standard Vault, mine the tokens and put them into LM or simply hold them.

As DeFiChain mainly is a project of german speaking users I also post a summary in german:

**Full paper ist als PDF angehängt. Hier die Zusammenfassung anhand eines Beispiels:**

Aktuell ist die Nachfrage nach den dToken aufgrund der hohen Gewinnausschüttungen im Liquidity Mining sehr hoch, das Angebot jedoch gering. Aus diesem Grund sind die dToken stark überbewertet.
Zur Lösung des Problems der starken Unterschiede zwischen den Preisen von dToken und den Preisen des Oracles werden lockedVaults mit dynamischer Gewinnausschüttung eingeführt. Dies führt zu einer derartigen Anpassung von Angebot und Nachfrage, dass sich die Preise zwischen DEX und Oracle angleichen. 
Erklärung des lockedVaults am Beispiel des dTSLA Tokens: ein Nutzer erstellt einen lockedVault mit dem gewünschten Besicherungsmodell. Er mintet den Token seiner Wahl, hier dTSLA. Die Eigenschaft des lockedVaults ist, dass dieser dTSLA Token sofort auf der DEX gegen dUSD verkauft wird. Dies erhöht das Angebot und verringert den Preis. Der Verkaufserlös dUSD wird ebenfalls in den lockedVault gesperrt. Der Nutzer kann also weder über den geminteten dTSLA Token verfügen, noch über den Verkaufserlös dUSD. Er ist short auf TSLA. Als Anreiz werden für die lockedVaults Gewinne in Form von DFI ausgeschüttet. **Es wird also nicht nur das Liquidity Mining belohnt, sondern auch das Erstellen von Token.**

Dazu wird die Ausschüttung, welche aktuell dem Liquidity Mining vorbehalten ist, auf diese lockedVaults ausgeweitet. Die Aufteilung der Ausschüttung zwischen Liquidity Mining und lockedVaults wird durch einen dynamischen Verteilungsschlüssel von der Blockchain festgelegt. Je nachdem, ob die Preise des jeweiligen Assets gerade über- oder unterbewertet sind, verändert die Blockchain den dynamischen Verteilungsschlüssel in die notwendige Richtung. Bei der Überbewertung eines Assets wird die Ausschüttung für die lockedVaults erhöht, für das Liquidity Mining verringert. Bei einer Unterbewertung des Assets erfolgt das Gegenteil. Auf diese Weise wird entweder das Minten und Verkaufen von Token (=Erhöhung Angebot) oder das Kaufen für das Liquidity Mining (=Erhöhung Nachfrage) attraktiver gemacht.

Schließen des Vaults am Beispiel des dTSLA Tokens: der Nutzer ist short auf das Asset TSLA. Um den Kredit zurückzuzahlen verkauft die Blockchain den gesamten eingesperrten Verkaufserlös dUSD. Jetzt gibt es die zwei Fälle: a) der TSLA Kurs ist gefallen b) der TSLA Kurs ist gestiegen. In Fall a) bekommt der Nutzer mehr dTSLA für seine dUSD, macht also zusätzlich zu den ausgeschütteten DFI noch einen Gewinn durch die Kursveränderung. Im Fall b) bekommt er weniger dTSLA für seine dUSD. Der Kredit kann nicht ganz zurückgezahlt werden, also muss der Nutzer dTSLA auf der DEX nachkaufen und kann erst dann den Kredit tilgen, was seinen Gewinn verringert. Das Tilgen mit auf der DEX gekauften dTSLA ist erst dann möglich, wenn der komplette eingesperrte Verkaufserlös an dUSD aufgebraucht wurde.

Parallel zum lockedVault kann der Nutzer die bestehenden Funktionalitäten weiterhin nutzen. Möchte er LM betreiben, so kann er entweder mit NEUEM Kapital auf der DEX die jeweiligen Token kaufen und ins LM geben, oder er verwendet den Standard Vault, mintet sich die Token und steckt sie ins LM oder hält sie einfach nur.

Let's discuss it!

[DeFiChain - Dynamische Verteilung der Gewinnausschüttung - Final.pdf](https://github.com/DeFiCh/ain/files/7779814/DeFiChain.-.Dynamische.Verteilung.der.Gewinnausschuttung.-.Final.pdf)
[DeFiChain - Dynamic distribution of profit distribution - Final.pdf](https://github.com/DeFiCh/ain/files/7779815/DeFiChain.-.Dynamic.distribution.of.profit.distribution.-.Final.pdf)

**Comment by shohamc1** [comment]
This should be a [dfip](https://github.com/DeFiCh/dfips).
