### ISSUE TITLE
Defichain wallet does not sync and gets stuck when clock is not set with the right time

### ISSUE THREAD

**Issue by miguelromero2000** [DeFiCh/ain#1008]
#### What happened:
Defichain wallet gets stuck and does not sync.

#### What you expected to happen:
Defichain wallet should sync without any problems.

#### How to reproduce it (as minimally and precisely as possible):
Close DefiChain if opened. Change your computer local clock time and set it to two hours less. Reopen Defichain wallet and it will not sync.

#### What are your environment parameters:

- Operative System: Windows 7 x64bits
- Defichain wallet: desktop for windows.
- CPU: Intel 6700K, 64GB ddr4 memory, SSD with +30 gb free space on disk.
- (Probably all OS are affected).

#### Anything else we need to know?:
It is easy to reproduce and would be nice to show an alert or to fix it so that the synchronization does not depend on local computer time and new people and/or benningers could avoid this bug which can get you crazy until you discover that it was a clock time problem.

**Comment by defijeff** [comment]
+1 for showing a warning
Generally, I don't think this can be fixed as Defichain is proof-of-stake and depends on an external clock that way.

It does not create its own timechain like proof-of-work through probabilitic iteration/guessing but instead it grants to hash 1 nonce/sec/masternode and demands that blocks are relative +/- 5 seconds for other nodes to accept it.

**Comment by shohamc1** [comment]
This warning is shown when a computer's time is out of sync.

```
Warning: Please check that your computer's date and time are correct! If your clock is wrong, DeFi Blockchain will not work properly.
```
