### ISSUE TITLE
Deposit of a Masternode as security for a loan

### ISSUE THREAD

**Issue by derstrecker** [DeFiCh/ain#1009]
Please check the actual DFIP: https://github.com/DeFiCh/dfips/issues/107

__________

ENGLISH

When the Freezer-Masternodes (MN) were introduced, there was the idea of enabling a change of owner of a Freezer-MN at some point, i.e. the sale. Based on this, the following idea:

The owner of a house can generate rental income as well as take out a mortgage on the house in order to be liquid. The same financial principle can also apply to masternodes: The rental income corresponds to the rewards, the mortgage to the following:

**Possible deposit of a MN as security for a loan.** This loan can amount to a maximum of 10K in dUSD, in order to remain at the maximum of an auction tranche (anything else is likely to be too complicated to implement for the time being). If the value of the MN falls below 10K (unlikely, but not impossible), the collateral (here the MN) can be auctioned off, as usual. I.e. after a successful auction, a change of owner takes place. According the Defichain-Masternode Telegram-channel, the function for transferring a masternode is already programmed, just not yet implemented. Since the masternodes run on the desktop wallet, the Vault/Loan function must be added there.

A Dfip would therefore include:
- Desktop Wallet is upgraded to include the Vaults/Loans function
- Implementation of the possibility to transfer a masternode to a new owner
- Possible deposit of a MN as collateral for a loan, dUSD lending only

In this update optional, not mandatory:
- Different fee rates for the freezer nodes
- Loan scheme 200% per default as additional security, can be changed by the user within the usual limits

In order to take into account the higher value of a freezer MN, the lending rates can be adjusted accordingly. According to the current value, a normal MN would have a collateralisation ratio of 670% and would be subject to a selected min. coll. ratio of e.g. 200%, which would cost 2% in fees. A 5Y freezer node could have a 25% discount on these fees, and a 10Y freezer node could have a 50% discount. The min. coll. ratio can be determined by the borrower as before within the scope of possibilities.

**Network Security**
The network would not be subject to instability at any time, as the masternodes would continue to operate even during an auction and a change of owner would be quick. Freezer MNs can still not be resigned after an owner change and keeps on its original freeze-duration (current share of freezer MN in the network: 31%, as of 26.1.2022, according to statistics from mydefichain). Also, the liquidation of a MN is unlikely, as with 20,000 Dfi of the MN and minimum collateralisation of 150%, the Dfi price would have to fall to 0.667 cents. In addition, if the existing vaults or a separate type of vault with otherwise similar functionality are equipped with this option, there is the security that the MN owner can add additional tokens for protection, such as dUSDC or dBTC, until the Dfi share reaches the usual minimum 50%, thus doubling the protection.

Since all masternode owners benefit from this, everyone was invited to help setting it up by helping to raise the Dip fees, which are 50 Dfi in total. These are already collected on this address: https://defiscan.live/address/dbDmgzKrBA86QiZtceUbEkUJrREQQGLxqj

Inspired by Agent Switters :)

-----------------------------------------

GERMAN

Bei Eröffnung der Freezer-Masternodes (MN) gab es die Idee irgendwann einmal einen Ownerwechsel einer Freezer-MN zu ermöglichen, also den Verkauf. Darauf aufbauend folgende Idee:

Der Besitzer eines Hauses kann sowohl Mieteinnahmen generieren, als auch sich eine Hypothek auf das Haus aufnehmen, um liquide zu sein. Dasselbe Finanzprinzip kann auch für Masternodes gelten: Die Mieteeinnahmen entsprechen dabei den Rewards, die Hypothek dem folgenden:

**Mögliche Hinterlegung einer MN als Sicherheit für einen Loan.** Dieser Loan kann maximal 10K in dUSD betragen, um beim Maximum einer Auktionstranche zu bleiben (alles Andere dürfte vorerst von der Umsetzung zu kompliziert werden). Fällt der Wert der MN unter die 10K (unwahrscheinlich, aber nicht unmöglich), kann das Collateral (hier die MN) ersteigert werden, so wie gehabt. Dh nach einer erfolgreichen Versteigerung findet ein Ownerwechsel statt. Laut dem Defichain-Masternode Telegram-Kanal ist die Funktion zum Übertragen eines Masternodes bereits programmiert, nur noch nicht implementiert. Da die Masternodes auf der Desktop-Wallet laufen, muss die Vault/Loan-Funktion dort hinzugefügt werden.

Ein Dfip würde also beinhalten:
- Desktop Wallet wird um die Funktion der Vaults/Loans ergänzt
- Implementierung der Möglichkeit eine Masternode auf einen neuen Eigentümer zu übertragen
- Mögliche Hinterlegung einer MN als Sicherheit für einen Loan, nur dUSD Beleihung

In diesem Update optional, nicht obligatorisch:
- Unterschiedliche Gebührensätze für die Freezer Nodes
- Darlehensregelung 200% als Standard für zusätzliche Sicherheit, kann vom Nutzer in den üblichen Rahmen verändert werden

Um den höheren Wert einer gefreezten MN zu berücksichtigen, können die Beleihungszinsen entsprechend angepasst sein. Nach aktuellem Wert hätte eine normale MN 670% Collateralization Ratio und würde bei einer gewählten Min. Coll. Ratio von z.B. 200% 2% Gebühren kosten. Bei einer 5Y gefreezten Node könnte ein Rabatt auf diese Gebühren von 25% erfolgen, bei einer 10Y gefreezten von 50%. Die Min. Coll. Ratio kann dabei wie bisher auch vom Loan-Nehmer im Rahmen der Möglichkeiten selbst bestimmt werden.

**Netzwerksicherheit**
Das Netzwerk wäre dadurch zu keiner Zeit einer Instabilität ausgesetzt, da die Masternodes sogar während einer Auktion weiterhin in Betrieb sind und ein Ownerwechsel schnell vonstatten geht. Freezer-MN können nach einem Ownerwechsel weiterhin nicht aufgelöst werden und behalten ihre ursprüngliche Freeze-Dauer bei (aktueller Anteil der Freezer-MN im Netzwerk: 31%, Stand 26.1.2022, laut Statistik von mydefichain). Auch ist die Liquidierung einer MN unwahrscheinlich, da bei 20.000 Dfi der MN und Mindestbesicherung von 150% der Dfi-Preis auf 0,667 Cent fallen müsste. Zusätzlich besteht die Sicherheit, wenn die bisherigen Vaults oder eine gesonderte Art von Vaults mit sonst gleicher Funktionsweise mit dieser Möglichkeit bestückt werden, dass der MN-Owner zusätzlich weitere Token zur Absicherung, wie dUSDC oder dBTC hinzufügen kann, bis der Dfi-Anteil die üblichen Mindest-50% beträgt, somit die Absicherung verdoppelt werden kann.

Da alle Masternode-Besitzer davon profitieren, wurde jeder eingeladen, bei der Einrichtung zu helfen, indem sie die Dfip-Gebühren, die insgesamt 50 Dfi betragen, gemeinsam aufbringen. Diese werden bereits unter dieser Adresse gesammelt:  https://defiscan.live/address/dbDmgzKrBA86QiZtceUbEkUJrREQQGLxqj 

Inspiriert von Agent Switters :)

**Comment by Dcshel** [comment]
sounds like a reasonable idea and option that should be allowed if it can be implemented without any major effects on the blockchain.  At least this should be allowed for those who have their assets frozen for 5 to 10 year periods as an additional benefit. Not so sure it's needed for those who are not locked in.  They can always pull out their assets and move them into other features, although it would encourage more people to set up Masternodes if they can  also utilize those assets by leveraging them and putting into other uses or mining.

**Comment by fmamar** [comment]
I would vote for this but it would have to be different than the standard dtoken vault, and maybe have a very conservative number on the collateral loan percentage to avoid liquidation as much as possible, and if liquidated then it should be put up for auction and remain as a node

**Comment by derstrecker** [comment]
> I would vote for this but it would have to be different than the standard dtoken vault, and maybe have a very conservative number on the collateral loan percentage to avoid liquidation as much as possible, and if liquidated then it should be put up for auction and remain as a node

Correct! I updated the proposal accordingly. Even though it should be part of the current Vaults as an extra MN-token, so 1. those who are using this option still can add additional collateral and by this double the hedge, and 2. inviting people to set up nodes, because they also can be used as for a loan (interesting for Dfi-hodlers regarding taxes).

**Comment by defiuser2** [comment]
I like the idea very much too. For me it is not needed to add some kind of a discount for the fees as this is a new usecase for the masternodes.
Furthermore I'd suggest to do a high loan scheme like 200 or 300 % per default as additional security. I think loans must than work on the desktop wallet too to link the loan to the owner address.
10 k seams also reasonable to make this request very easy. Also I'd say that these kind of vaults are just fixed for the node. 
The nodes on auction shall remain nodes and also remain locked. If someone graps it from the auction his upside for this locked node would be a shorter run time than 10 years as the node already exists.
Yeah go ahead and suggest this feature.

**Comment by derstrecker** [comment]
I added some suggestions into the original issue.

**Comment by Dcshel** [comment]
I don't see how it could be possible for an defaulted/ liquidated node to transfer ownership. If my node runs on my laptop or PC, or leased cloud space, I could easily shut it down and no rewards would go to lower of said assets. You would have to lock out assets of liquidated nodes assets and sell those off once in default.

**Comment by derstrecker** [comment]
> I don't see how it could be possible for an defaulted/ liquidated node to transfer ownership. If my node runs on my laptop or PC, or leased cloud space, I could easily shut it down and no rewards would go to owner of said assets. You would have to lock out DFI of liquidated nodes and sell those off once in default.

The option to transfer ownership is already available as code. As I understood how blockchains work, nodes are on the chain, like the coins, separate from the hardware. As soon as someone uses a MN as collateral, he/she has to agree for a possible transfer of ownership. This is written in the blockchain, not on ones hardware. But I am not an expert on this.

**Comment by Dcshel** [comment]
Actually that isn't correct. The Blockchain simply confirms the node is compliant and sends rewards to that nodes address. The node is a PC based transaction processing machine that randomly mints new blocks

**Comment by derstrecker** [comment]
> Actually that isn't correct. The Blockchain simply confirms the node is compliant and sends rewards to that nodes address. The node is a PC based transaction processing machine that randomly mints new blocks

Nevertheless there is already a code for MN transfer of ownership :).

**Comment by Jouzo** [comment]
DFIP was rejected https://github.com/DeFiCh/dfips/issues/107
