### ISSUE TITLE
BTC deposits from DeFiChain are currently disabled

### ISSUE THREAD

**Issue by kgr95** [DeFiCh/ain#1020]
#### What happened: My dBTC deposit from the DeFi Wallet to CakeDefi yesterday was not working. The acutal transfer went fine as you can see in the transaction https://defiscan.live/transactions/da4fab1eb47123aeb29efd47ae2d7e229f8938c9ccdc24f9aa39af90b18a19f4. But the dBTC haven't been arrived yet to CakeDefi. There is also no balance in the wallet of CakeDefi https://defiscan.live/address/dSuAWQdvdkuAzMqN5c7iQooacqoETgngZw.

After one day I get the information in CakeDefi that "_BTC deposits from DeFiChain are currently disabled_". What happens with by dBTC? Are they lost now? 

I'm thankful for you help!

Regards

**Comment by RoflWolke7** [comment]
Hi @kgr95,

you should better ask there: https://t.me/CakeDeFi_EN

The announcement stated:

Until we get further instructions from the DeFiChain Community, Cake DeFi has disabled:

👉 dBTC withdrawals
👉 dBTC deposits
👉 BTC-DFI liquidity pool entry and exit

Please do NOT attempt any of these as they will not be executed **and a deposit will be pending until it is resolved on the blockchain**.

IMHO nothing is lost but you have to wait for Cake that they reenable the processing...
