### ISSUE TITLE
outdated DNS seed for SPV

### ISSUE THREAD

**Issue by FirstClassCitizenFCC** [DeFiCh/ain#1025]
#### What happened:
If _bitseed.xf2.org_ is the only DNS seed available for SPV, running defid results in sending multiple (25-30) DNS queries per second.

#### How to reproduce it (as minimally and precisely as possible):

- block all seeds from [BRMainNetDNSSeeds](https://github.com/DeFiCh/ain/blob/7630137b3ea10269f564f13297f21b997735f38e/src/spv/bitcoin/BRChainParams.cpp#L30) except _bitseed.xf2.org_
- run defid

#### What are your environment parameters:
docker defi/defichain:latest

#### Anything else we need to know?:

- Allowing all DNS seeds resolved the issue.
- Bitcoin Core removed this seed in [#9730](https://github.com/bitcoin/bitcoin/pull/9730)
- dns query-status is _SERVFAIL_

```
# dig @1.1.1.1 bitseed.xf2.org

; <<>> DiG 9.16.15-Debian <<>> @1.1.1.1 bitseed.xf2.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 44015
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; EDE: 22 (No Reachable Authority)
;; QUESTION SECTION:
;bitseed.xf2.org.		IN	A

;; Query time: 32 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Fri Jan 07 18:44:36 CET 2022
;; MSG SIZE  rcvd: 50
```

**Comment by prasannavl** [comment]
Thanks @FirstClassCitizenFCC. Add to high priority lists for v3, where ICX is planned to be re-enabled.
