### ISSUE TITLE
Amount not correct when moving from Wallet to LM

### ISSUE THREAD

**Issue by djfuellen** [DeFiCh/ain#1026]
When moving from the wallet/funds screen to LM the amount of funds is not correct in the screen where you select the amound of funds you want to add. It seems outedet. Thus you cannout use the MAX function. You have to go back to the wallet and then back over Liquidity-> Click on the pool you want to add, then the amount is correct.

**Comment by shohamc1** [comment]
This issue seems to be related to the desktop wallet. Please open an issue [here](https://github.com/DeFiCh/app/issues/new/choose) if you are still facing this issue.
