### ISSUE TITLE
new blocks are not propagated to all nodes immediately

### ISSUE THREAD

**Issue by FirstClassCitizenFCC** [DeFiCh/ain#1042]
#### What happened:
Info about new blocks are not distributed well to all fullnodes. Fullnodes often receive no blocks for a long time and than receive multiple blocks in a few seconds. If you check my [logfile](https://gist.github.com/FirstClassCitizenFCC/2e52c56558fcc0f15ef797046a9c5b30) you will see as an example my node received a new chain tip at `2022-01-17T12:05:34Z`, than nothing until `2022-01-17T12:09:04Z` and the next 14 followed all between `2022-01-17T12:09:04Z` and `2022-01-17T12:09:27Z`. 

#### What you expected to happen:
One would expect every fullnode should receive a new block immediately after it was minted. Lightnodes otherwise have to wait longer than neccecary to get a confirmation for a transaction.

#### How to reproduce it (as minimally and precisely as possible):
- check debug.log of fullnode
- you even can refresh the Blocks-page of defiscan.live a couple of times the see new blocks do not come in immediately. 

#### What are your environment parameters:
v2.5.0

#### Anything else we need to know?:
observations:
- The next block after such a pause contains a lot of transactions, the other ones following mostly have just a few or only the coinbase transaction.
- Blocktimes are sometimes out of order (guess this is because the locale time of the minter is used)

Could this phenomenon be caused by the close proximity of the majority of masternodes at cake defi? A thought of mine is they could therefore primarily connect to each other.

**Comment by FirstClassCitizenFCC** [comment]
Does anyone have a clue how this can happen?

**Comment by Stonygan** [comment]
This is a false assumption. The nodes receive the blocks as they are mined. In one of the last hardforks last year a change was implemented (keyword: speedy miner), which has the disadvantage that the blocks are mined very irregularly. In the first second after a new block the masternodes have a multiple of the hashrate, which leads to the fact that very often several blocks come one after the other.
I just ran an evaluation on 5 fullnodes in 4 different data centers, all nodes got the new blocks at the same time and instantaneously when they were created. +/- 0.5 seconds.

**Comment by FirstClassCitizenFCC** [comment]
You are right. It was a premature assumption. I should have just stated my observations. My apologies!

I could not find any references of _speedy miner_, can you explain its purpose/advantages? Has it something to do with the addition of subnodes?
Does this mean a new block is either be found in the first second after the last one or it will take a couple of minutes? This would make the defacto blocktime also a couple of minutes instead of 30 seconds, since hardly any TX are included in a block found within a second.

Is this something that needs to be addressed?
