### ISSUE TITLE
Node crash when executed 'getblockstats 1548958'

### ISSUE THREAD

**Issue by trimat1** [DeFiCh/ain#1044]
Node crashed after executing 'getblockstats 1548958'.

Would expected to get the blockstats like feerates etc. from this block.

Tried it on 2 different Systems (GUI on Desktop and via CLI on Server installation), works repeatably.

System 1: Win10 with DefiWallet
System 2: Debian Server running defid, executing commands via SSH and defi-cli

**Comment by prasannavl** [comment]
Thanks for reporting @trimat1 - can confirm.
