### ISSUE TITLE
listvaulthistory command not working

### ISSUE THREAD

**Issue by salomonkarsten** [DeFiCh/ain#1047]
In the example of the listvaulthistory "vaultID"    command 
it states listburnhistory... on desktop wallet version 2.8.4 further the result states:

listvaulthistory {"vaultID":"xxxxxxxxxx"}
-vaultindex required for vault history

What is the vaultindex how to find it with only the vaultID?

**Comment by shohamc1** [comment]
Hey, you need to run the node with the `-vaultindex` startup parameter.

From the help dialog:
```
-vaultindex
       Maintain a full vault history index, tracking all vault changes. Used by
       the listvaulthistory rpc call (default: 0)
```
