### ISSUE TITLE
MinPrice when selling

### ISSUE THREAD

**Issue by mnannigm** [DeFiCh/ain#1103]
#### What would you like to be added:
When using the CLI and the poolswap or compositeswap command we can specify a maxPrice field but this is only useful in case we plan to buy a token. What I am missing is a minPrice field in case one wants to sell. 

#### Why is this needed:
DEX prices change quite heavily from block to block and I had many bad experiences when the price was suddenly much higher or lower. In the buying scenario the maxPrice field can protect me from paying too much but in the sell scenario we would benefit from the minPrice field to ensure we do not sell for less than expected.

**Comment by mnannigm** [comment]
Had some second thoughts about this and figured when, for instance selling DFI to receive USDT, the maxPrice is probably also usable in the sense that 1 USDT should require a max of 0.3333 DFI (assuming the price of DFI is at 3$). If the DEX price would suddenly be less, like only 2$, the price per USDT in DFI would be 0.5 DFI. 

I still need to verify that this works as I assume it to work but in that case, if we want to ensure we get at least 3USDT/DFI the maxPrice would be 0.3333. 

If that is true I think the minPrice is not such a high priority but still I guess it would be more straight-forward to use such a field. Up to you if you think it would be a convenient thing to use or not.

**Comment by solros** [comment]
Hi @mnannigm, your second thoughts are correct :-)!
On the DEX, you don't sell, you always buy! 
For example when you want to "sell" 1 DFI to USDT for a minimum price of 3 USDT/DFI, what you actually do is *buy* USDT for 1 DFI with a maximal price of 0.333 DFI/USDT. So the MaxPrice does exactly what you want.
On a CEX, you think in terms of buying and selling, but this somehow discriminates one token against the other. On a DEX, however, all tokens are equal and hence you cannot call one direction "buying" and the other "selling".
In my opinion this symmetry is very elegant.
I'd vote for closing this issue.
