### ISSUE TITLE
`testpoolswap` RPC should check for a direct swap first when `auto` is specified.

### ISSUE THREAD

**Issue by surangap** [DeFiCh/ain#1114]
#### What happened:
1. add a CAT-DFI pool.
2. call `testpoolswap` from CAT -> DFI with `path = auto`, `verbose = true`
3. response have as follows. note `pools` field.
`{ path: 'auto', pools: [ '2', '2', '2' ], amount: '48.48437068@0' }`

The above should be a direct swap since `CAT-DFI`  pool is present.
RCA
even in `compositeswap` check for a direct swap is done first and then goes to the `CalculateSwaps()` and `compositeswap()`
ref -> https://github.com/DeFiCh/ain/blob/c0a25f727f32c1b2c32a5120059276ec97e38bd2/src/masternodes/rpc_poolpair.cpp#L919

but in the scenario mentioned above, it will call `CalculateSwaps()` straight. ref -> https://github.com/DeFiCh/ain/blob/c0a25f727f32c1b2c32a5120059276ec97e38bd2/src/masternodes/rpc_poolpair.cpp#L1091

it could be that the `CalculateSwaps()` is unable to handle this scenario well.
But simply adding a check for a direct swap first should solve the issue(same as the `compositeswap` flow. ).
https://github.com/DeFiCh/ain/blob/c0a25f727f32c1b2c32a5120059276ec97e38bd2/src/masternodes/rpc_poolpair.cpp#L1091

**Comment by surangap** [comment]
relates to https://github.com/DeFiCh/jellyfish/pull/1074

**Comment by eli-lim** [comment]
It seems like CPoolSwap::CalculateSwaps / CalculatePoolPaths doesn't look for a direct path.

Just curious, which of the following are we looking to achieve for `testpoolswap`?
- Always use direct path if available
- Use best path (implying some composite path may yield an amount greater than direct - assuming that's even possible)
