### ISSUE TITLE
utxostoaccount creates a new address

### ISSUE THREAD

**Issue by goofy79** [DeFiCh/ain#1126]
I want to change to defi tokens to utxo with the command 
`./defi-cli utxostoaccount {"address":"amount of defi tokens"}`
but if i do this, i have a new address with 0.48993855 DFI on it. 
This can i see with the following command 
```
./defi-cli listaddressgroupings
[
  [
    [
      "dHxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      0.00000000
    ],
    [
      "dNxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      0.48993855
    ],
    [
      "dQxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      0.00999211,
      "Main Wallet"
    ],
    [
      "dRxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      0.00000000
    ],
    [
      "daxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      0.00000000
    ],
    [
      "daxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      0.00000000
    ]
  ]
]
```
than i have to send the tokens back with 
`./defi-cli sendutxosfrom "dNxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" "dQxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" 0.48993628`

![image](https://user-images.githubusercontent.com/11212295/156450726-352cd6ad-188c-49ec-8724-e148301f3678.png)

Every time i use the utxostoaccount command, i get a new address.
Thats strange ? and i don't know why ? 

BR
Goofy

**Comment by shohamc1** [comment]
This is the default behaviour for most UTXO blockchains (bitcoind will also do this by default), this is done to protect user's privacy ([more](https://en.bitcoin.it/wiki/Address_reuse)).

Being a Bitcoin fork, DeFiChain inherits the same behaviour of sending change to a new address.
