### ISSUE TITLE
Crash on boot with v2.9.3 on Mac desktop

### ISSUE THREAD

**Issue by jaspo77** [DeFiCh/ain#1158]
I'm hitting the following crash attempting to boot the v2.9.3 of the desktop wallet on mac. I've tried uninstalling and reinstalling with no success.

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [6758]

VM Regions Near 0x20:
--> 
    __TEXT                 000000010f192000-000000010f194000 [    8K] r-x/r-x SM=COW  /Applications/DeFi Wallet.app/Contents/MacOS/DeFi Wallet

Application Specific Information:
crashed on child side of fork pre-exec

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib        	0x00007fff735e5e41 nanov2_forked_calloc + 7
1   libsystem_malloc.dylib        	0x00007fff735d0f59 malloc_zone_calloc + 99
2   libsystem_malloc.dylib        	0x00007fff735d0ed9 calloc + 24
3   libobjc.A.dylib               	0x00007fff72269c40 allocateBuckets(unsigned int) + 29
4   libobjc.A.dylib               	0x00007fff722696d2 cache_fill + 283
5   libobjc.A.dylib               	0x00007fff7226916d lookUpImpOrForward + 527
6   libobjc.A.dylib               	0x00007fff722689d9 _objc_msgSend_uncached + 73
7   libxpc.dylib                  	0x00007fff7366f89e xpc_atfork_child + 125
8   libSystem.B.dylib             	0x00007fff7036aab8 libSystem_atfork_child + 59
9   libsystem_c.dylib             	0x00007fff734748ad fork + 40
10  com.github.Electron.framework 	0x000000011704d1ef uv_spawn + 527
11  com.github.Electron.framework 	0x000000011d7e2941 node::PromiseRejectCallback(v8::PromiseRejectMessage) + 234001
12  com.github.Electron.framework 	0x000000011808d1fb v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) + 12651

**Comment by shohamc1** [comment]
This seems to be an issue with the DeFiChain Wallet, please open an issue [here](https://github.com/DeFiCh/wallet/issues/new/choose) if you are still facing this issue.
