### ISSUE TITLE
Payback doesn't work while vault is halted

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#1164]
#### What happened:

While oracles where offline, I tried to payback the loan in this dToken (dVOO in this case). I received 
```
Test PaybackLoanTx execution failed:
Cannot payback loan while any of the asset's price is invalid
```

on node v2.6.2

#### What you expected to happen:

Loan should be able to be paid back even while vault is halted

#### How to reproduce it (as minimally and precisely as possible):

* create vault with loan in VOO
* oracle on VOO had no update for 3 hours -> vault gets frozen
-> try to pay back VOO. failed for me.
(i tried to pay back VOO and DUSD at once, not sure if this makes a difference)

**Comment by Bushstar** [comment]
@kuegi this is the correct behaviour for 2.6.2 and before. The 2.7.0 release will change this to let you payback native tokens while there are invalid prices in a vault.

**Comment by kuegi** [comment]
> @kuegi this is the correct behaviour for 2.6.2 and before. The 2.7.0 release will change this to let you payback native tokens while there are invalid prices in a vault.

oh perfect thx. Uzyns reply sounded like it should already be possible and didn't see it in the releasenotes of 2.6.2. wonderful news. thx.
