### ISSUE TITLE
sample in help of futureswap is wrong

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#1172]
https://github.com/DeFiCh/ain/blob/92223dcbb672ae1df195fbbd30b2ee7228ec6baa/src/masternodes/rpc_accounts.cpp#L2062

states as sample of the futureswap call:

`defi-cli futureswap dLb2jq51qkaUbVkLyCiVQCoEHzRSzRPEsJ 1000@DUSD TSLA`

but the call requires a number (the dtoken Id not name) as destination. so it should be

`defi-cli futureswap dLb2jq51qkaUbVkLyCiVQCoEHzRSzRPEsJ 1000@DUSD 19`

**Comment by Jouzo** [comment]
This was fixed in commit ddd19f4f3ba24c4a8685825f786af5082e88897f.
Destination can now be either 19 or TSLA
