### ISSUE TITLE
FutureSwaps are not adding the destination token to the total balance of the loanToken

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#1173]
sorry for missing it in the review, but I think we missed adding the created tokens to the total balance of the loanToken.

Since they are minted, they should be tracked in the loantoken, right?
the sources are "burned" but they stay within the smartcontract, so its fine to not remove them from the balance I think.

**Comment by kuegi** [comment]
just verified on testnet: newly created dtoken from the swap are not reflected in the minted amount of  `gettoken` call

**Comment by prasannavl** [comment]
Thanks @kuegi - you are correct. This indeed needs to be fixed. A `/live/economy/dfip2203_minted` attr is missing.
