### ISSUE TITLE
result of futureSwap is not listed in accounthistory

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#1174]
when doing a DFIP2203 futureSwap, the paying of the source token shows up in the history, but the resulting dToken (that is payed out on the futuresblock) is not shown. (but added correctly to the balance).

it is correctly tracked via `listfutureswaphistory` thou.

**Comment by prasannavl** [comment]
Hi @kuegi - this is correct - the beta version used the alternate RPC as a quick way to track it. This is no longer the case, and the actual master now includes specific TX types for this to be displayed in `listaccounthistory`.

**Comment by prasannavl** [comment]
Related: https://github.com/DeFiCh/ain/commit/ad82928543abf5cde662fd83ff213bd5df71c57d
