### ISSUE TITLE
defi-cli getmininginfo 

### ISSUE THREAD

**Issue by Kracht** [DeFiCh/ain#12]
Hi, just found a small typo...

````
~/.defi# defi-cli getmininginfo
error code: -32601
error message:
Method not found
````

but:

````
~/.defi# defi-cli getmintinginfo
{
  "blocks": 81776,
  "difficulty": 436865480.6849026,
  "isoperator": false,
  "networkhashps": 6.198374690712178e+16,
  "pooledtx": 0,
  "chain": "main",
  "warnings": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
}
````

Unintended typo I guess, instead of "getmininginfo" it is "getmin**t**inginfo" with an extra t.

I'm running  a docker node with the following specs
````
~/.defi# defi-cli -getinfo
{
  "version": 1000000,
  "protocolversion": 70015,
  "blocks": 81786,
  "timeoffset": 25,
  "connections": 8,
  "proxy": "",
  "difficulty": 287411770.450339,
  "chain": "main",
  "walletversion": 169900,
[...]
}
````

**Comment by prasannavl** [comment]
Hi @Kracht, 

Thanks for reaching out! It's intentionally `min**t**ing` with `t` :) Our consensus algorithm is a combination of proof of stake (PoS) along with Bitcoin's proof of work (PoW). Bitcoin uses proof of work to `mine` blocks. Defichain uses proof of stake to `mint` blocks. 

For more details, please have look at the whitepaper - https://www.defichain.io/white-paper/

**Comment by Kracht** [comment]
That totaly makes sense, feeling a bit dumb now ^^ thx for taking time to explain!
