### ISSUE TITLE
Memory Problems defid Version 2.7.0

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/ain#1218]
#### What happened:
After a few days of running, the memory of our server runs through the defid to almost 100%. Only a restart of defid fixes the problem. No errors in debug.log available.

#### What you expected to happen:
Free up memory
#### How to reproduce it (as minimally and precisely as possible):
defid is running, nothing else.

#### What are your environment parameters:
Servers with and without operators are affected.
We use txindex=1 and spv=1
Debian 11 buster/Ubuntu 20.04.4 focal. No difference if we have 8 or 16 GB memory

#### Anything else we need to know?:

![mem](https://user-images.githubusercontent.com/44975826/166811714-9f256c5f-1523-4409-a731-29de3836c4f5.png)

![top](https://user-images.githubusercontent.com/44975826/166811747-a3deaedd-e742-4af9-8afb-1e7d04022ed0.png)

We heard from many other users (e.g. Masternode Health Monitor Servers) that they have the same problem.

**Comment by prasannavl** [comment]
Thank you for this report. Could you please share more info if you have, like the config that you use and hardware specs? This is quite interesting info, as this seems to indicate some kind of a leak, however, this is the first report of such.

**Comment by prasannavl** [comment]
Note: We are aware of reports of regression since 2.7.0 that causes things to slow down on very high load conditions, but we didn't have co-relation yet, I'm keen to understand if these could be related.

**Comment by DerFuchs** [comment]
I've been seeing similar behavior. Defid did not crash - or at least I did not notice it - but memory consumption is going up during time.

My machine:
- Intel i7-7700K, physical
- 32 GB of RAM
- 500 GB NVME Raid
- Ubuntu 20.04.2 LTS
- running only defid and Master Node Health data collecting script, nothing else
- Yes, I know it is slightly overpowered :D

defi.conf:
```
rpcuser=****
rpcpassword=****
daemon=1
gen=1
spv=1
```

Maybe I can manage to get some anonymized data from the Master Node Health users, especially their memory usage over time.

**Comment by adrian-schnell** [comment]
my machine get nearly daily a RAM warning (>87% used)

- 8 GB RAM
- 160 GB SSD
- 4 AMD vCPU 
- Ubuntu 20.04.4 LTS
- running only defid and Masternode health (data collection via rpc)

```
daemon=1
gen=1
spv=1
masternode_operator=XXXXXX

addnode=seed.mydeficha.in:8555
```

**Comment by prasannavl** [comment]
Closing outdated / stale issues.
