### ISSUE TITLE
DEX Api extremly slow

### ISSUE THREAD

**Issue by endeffects** [DeFiCh/ain#1219]
Hallo,

your DEX Api for the following endpoint is extremly slow, could you please fix this?

https://api.defichain.io/v1/getsubgraphswaps

I also like to know if there is any other way to download the full list of transactions for the dex?

Regards

**Comment by shohamc1** [comment]
To get a list of transactions on a particular pair, you can use the [listPoolSwapsVerbose](https://jellyfishsdk.com/ocean/poolpairs#list-pool-swaps-verbose) endpoint.

The performance issue is unrelated to this repo. If you are still facing this performance issue, please open another issue [here](https://github.com/JellyfishSDK/jellyfish/issues/new/choose).
