### ISSUE TITLE
Future Swap is deactivated

### ISSUE THREAD

**Issue by solros** [DeFiCh/ain#1249]
Since the last price block 1896000, the future swap seems to be deactivated. 
`getfutureswapblock` returns 0.
If I try to do a future swap, I get:

```
Test DFIP2203Tx execution failed:
DFIP2203 not currently active
```

This should not happen.

**Comment by solros** [comment]
It seems to be working again now. What happened there?

**Comment by shohamc1** [comment]
Closing as the issue seems to be fixed, feel free to reopen if you have this error again.
