### ISSUE TITLE
Payback of small loan amount is not possible (v2.8.0)

### ISSUE THREAD

**Issue by Sebz84** [DeFiCh/ain#1321]
#### What happened:

Paying back a loan amount of 0.00000002 DUSD is not possible. The following error message is received:
_PaybackLoanTx: There is no loan on token (DUSD) in this vault! (code 16)_

It happens after the update to v2.8.0. I didn't have this problem before.

#### How to reproduce it (as minimally and precisely as possible):

getvault xxxxxx
{
  "vaultId": "xxxxxx",
  "loanSchemeId": "MIN150",
  "ownerAddress": "yyyyyy",
  "state": "active",
  "collateralAmounts": [
    "15500.00000000@DFI",
    "40986.50816415@USDC"
  ],
  "loanAmounts": [
    "0.00000002@DUSD",
    "2.57825822@TSLA",
    "0.08198612@BABA",
    "0.06802729@GME",
    "116.44145322@PLTR",
    "38.23391034@SPY",
    "0.29538156@SLV",
    "91.80994602@PDBC",
    "18.42686860@VNQ",
    "15.46857453@URTH",
    "0.00000780@TLT",
    "0.77502868@AMZN",
    "27.24728472@COIN",
    "0.24888140@EEM",
    "7.41789258@NVDA",
    "0.00000002@MSFT",
    "8.91391298@FB",
    "7.58702433@NFLX",
    "6.05089517@DIS",
    "0.03845730@MSTR",
    "21.95497719@MCHI",
    "0.26891309@INTC",
    "0.00000305@PYPL",
    "5.69315691@KO",
    "4.96052556@BRK.B",
    "0.11427581@PG",
    "0.07359770@SAP"
  ],
  "interestAmounts": [
    "0.00000001@DUSD",
    "0.00019107@TSLA",
    "0.00000093@BABA",
    "0.00006129@GME",
    "0.00098031@PLTR",
    "0.00030510@SPY",
    "0.00006258@SLV",
    "0.00293325@PDBC",
    "0.00134442@VNQ",
    "0.00049120@URTH",
    "0.00000001@TLT",
    "0.00001739@AMZN",
    "0.00022940@COIN",
    "0.00006804@EEM",
    "0.00022193@NVDA",
    "0.00000001@MSFT",
    "0.00028440@FB",
    "0.00060889@NFLX",
    "0.00014045@DIS",
    "0.00000052@MSTR",
    "0.00152127@MCHI",
    "0.00000896@INTC",
    "0.00000001@PYPL",
    "0.00018955@KO",
    "0.00013869@BRK.B",
    "0.00000727@PG",
    "0.00000171@SAP"
  ],
  "collateralValue": 74191.80870380,
  "loanValue": 35983.59323487,
  "interestValue": 0.95307412,
  "informativeRatio": 206.18232375,
  "collateralRatio": 206
}

paybackloan "{\"vaultId\":\"xxxxxx\",\"from\":\"yyyyyy\",\"amounts\":\"0.00000002@DUSD\"}"
error code: -26
error message:
PaybackLoanTx: There is no loan on token (DUSD) in this vault! (code 16)

#### What are your environment parameters:
v2.8.0 - Fort Canning Crunch

**Comment by prasannavl** [comment]
Closing outdated / stale issues.
