### ISSUE TITLE
Ticker of Meta (former FB) changed from FB to META. Oracle prices are therefore not up-to-date.

### ISSUE THREAD

**Issue by KunoWA** [DeFiCh/ain#1340]
#### What you expected to happen: The token 59 (dFB) needs to be updated accordingly:
new symbol: META
new symbolKey: META (if not used for Oracle requests this could stay FB)
new name: dMETA

#### How to reproduce it (as minimally and precisely as possible):
n/a

#### What are your environment parameters:
n/a

#### Anything else we need to know?:
The current oracle price of dFB is USD 189.06 but should be the last closing price USD 184.00.
reference: https://www.nasdaq.com/market-activity/stocks/meta

**Comment by joeldavidw** [comment]
The price `META` have been mapped to `FB` temporarily while the migration of the token symbols is being worked on. 

https://github.com/JellyfishSDK/oracle-adapters/pull/270

**Comment by KunoWA** [comment]
Dear Shoham

I can not follow your decision to close this issue. The token for Facebook is still wrongly called dFB but should be dMETA.

Should I open an issue with a better name?

Thanks for your help.
Best regards
Kuno

**Comment by shohamc1** [comment]
Hey, I believe this issue was about the oracle prices being incorrect - which seems to have been fixed.

It would be great if you can open a new issue for the name change of the token name and symbol.
