### ISSUE TITLE
wallet 2.14.0 Pool Add liquidity transaction not shown as such

### ISSUE THREAD

**Issue by binoculo** [DeFiCh/ain#1353]
[####]What happened:
Transaction ID f7eba1b8808d4988bfff2ba6ded27c9d96e947b482f6d7552ac795f36928bbf5 in Windows Defi Wallet Desktop App version 2.14.0 is shown as sending and retrieving transaction. See ![Transaktionen2022-06-20 2054](https://user-images.githubusercontent.com/77114600/174665941-3a121061-62f6-4e1e-aa78-f28bce9a9863.png)

#### What you expected to happen:
The transaction should be shown as 'Add liquidity' transaction as shown in Version 2.13.0 still. See ![Transaktionen2022-06-20 1136](https://user-images.githubusercontent.com/77114600/174665932-48241c4b-6bb6-4e9d-87e4-dc9adca42265.png)

#### How to reproduce it (as minimally and precisely as possible):
Check transaction ID in https://defiscan.live/transactions/f7eba1b8808d4988bfff2ba6ded27c9d96e947b482f6d7552ac795f36928bbf5

#### What are your environment parameters:
 
Lenovo ThinkPad 
Prozessor	Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz   2.59 GHz
Installierter RAM	8.00 GB (7.84 GB verwendbar)
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor

Edition	Windows 10 Home
Version	21H1
Installiert am	‎26.‎10.‎2020
Betriebssystembuild	19043.1766
Leistung	Windows Feature Experience Pack 120.2212.4180.0

https://github.com/DeFiCh/app/releases/download/v2.14.0/DeFi-Wallet-Setup-2.14.0.exe

#### Anything else we need to know?:
I tried it a second time on another Lenovo machine with Windows 11 installed. Same issue with Version 2.14.0.
I also did de-install 2.14.0 and re-installed 2.13.0 and the issue was still there (I did not re-index in between). Still the transaction was shown wrongly, what surprised me. Is that not a display issue?

This is my first issue I raise. Please let me know any feedback to submit a next issue better, if needed, thanks!

**Comment by shohamc1** [comment]
This seems to be an issue with the DeFiChain Wallet, please open an issue [here](https://github.com/DeFiCh/wallet/issues/new/choose) if you are still facing this issue.
