### ISSUE TITLE
Clear instructions on Node update

### ISSUE THREAD

**Issue by trimat1** [DeFiCh/ain#1374]
#### What would you like to be added:

more clear description on what to do when releasing a node update.
so not just 'need to reindex' or 'load snapshot', but concrete CLI command on what to do.
so i.e. start 'defid -reindex' or run 'defi-cli rescanblockchain' or - for loading the snapshot - the few commands to get zip on server, unpack it and put it in the right folder (or if available a command)

#### Why is this needed:

little to barley no work.
make it easier for (new) (master-)node operators to update without special knowledge

**Comment by shohamc1** [comment]
The [handbook has a section on upgrading defid](https://defich.github.io/handbook/guides/upgrading.html). If you have any suggestions for the handbook, do [open an issue on the handbook repo](https://github.com/DeFiCh/handbook/issues/new).
