### ISSUE TITLE
RPC requests -> Node stops syncing

### ISSUE THREAD

**Issue by nico89-exp** [DeFiCh/ain#1376]
Hello,

I'm using Defichain since several months in form of a Definode (https://github.com/DefiNode/DeFiNode).

Since the update to 2.9.0 and then 2.9.1 the wallet interface via RPC is not working anymore. The node stops syncing (no more UpdateTips coming in) and I receive 

WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting

error messages. Chaging the mentioned setting actually doesn't change anything. 

I tried a complete reinstall with fresh compilation of node and wallet -> no change.

Best,
Nico

**Comment by nico89-exp** [comment]
Seems to be connected to [#1211](https://github.com/DeFiCh/app/issues/1211). When a "history" tab is called the node crashes and I guess RPC calls start to pile up until the overflow. As long as no "history" tab is called it seems to work.

**Comment by prasannavl** [comment]
Closing outdated / stale issues and is currently not actionable.
