### ISSUE TITLE
Unable to add previously used address

### ISSUE THREAD

**Issue by yhurynovich** [DeFiCh/ain#1377]
I'm unable to add a previously used address to the "receive addresses" list and I suspect that balances from this address are not included too.

The application says: "Invalid address. Please check that this belongs to you."

![177889426-0d2c0421-ed20-4030-8e27-572ff175421a](https://user-images.githubusercontent.com/6166796/177891401-f232d51c-03bd-4cc5-937b-c35b9ae8b259.png)

https://defiscan.live/address/dRLhMF6EPw9jYzncS1mQokATXRp9jAuUVW

getaddressinfo "dRLhMF6EPw9jYzncS1mQokATXRp9jAuUVW"
{
  "address": "dRLhMF6EPw9jYzncS1mQokATXRp9jAuUVW",
  "scriptPubKey": "a91482c33d82a5d9bd77f8293f22e7a55ed90a693ebf87",
  **"ismine": false,**
  "solvable": false,
  "iswatchonly": false,
  "isscript": true,
  "iswitness": false,
  "ischange": false,
  "labels": []
}

**Comment by shohamc1** [comment]
Hey thanks for opening the issue. Can you check if you have loaded the correct wallet using the `loadwallet` RPC?

**Comment by shohamc1** [comment]
Closing as stale, feel free to reopen if this is unresolved.
