### ISSUE TITLE
The method "testpoolswap" calculates the wrong value from DFI to DUSD

### ISSUE THREAD

**Issue by Kolibri1990** [DeFiCh/ain#1397]
#### What happened:

A poolswap from 1 DFI in DUSD gives 1.12 DUSD, but testpoolswap from 1 DFI in DUSD gives you 0.79 DUSD.

The testpoolswap calculation of DFI in DUSD is wrong.

Is it possible that the stabilization fee is deducted?

#### What you expected to happen:

Same calculation like poolswap

#### What are your environment parameters:

DeFiChain Node 2.9.2

#### Anything else we need to know?:

Maybe it is since the new stable pools are life?
Is it possible that the stabilization fee is deducted?

**Comment by pawn-police** [comment]
I was about to report the same issue. I am also on 2.9.2 and this is what I have tried:
`./defi-cli.exe testpoolswap '{"amountFrom":1000.0,"tokenFrom":"DFI","tokenTo":"DUSD","from":"dLXs788fWMpGoar1WzDnLoNCNYyZVPPozv","to":"dLXs788fWMpGoar1WzDnLoNCNYyZVPPozv"}' "auto" `
Results in 797.70634644@15 which is much lower than expected.

I have also checked that the correct pool was chosen and this seems to be the case. 
`path=direct, pools=[17]`
