### ISSUE TITLE
Inconsistent results from listaccounthistory

### ISSUE THREAD

**Issue by RomanShumkov** [DeFiCh/ain#1414]
#### What happened:
listaccounthistory returns different values in "amounts" field of the same LM Commission history record when querying with different maxBlockHeight parameter values.

#### What you expected to happen:
Expecting same LM history record (same owner, blockHash, type, poolID) to have constant value in "amounts" property regardless of which listaccounthistory parameters were used.

#### How to reproduce it (as minimally and precisely as possible):
Set up defichain node v2.9.2 and restore from the following [snapshot](https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/snapshot-mainnet-2121091.zip).
Run the following script:
```typescript
    let address = '<censored>';// PM me for address example
    let predicate = function(x) {
      return x.blockHash === '393023a930713382f2fd07dec2ee023a52f174ef0b021e2607086e978e0864e9'
        && x.owner === address
        && x.poolID === '17'
        && x.type === 'Commission';
    }

    let params = {
      no_rewards: false,
      token: 'DFI',
      maxBlockHeight: 1666579,
      depth: 501,
      limit: 5000
    };
    let item = (await rpcClient.account.listAccountHistory(address, params)).filter(predicate)[0];

    params.maxBlockHeight += 1;
    let sameItem = (await rpcClient.account.listAccountHistory(address, params)).filter(predicate)[0];

    console.log(
      item.owner === sameItem.owner,
      item.blockHash === sameItem.blockHash,
      item.type === sameItem.type,
      item['poolID'] === sameItem['poolID'],
      item.amounts[0] === sameItem.amounts[0]
    );
```
**Expected console output**: true true true true true
**Actual console output**: true true true true false

#### What are your environment parameters:
Mac OS M1

#### Anything else we need to know?:
1. I have tried starting node with -rpccache=0 but it didn't help.
2. I assume that any address holding DUSD-DFI token on 28th of February, 2022 can be used to reproduce the issue.
3. I can share my address in PM.

**Comment by shohamc1** [comment]
Unable to reproduce on 2.11.1. Can you try using the latest version available? Feel free to reopen if the issue still exists on your end.
