### ISSUE TITLE
Account history and custom TX contain conflicting information

### ISSUE THREAD

**Issue by pawn-police** [DeFiCh/ain#1496]
#### What happened:
The account history entry and corresponding custom TX both specify a different "to token"

#### What you expected to happen:
I expected the "to token" to be the same in both the account history entry and corresponding custom TX.

#### How to reproduce it (as minimally and precisely as possible):
```
defi-cli getcustomtx 727460c2d402404eb90335b1bca3dcd94b8434634f8dfa79539370601752f1ed
{
  "type": "PoolSwap",
  "valid": true,
  "results": {
    "fromAddress": "dE4UnQhJFC1UmYgLaEDTYGpzsruqD55XyP",
    "fromToken": "2",
    "fromAmount": 0.00000644,
    "toAddress": "dVorVwqVYshUVMRLqPt6rWQBowZ1U5modL",
    "toToken": "2",
    "maxPrice": 0.00006779,
    "compositeDex": "BTC-DFI"
  },
  "blockhash": "0521fe666637aae30c11d215903a56320ff7172a965bcf7d6cbcc7276f5eaccb",
  "blockHeight": 1599588,
  "blockTime": 1644043031,
  "confirmations": 682869
}

defi-cli getaccounthistory dE4UnQhJFC1UmYgLaEDTYGpzsruqD55XyP 1599588 1
{
  "owner": "dE4UnQhJFC1UmYgLaEDTYGpzsruqD55XyP",
  "blockHeight": 1599588,
  "blockHash": "0521fe666637aae30c11d215903a56320ff7172a965bcf7d6cbcc7276f5eaccb",
  "blockTime": 1644043031,
  "type": "PoolSwap",
  "txn": 1,
  "txid": "727460c2d402404eb90335b1bca3dcd94b8434634f8dfa79539370601752f1ed",
  "amounts": [
    "-0.00000644@BTC"
  ]
}

defi-cli getaccounthistory dVorVwqVYshUVMRLqPt6rWQBowZ1U5modL 1599588 1
{
  "owner": "dVorVwqVYshUVMRLqPt6rWQBowZ1U5modL",
  "blockHeight": 1599588,
  "blockHash": "0521fe666637aae30c11d215903a56320ff7172a965bcf7d6cbcc7276f5eaccb",
  "blockTime": 1644043031,
  "type": "PoolSwap",
  "txn": 1,
  "txid": "727460c2d402404eb90335b1bca3dcd94b8434634f8dfa79539370601752f1ed",
  "amounts": [
    "0.09569930@DFI"
  ]
}
```

#### What are your environment parameters:
Full node 2.11.1 on Ubuntu

#### Anything else we need to know?:
All the instances I have found so far:
[all-transactions.txt](https://github.com/DeFiCh/ain/files/9693824/all-transactions.txt)

Some examples from the file:
- https://defiscan.live/transactions/1383676f0a92aeed44f18d04bccd5b78df7c38aecf390c7ac802a45db38adea8
- https://defiscan.live/transactions/233c81c890695b0873de507b232376bec377d557b3b126a7a896f441b007d9aa
- https://defiscan.live/transactions/727460c2d402404eb90335b1bca3dcd94b8434634f8dfa79539370601752f1ed
- https://defiscan.live/transactions/0865dfb2f8d42e6a83a9d094eeeec6a19bfd38c79773addc112a71ace5d1b131
- https://defiscan.live/transactions/ab8aad9799870d750d714bc3dcad194bcd6fec67018200add7746b975876c055
- https://defiscan.live/transactions/a32d15a99374ea513c4dcf69f88783a0a6b8f07e6f93792901f67667678be5fe
- https://defiscan.live/transactions/aa46b66018f54643d1e53500bfe7405390d080c855063f9f2f70280283707260

**Comment by shohamc1** [comment]
Hey, thanks for opening this issue. Were these transactions submitted using the `defi-cli`, the desktop/light wallet or some other wallet? Were you trying to swap from BTC to DFI, or were you trying a BTC to BTC transaction?

/triage accepted
