### ISSUE TITLE
Testnet Token dRANDOM + Random Number Generator as oracle

### ISSUE THREAD

**Issue by ghost** [DeFiCh/ain#1506]
#### What would you like to be added:
On Testnet
Create new dRANDOM Token as Loan Token
Create dRANDOM-DUSD LM Pool
Create Oracle for dRANDOM Token: Random Number between 100 - 500 every 15 minutes

#### Why is this needed:
Testing Price movements for vault bots like vault-maxi, defichain Wizard

**Comment by bernd-mack** [comment]
what about using a more predictable pricemovement than a random?
e.g. a sinus  chart or maybe we just the possibility to add some oracles with a "release" button to trigger a pump or dump on the custom token.

**Comment by prasannavl** [comment]
v3 has foundational elements to redistribute foundation keys for testnet so open sourced oracles can be accepted into testnet easier. 

That being said, both sin / cos based oracles as well as random ones would definitely be helpful ones to have -- would suggest starting with an open source oracle that can be then be submitted as a proposal to be accepted into testnet.

**Comment by prasannavl** [comment]
Closing outdated / stale issues.
