### ISSUE TITLE
skip collateral_factor check when `-jellyfish_regtest` args are present

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/ain#1509]
#### What would you like to be added:

We need https://github.com/DeFiCh/ain/pull/1473 this merged and released.

#### Why is this needed:

While the idea of introducing a collateral factor check is valid and undoubtedly justified for obvious reasons, it presents difficulty to downstream applications that rely on the previous condition to be valid. Once we grandfathered a scenario such as this in, it's almost an impossible feat to change them.

On JellyfishSDK alone, over 500 unique tests were mocked within the construct of the previous condition. Changing those tests isn't a small feat, as manual calculations were done and estimated many months of effort were poured into that. We simply don't have the resources right now, as the team is working on MetaChain. If we were to add in DeFiScan and DeFiChain Wallet tests, that's at least a few thousand scenarios and >10k assertions that must be updated. 

Currently, those subsystems are using a "HEAD" image of #1473 for testing. Which isn't sustainable, we need #1473, or a version of it merged so that JellyfishSDK and its ecosystem can follow the latest release.

**Comment by prasannavl** [comment]
Just want to be clear: the solution you're seeking by merging #1473 will create incorrect testing condition after the fork to satisfy the past.

That said, would be open to adding network regtest + a combination flag for `-skip-loan-collateral-validation` as a workaround if that helps, so it's self descriptive and doesn't create weird caveats down the line that's difficult to reason with out of context. Should help workaround this if it makes life easier for downstream migration.

**Comment by fuxingloh** [comment]
> That said, would be open to adding network regtest + a combination flag for `-regtest-skip-loan-collateral-validation` as a workaround if that helps, so it's self descriptive and doesn't create weird caveats down the line that's difficult to reason with out of context. Should help workaround this if it makes life easier for downstream migration.

Yup, I think `-regtest-skip-loan-collateral-validation` is better, let's go with that.
