### ISSUE TITLE
dToken to dUSD future swap, gets destination "0"

### ISSUE THREAD

**Issue by sambP** [DeFiCh/ain#1526]
The RPC interfaces delivers the wrong destination token id when using the future swap with dUSD as the destination.

Example TX: https://defiscan.live/transactions/da6311531a42b52d6e2a8857566c079d1590e9ab9d43bf3e76a7a2e582e74ba0
This is a dFB to dUSD future swap. Not dFB to DFI. 

The bug report is only about the wrong rpc result, not about the future execution itself.

**Comment by shohamc1** [comment]
Hey, thanks for this issue. This was a frontend bug on DeFiScan which has been fixed now. ![image](https://user-images.githubusercontent.com/7486955/199385007-86884da2-cbb6-4bea-892c-53707ed5c1bf.jpeg)

**Comment by sambP** [comment]
But it wasn't only a defiscan bug. The RPC on 2.11.1 is returning also "0" instead of the dUSD token id.

**Comment by shohamc1** [comment]
This is expected behaviour as the user does not set the destination when doing a dToken -> DUSD future swap (destination is always DUSD). The empty field is just serialised to zero.

**Comment by sambP** [comment]
Okay, I got your point there, but the token id of DFI is also "0" and the normal RPC doesn't know about this exception. The defiscan bug was the perfect example of that. It's just not optimal API design in my option. But anyway, pretty sure you have more important things to do...
