### ISSUE TITLE
v3.0.0-rc1 Testnet: payback token during halted vault fails

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#1561]
#### What happened:
* on testnet the oracles are currently down so all vaults are halted.
* trying to pay back a DUSD loan results in `PaybackLoanTx: No such loan token id 11 (code 16)` (note that on testnet, DUSD is token 11)

#### What you expected to happen:

payback of loans should work normally during halted vaults

#### How to reproduce it (as minimally and precisely as possible):

* testnet version of mydefichain where vaults are halted due to missing oracle data

**Comment by prasannavl** [comment]
Fixed by #1562

**Comment by prasannavl** [comment]
This particular instance was due to a different bug that affected attributes overall, causing spurious errors which included payback, which is fixed by #1562

**Comment by prasannavl** [comment]
Closing outdated / stale issues.
