### ISSUE TITLE
lower Onchain gov cycles in testnet

### ISSUE THREAD

**Issue by bernd-mack** [DeFiCh/ain#1602]
#### What happened:
Onchain governance cycles are far too big to test, should be lowered same as masternode creation/update and resigntimes so a few hours

#### What you expected to happen:
create a onchain governancerequest and do not wait 2 months :)
https://defiscan.live/blocks/countdown/1560000?network=TestNet
![image](https://user-images.githubusercontent.com/76614620/204022889-8afa45ed-5f13-4fe8-9b4c-4b6b38612eab.png)

#### How to reproduce it (as minimally and precisely as possible):
http://tc01.mydefichain.com/listgovproposals/

#### What are your environment parameters:
testnet 3.0.0 rc5 

#### Anything else we need to know?:
-

**Comment by Jouzo** [comment]
Proposal voting period has been reduced to 2880 blocks on testnet.
You can check the voting period with :
```
defi-cli -testnet listgovs | grep voting_period
 "v0/gov/proposals/voting_period": "2880"
```
Each proposal voting period is saved on creation. That means that this voting period change only applies to new proposal. 

I just created a new proposal to check. You can now run `defi-cli listgovproposals` or check link http://tc01.mydefichain.com/listgovproposals/ and see that new proposals have a shorter voting period.

```
[
    {
        "amount": 1893.0,
        "approvalThreshold": "50.00%",
        "context": "Achtzehnhundertdreiundneunzig",
        "contextHash": "",
        "currentCycle": 1,
        "cycleEndHeight": 1560000,
        "fee": 18.93,
        "feeBurnAmount": 9.465,
        "payoutAddress": "tibhmC1iRrk72ZViNrYyA9kYw1tCGjF6XG",
        "proposalEndHeight": 1820000,
        "proposalId": "f9fb807b95b52eb9848baa302c419341d8868ac593c55d858d773c8446bdee24",
        "quorum": "1.00%",
        "status": "Voting",
        "title": "VfB CFP",
        "totalCycles": 3,
        "type": "CommunityFundProposal",
        "votingPeriod": 130000
    },
    {
        "amount": 0.0,
        "approvalThreshold": "66.67%",
        "context": "Mic check 1,2,3",
        "contextHash": "",
        "currentCycle": 1,
        "cycleEndHeight": 1391040,
        "fee": 50.0,
        "feeBurnAmount": 25.0,
        "payoutAddress": "",
        "proposalEndHeight": 1393920,
        "proposalId": "f43079fa1b94149471d731e9c24b3493a171c7580a454327bf03966252d5af4c",
        "quorum": "1.00%",
        "status": "Voting",
        "title": "Jouzo VOC",
        "totalCycles": 2,
        "type": "VoteOfConfidence",
        "votingPeriod": 2880
    }
]
```

**Comment by bernd-mack** [comment]
perfect, thank you.
