### ISSUE TITLE
v 3.0.0 reindex testnet from 0 stops at 1372460 with bad custom tx

### ISSUE THREAD

**Issue by bernd-mack** [DeFiCh/ain#1611]
#### What happened:
Sync from block 0 with latest relase [3.0.0](https://github.com/DeFiCh/ain/releases/tag/v3.0.0) on testnet stopped at height=1372460

```
reconsiderblock e25c037c402ab8327e5a88021c839145d073128eca37e9dcbb6be04f538d5085
bad-custom-tx (code 68)
2022-11-27T13:26:47Z ERROR: ConnectBlock: ApplyCustomTx on 59e2b91d69879f22b2cc25be2d5468f928fffe2d730cf39e858bc6d6c8ad3baf failed with SetGovVariableTx: ATTRIBUTES: Cannot be set before GrandCentralHeight
2022-11-27T13:26:47Z InvalidChainFound: invalid block=e25c037c402ab8327e5a88021c839145d073128eca37e9dcbb6be04f538d5085  height=1372461  log2_work=78.428139  date=2022-11-15T16:28:42Z
2022-11-27T13:26:47Z InvalidChainFound:  current best=ec66376440b3de28a6144f2d44d022a91c7cdf9fe8404239d04af9957b12bf64  height=1372460  log2_work=78.428138  date=2022-11-15T16:26:34Z
2022-11-27T13:26:47Z ERROR: ConnectTip: ConnectBlock e25c037c402ab8327e5a88021c839145d073128eca37e9dcbb6be04f538d5085 failed, bad-custom-tx (code 68)
```
#### What you expected to happen:
sync from 0 to birthday ocean latest block

#### How to reproduce it (as minimally and precisely as possible):
set up testnet Node with 3.0.0

#### What are your environment parameters:
`getversioninfo
{
  "name": "DeFiChain",
  "version": "3.0.0",
  "numericVersion": 3000000,
  "fullVersion": "DeFiChain:3.0.0",
  "userAgent": "/DeFiChain:3.0.0/",
  "protoVersion": 70034,
  "protoVersionMin": 70023,
  "rpcVersion": "1",
  "rpcVersionMin": "1",
  "spv": {
    "btc": {
      "version": 70013,
      "min": 70002,
      "userAgent": "/bread:2.1/"
    }
  }
}`

**Comment by prasannavl** [comment]
Hmm.. It's a `setgov` TX. 

The only setgov TX that should throw that error is if there's a Grand Central value that's being set before on testnet: https://github.com/defich/ain/blob/pvl/debug-2/src/masternodes/govvariables/attributes.cpp/#L1505-L1513. 

Looking into it.

**Comment by prasannavl** [comment]
TX 59e2b91d69879f22b2cc25be2d5468f928fffe2d730cf39e858bc6d6c8ad3baf

```
040000000100030929fff63aa476df7925f8039472292b72eb4486e997ff9a000f23f5bc84010000006a473044022016cfa770cada2fa90de7883575fe9c64155db394773fb979fde6987c7f03d1b60220681c6e427632c9d6d6f8bb9c9666f0f594c4b28187b4da9825757197803ebabe0121030e73d57cc3cd9a450d6d34ba68b1b241e9a427f4ff929ed92c333a990315e4b9ffffffff020000000000000000226a2044665478470a41545452494255544553010000000061680000006b0000000001002ea1394a000000001976a914e5ed1bfa532e2358e964381a70e0df6d4dd0041988ac0000000000
```

Which is:

```
{
  "txid": "59e2b91d69879f22b2cc25be2d5468f928fffe2d730cf39e858bc6d6c8ad3baf",
  "type": "SetGovVariable",
  "valid": true,
  "results": {
    "ATTRIBUTES": {
      "v0/params/feature/gov-foundation": "true"
    }
  }
}
```

So, the v3.0.0 node is correct to reject the block. Looking deeper to see if/how/why 2.11.1 node accepted this TX to be a part of the 2.11 testnet chain

**Comment by Jouzo** [comment]
There's a new chain without this transaction.
Blockhash for block `1386352` is `e1dd25391cf27fa04adb9b67990cae788fbb302f06d57ea144a83a13e36725dd`
