### ISSUE TITLE
Updatemasternode fails

### ISSUE THREAD

**Issue by mjollnir14** [DeFiCh/ain#1639]
DeFi Blockchain Daemon version v3.0.1
blockheight 2479181

`
$ defi-cli -rpcwallet=black2-owner updatemasternode "3redactedRedactedRedacted" '{"operatorAddress":"8RedactedRedacted"}'

error code: -32600
error message:
Test UpdateMasternodeTx execution failed:

Updating masternode operator address not currently enabled in attributes.
`

Key missing in attributes.h ?

**Comment by Stonygan** [comment]
The Attributes are not activated yet.
You can check it here:
https://api.mydefichain.com/v1/listgovs/

When you see something like:

```
"v0/params/feature/mn-setrewardaddress": "true",
"v0/params/feature/mn-setoperatoraddress": "true",
"v0/params/feature/mn-setowneraddress": "true",
```

its activated and usable.
