### ISSUE TITLE
creategovcfp ignore Parameter cycle

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/ain#1646]
#### What happened:
```
creategovcfp {"title":"CFP-2212-04","context":"mydefichain-12","amount":10000,"cycle":"12","payoutAddress":"tjabbjqtGyme56gEbDCfoXx4bR1D88QgF6"}
3b22fd6410258b26c56aa23c49bfd11be3dbe43a73c0536e0df28b9bc6fb05d6
```

{
        "amount": 10000.0,
        "approvalThreshold": "50.00%",
        "context": "mydefichain-12",
        "contextHash": "",
        "creationHeight": 1408688,
        "currentCycle": 1,
        **"cycleEndHeight": 1414080,**
        "fee": 100.0,
        "payoutAddress": "tjabbjqtGyme56gEbDCfoXx4bR1D88QgF6",
        **"proposalEndHeight": 1414080,**
        "proposalId": "3b22fd6410258b26c56aa23c49bfd11be3dbe43a73c0536e0df28b9bc6fb05d6",
        "quorum": "1.00%",
        "status": "Voting",
        "title": "CFP-2212-04",
        "**totalCycles": 1,**
        "type": "CommunityFundProposal",
        "votingPeriod": 2880
    },

#### What you expected to happen:
Create CFP with Cycle, dont ignore Cycle.

#### How to reproduce it (as minimally and precisely as possible):
Create Proposal with more then 1 Cycle.

#### What are your environment parameters:
Testnet, version 3.0.1

**Comment by Jouzo** [comment]
Hi @Stonygan,
The expected key is `cycles` with a s

**Comment by Jouzo** [comment]
I'll open a PR to validate the input
