### ISSUE TITLE
Avoid excessive CPU usage when unresolvable entry in SPV DNS seeds

### ISSUE THREAD

**Issue by Bushstar** [DeFiCh/ain#1653]
When SPV has a Bitcoin DNS seed that cannot be resolved this results in high CPU usage. The PR below reverts changes to these seeds which included one which does not resolve.

https://github.com/DeFiCh/ain/pull/1652

When comparing 2.7.0 and [master](https://github.com/DeFiCh/ain/commit/221a8489a632098f1dbb1cc1af84de98aba369c6) via perf, the top two results in master were both utilising 37% of the CPU on object libc.so.6 symbol __resolve_conf_allocate. With the above PR merged __resolve_conf_allocate could not be seen on the first page with all results above 1%.

SPV should be updated to not utilise high CPU if a Bitcoin seed is unable to resolve.

**Comment by prasannavl** [comment]
Resolved by https://github.com/DeFiCh/ain/pull/1652
