### ISSUE TITLE
Missing DFI Token  , with Defichain BNB Bridge

### ISSUE THREAD

**Issue by gittagit123** [DeFiCh/ain#1674]

**Comment by gittagit123** [comment]
> #### What happened: i send Dfi about the Defichain-bridge.com-  after 1 hour waiting , i try to recover the Transaktion.  But Error "signatures have invalid lenth/count: 0"

Txid and Adress are right
> #### What you expected to happen: lost my Dfi
> #### How to reproduce it (as minimally and precisely as possible):
> #### What are your environment parameters:dfi investor
> #### Anything else we need to know?: Hope i become Support and my DFI Token back. Thanks

**Comment by shohamc1** [comment]
Hey, this repository is not related to the Binance Bridge, you can try opening an issue [here](https://github.com/muirglacier/bridge-ui/issues) instead.

**Comment by gittagit123** [comment]
But my Dfi are on the DeFiChain now and not Binance. 
I can send the Dfi Transaktion ID

**Comment by decentralize7** [comment]
hello guys, i've sent funds from dfi to bsc. my dfi tokens are stucked in a loop, at least the frontend says so. the tx is confirmed though!
