### ISSUE TITLE
help of minttokens does not mention the possibility to mint to address

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#1675]
currently `help minttokens` only mentions the possibility to mint to your own address. missing the information and sample for minting to another address

tested in 3.2.0

**Comment by shohamc1** [comment]
```
> defi-cli minttokens 10@symbol '[{"txid":"id","vout":0}]' address
```

An example is currently present in the help dialogue on minting to an address. However this does not inform the user on the possibility to use a JSON object in the CLI for passing arguments, or the fact that UTXOs may be empty if not using JSON in the CLI. 

#1677 addresses these issues by adding the examples for these scenarios.

**Comment by kuegi** [comment]
thx @shohamc1 
I honestly didn't realize that there is an address parameter AFTER the utxos. every other call has the utxos as last parameter. also the "to" in this version is not marked as optional.

**Comment by shohamc1** [comment]
The parameter was kept after UTXOs to not break any existing applications using the RPC.

The `to` argument is marked optional - in the help dialogue, if an argument is not marked as `required`, it is optional. 

It seems that arguments that are `OMITTED_NAMED_ARG` show up as `(type, optional)` in the help dialogue whereas arguments that are `OMITTED` simply show up as `(type)`. This seems a bit confusing as one is marked explicitly while the other is not.
