### ISSUE TITLE
paybackloanwithcollateral in listaccounthistory

### ISSUE THREAD

**Issue by BenTStark** [DeFiCh/ain#1680]
#### What happened:
See for example transaction 3b5be9eefee54e7467e5e1b01bd56da4d0a06fbf865ce0205ce51f2da731c006 at block 2519215.
When I try to find it with listaccounthistory, I do not find this transaction

#### What you expected to happen:
with 
`listaccounthistory df1qne6936a5jha0ctlnm5676g6wpc47y73xd6qe6t '{"maxBlockHeight":2519216,"depth":2}' `
this transaction should be listed

#### What are your environment parameters:
Node Version 3.0.1

#### Anything else we need to know?:
As far as I can see, this may occur at so the so called looped vaults where you payback with collateral. I see at least 400 transactions with this issue in my data.

**Comment by shohamc1** [comment]
Possibly related to https://github.com/DeFiCh/ain/issues/1536

**Comment by shohamc1** [comment]
Fixed in 3.2.4.
