### ISSUE TITLE
❓ dUSD for transaction fees

### ISSUE THREAD

**Issue by mrgrauel** [DeFiCh/ain#1684]
This started as a discussion on reddit. Before I write a DFIP I'd like to get developer feedback.

Original Reddit: https://www.reddit.com/r/defiblockchain/comments/ycjpxv/dusd_for_transaction_fees/

#### What would you like to be added:
* use `dUSD` for transaction fees

##### Motivation

As a crypto beginner I never understood why the transaction fees have to be paid in the main tokens of the blockchain. I always had to convert the amount to a USD or EUR price to understand exactly what I was paying now. In my experience, a few months or years later, friends also had a similar or identical problem with transaction fees.

Another point is that all blockchains become more expensive in bull markets. It is usually justified by the number of transactions, but the increase in price of the token alone makes each transaction more expensive.

##### Problem

Most blockchains suffer from high transaction fees as native tokens become more expensive.

##### Proposal

* Use dUSD for transaction fees on MetaChain

##### How does this benefit the DeFiChain community?

* predictable transactions fees in every market situation
* no conversion necessary for new users, which improves the user experience

#### Why is this needed:
* onboarding new users is easier
* tx fee is easier to value

**Comment by prasannavl** [comment]
Closing outdated / stale issues and is currently not actionable.
