### ISSUE TITLE
DeFiChain Upgrade v3.3 [Feb 2023]

### ISSUE THREAD

**Issue by kynkong91** [DeFiCh/ain#1688]
#### Features / enhancements in this upgrade:
- [DFIP-2211-D: DUSDLOCK pools to lockup DUSD](https://github.com/DeFiCh/dfips/issues/236)
- Masternode rewards address format change

#### When is this upgrade scheduled:
- This upgrade is scheduled for Feb 2023

**Comment by prasannavl** [comment]
Note: De-prioritized in favour of metachain integration.
