### ISSUE TITLE
Registering DFI as coin type at SLIP-0044

### ISSUE THREAD

**Issue by maaze19** [DeFiCh/ain#169]
As preperation for further wallets which will be built with the definition of BIP44, I would like to ask for registering an index for DFI at SLIP-0044:
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

My ideas would be:
 - index 1129, hexa 0x80000469 (D=4,F=6,I=9)
 - index 4474441, hexa 0x80444649 (DFI in ASCII)

**Comment by uzyn** [comment]
I like this.

**Comment by ShengguangXiao** [comment]
0x469 = 1129,
0x444649 = 4474441, how does index 71592265 come out? 71592265 = 0x4446949

**Comment by maaze19** [comment]
> 0x469 = 1129,
> 0x444649 = 4474441, how does index 71592265 come out? 71592265 = 0x4446949

Thank you, I have edited my initial post.

**Comment by uzyn** [comment]
Thanks for your suggestion @maaze19 Proposal has been made to SLIP-44 and included.
