### ISSUE TITLE
Not possible to exchange BTC to DFI with DEX

### ISSUE THREAD

**Issue by Darkman-Q-Tester** [DeFiCh/ain#172]
OS Version: Windows 10  (20H2, Build 19042.746)
Wallet App Version: 2.1.10

Issue:
Not possible to exchange BTC to DFI with DEX.
Entered available amount of BTC but system shows error "Something went wrong", see attched picture.
Next button not available.
Unclear error message is displayed.
Funds are available and address is valid (same address was used to receive DFI and BTC from Cake).

Expected behavior :
It should be possible to swap BTC to DFI without error.

Proposal:
- In case of error please display a readable message which makes it clear what the root cause of the error is, a unique error Code which is explained in detail in the Help Menu or in a FAQ section. Also user should get to know what he needs to do now.
- Please check in the code for which root cause the error code "Something went wrong" is displayed and add a precise information what is wrong and what to do now.
- If possible display the amount of target coins the user will get as soon the first field is left.
- The DeFi App "Logs" menu should lead to specific Log files which are helpful for the developer to fix issues. I could not identify which file would be helpful in this case.

Steps to Reproduce:
After automatic update to 2.1.10 restart DeFi App.
Initial Version 2.1.9. was from Defichain webpage.
Go to DEX section.
Enter amount of BTC (in this case 50%) and select DFI as target coin.
→ Error is displayed
If I go back to Wallets and try again later the same use case I get the same result again.

Comment:
How to swap now?
Please let me know if I can support you.
I have very fast optical internet line and high end fast PC (32GB/Samsung Evo Pro M2).

![grafik](https://user-images.githubusercontent.com/77509687/104773091-c94cab80-5774-11eb-9258-591dc9f837c6.png)

**Comment by DanielZirkel** [comment]
Hi @izzycsy 
Can you move that issue to the app, please?
This is the wrong place, I think.

**Comment by Darkman-Q-Tester** [comment]
Will retest and reopen in the correct section.
