### ISSUE TITLE
Not possible to add BTC/DFI to Liquidity Mining

### ISSUE THREAD

**Issue by Darkman-Q-Tester** [DeFiCh/ain#173]
OS Version: Windows 10  (1909, Build 18363.1316)
Wallet App Version: 2.1.6

Issue:
Not possible to add BTC/DFI to Liquidity Mining.
Error message is displayed (Code 16). See attached picture.

Expected behavior :
It should be possible to add BTC/DFI to Liquidity Mining without error.

Proposal:
- In case of error please display a readable message which makes it clear what the root cause of the error is. Use an unique error Code which is explained in detail in the Help Menu or in a FAQ section, add a link to this in the error message. Also explain what the user should do now.
- The DeFi App "Logs" menu should lead to specific Log files (or a function witch creates a DebugInfo.zip which can be uploaded here) to support the developer.

Steps to Reproduce:
Go to Liquidity section.
Select BTC-DFI
Click on Add more
Click on "MAX" next to DFI
Click on Next
Click Supply
→ Error is displayed (code 16)

Comment:
Looks like there is probably a mismatch between available coins and tokens. The point is the end user can not know what the issue is here and what to to next. The system should fix this in the background.

Please let me know if I can support you.

Attachment:
![grafik](https://user-images.githubusercontent.com/77509687/104808182-c38eae80-57e4-11eb-8bc9-e592102f9099.png)

**Comment by DanielZirkel** [comment]
Hi @izzycsy 
Can you move that issue to the app, please?
This is the wrong place, I think.

**Comment by Darkman-Q-Tester** [comment]
Will retest and reopen in the correct section.
