### ISSUE TITLE
node crash on getcustomtx of mempool tx, likely createVoc

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#1739]
#### What happened:

all of my nodes monitoring the mempool crashed simultaneously (being on different servers, so no machine topic). last entry in the log is the updateTip to block 2655146. According to the log of the bot, it crashed on the getcustomtx call. Unfortunately I don't know which tx it was, but the only "suspicious" tx in the following block is a createVOC  : c5e4d2d681fa5c40f445854979b54a8368c41cb86df58ef915f6df1454ef18d2

since its in the block now, getcustomtx works fine. So its not reproducable here, but since it happened on all nodes that did the getcustomtx I think its worth investigating.

#### What are your environment parameters:
happened both on a windows machine and ubuntu. all with node 3.2.3

**Comment by phigo90** [comment]
My nodes had the same problem at the same block with getcustomtx. I am running 3.2.1 on a Debian system. I don't know if it helps, but the error message was 'Speicherabzug erstellt'. I can provide the debug.log file, if it helps
