### ISSUE TITLE
Warning message when creating first address

### ISSUE THREAD

**Issue by Darkman-Q-Tester** [DeFiCh/ain#175]
OS Version: Windows 10  (20H2, Build 19042.746)
Wallet App Version: 2.1.6

Issue:
After creating first DFI address a warning is displayed below the address.
(Warning: Not saved by seed phrase)
Same for created second address.
Blockchain is in sync.

Expected behavior :
It should be possible to create a valid address without warning message.

Proposal:
- In case of this error/warning please display a readable message which makes it clear what the root cause of the error is. Use an unique error Code which is explained in detail in the Help Menu or in a FAQ section, add a link to it on this page. Also explain what the user should do or should not do. Explain if the address anyway usable.
- The DeFi App "Logs" menu should lead to specific Log files (or a function witch creates a DebugInfo.zip which can be uploaded here) to support the developer.

Steps to Reproduce:
- After first installation of the DeFi App,
- Create new Wallet, save the seed,
- Create first DFI address
→ Address will be displayed with (Warning: Not saved by seed phrase)
If warning is displayed try to create a second address

What to do now?
Can I still use this address to receive DFI/BTC/ETH from Cake?

Comment:
This issue was found on two Windows 10 machines with Version 2.1.6, 2.1.9 and with 2.1.10.

Please let me know if I can support you.

Attachment:
![grafik](https://user-images.githubusercontent.com/77509687/104816166-914b7400-5819-11eb-87c9-6ff75a025b25.png)

**Comment by DanielZirkel** [comment]
Hi @izzycsy 
Can you move that issue to the app, please?
This is the wrong place, I think.

**Comment by Darkman-Q-Tester** [comment]
Will retest and reopen in the correct section.
