### ISSUE TITLE
Error: recipient () does not refer to any valid address

### ISSUE THREAD

**Issue by Darkman-Q-Tester** [DeFiCh/ain#176]
OS Version: Windows 10 (20H2, Build 19042.746)
Wallet App Version: 2.1.10

Issue:
Not possible to add Liquidity for BTC-DFI even if some coins are available.
Error message displayed: "recipient () does not refer to any valid address"

I guess this is related to this bug: https://github.com/DeFiCh/ain/issues/172

Expected behavior :
It should be possible to add BTC-DFI to Liquidity Mining without error.
If address is somehow not valid even if receivement of coins was possible then the App should come with advice what to do. 

Proposal:
- In case of this error please display a readable message which makes it clear what the root cause of the error is. Use an unique error Code which is explained in detail in the Help Menu or in a FAQ section, add a link to it on this page. Also explain what the user should do now.
- The DeFi App "Logs" menu should lead to specific Log files (or a function witch creates a DebugInfo.zip which can be uploaded here) to support the developer.

Steps to Reproduce:
- After first installation of the DeFi App,
- Create a address
- Receive some DFI and BTC from Cake
- Go to Liquidity Section
- Try to add Liquidity to BTC-DFI, Select BTC and DFI
- Select "MAX" next to DFI

What to do now?

Comment:
Error is displayed even after restart. This Wallet Address is not usable.

Please let me know if I can support you.

Attachment:
![grafik](https://user-images.githubusercontent.com/77509687/104817199-ee4a2880-581f-11eb-8a9d-23714eaae51b.png)

Address looks correct:
![grafik](https://user-images.githubusercontent.com/77509687/104817215-0de15100-5820-11eb-8131-bbdb60c255b8.png)

**Comment by DanielZirkel** [comment]
Hi @izzycsy 
Can you move that issue to the app, please?
This is the wrong place, I think.

**Comment by Darkman-Q-Tester** [comment]
Will retest and reopen in the correct section.
