### ISSUE TITLE
OCG Voting rewards are not spendable

### ISSUE THREAD

**Issue by bernd-mack** [DeFiCh/ain#1763]
#### What happened:
voted with onchain governance and got reward on my address but wallet does not show tokenbalance and therefore the DFI are not spendable

#### What you expected to happen:
rewards from onchainvoting are listed in gettokenbalances and are spendable

#### How to reproduce it (as minimally and precisely as possible):
vote for a DFIP/CFP and get a reward. Reward is shown on defiscan but not on local wallet

#### What are your environment parameters:
defichain desktop wallet with latest noderelease

#### Anything else we need to know?:
restore with snapshot did not help and another telegram with multiple masternodes told that only one reward is shown in balance.

**Comment by shohamc1** [comment]
Hey, thanks for opening this. It seems that the issue here is the token not showing up on `gettokenbalances`, which should be fixed by the linked PR. 

By my testing, rewards are spendable and can be viewed using `getaccount` in the meanwhile.

**Comment by bernd-mack** [comment]
Thanks and sorry, the wording was not clear (German->English gets lost or does not arrive exactly with me from time to time a little bit of information) :(
Spend if you build the transactions themselves or use account2utxos were not meant, only the gettokenbalances and thereby also the desktop wallet which presumably falls back on it and there with a 0 not automatically converts the tokens if you want to send something.
=> They are spendable, just not automatically when using desktop wallet
