### ISSUE TITLE
Error "Unable to start blockchain"

### ISSUE THREAD

**Issue by Darkman-Q-Tester** [DeFiCh/ain#177]
OS Version: Windows 10 (20H2, Build 19042.746)
Wallet App Version: 2.1.10

Issue:
When launching the DeFi App and waiting for 5 minutes while spinner is turning
then error "Unable to start blockchain" is displayed.
This happens regularly, with all App versions.

What is the root cause of this issue?
I guess the blockchain can not be "down".
What should the user do now?

Expected behavior:
It should be possible to start the DeFi App without error.

Proposal:
- In case of error please display a readable message which makes it clear what the root cause of the error is. Use an unique error Code which is explained in detail in the Help Menu or in a FAQ section, add a link to it on this App page. Also explain what the user should do now.
- The DeFi App "Logs" menu should lead to specific Log files (or a function witch creates a DebugInfo.zip which can be uploaded here) to support the developer.

Steps to Reproduce:
Launch the wallet app

Comment:
I have a fast internet line and high-end PC.

Please let me know if I can support you.

Attachment:
![grafik](https://user-images.githubusercontent.com/77509687/104843319-476e9680-58ca-11eb-907c-a0ad79adc75b.png)
![grafik](https://user-images.githubusercontent.com/77509687/104843343-63723800-58ca-11eb-8cae-40b9c1167d4e.png)
![grafik](https://user-images.githubusercontent.com/77509687/104843353-6f5dfa00-58ca-11eb-888f-3882f8314c8e.png)

**Comment by DanielZirkel** [comment]
Hi @izzycsy 
Can you move that issue to the app, please?
This is the wrong place, I think.

**Comment by Darkman-Q-Tester** [comment]
Will retest and reopen in the correct section.
