### ISSUE TITLE
Allow a full node to generate blocks in regtest

### ISSUE THREAD

**Issue by dbilousov** [DeFiCh/ain#1771]
#### What would you like to be added:
Remove the check for the regtest that prohibits generating new blocks within the regtest.

#### Why is this needed:
I am struggling to understand why my Node has to be a Masternode operator to generate blocks if I am within the regtest net. 
`defi-cli -regtest generatetoaddress 100 $(defi-cli -regtest getnewaddress)`

```
error code: -5
error message:
Error: I am not masternode operator
```
It seems this behaviour differs from how it works for the bitcoin blockchain on regtest. 
My question is whether this behaviour for the DefiChain is intended? In that case I would need to turn on the Masternode operator mode to generate the blocks in the regtest

**Comment by shohamc1** [comment]
Hey there, using regtest requires some setup. 

- You need to import the private keys of the masternode operators into your wallet. Private keys and their addresses can be found [here](https://github.com/DeFiCh/ain/blob/456eaac743b3b1f92366188d4e9453dfbd2821ed/test/functional/test_framework/test_node.py#L131).
- Run `defid -regtest=1` and then `importprivkey` any of the operator private keys. (you only need to do this once)
- Shutdown `defid` and rerun it with `-masternode_operator=<address>`, where `<address>` is the corresponding operator address that was imported earlier. 

After this you should be able to generate blocks using `generatetoaddress`, or you can use `-gen=1` to automatically generate blocks.

**Comment by dbilousov** [comment]
Hi @shohamc1 

thank you, much appreciated!

Kind regards
Dennis
