### ISSUE TITLE
3.2.5 - gettokenbalances - false values

### ISSUE THREAD

**Issue by luckythai** [DeFiCh/ain#1778]
#### What happened:

When using 3.2.5 as a node, gettokenbalances brings false values.

When using 3.2.5 in the desktopapp, the values are not correct and the use of the consoles is not possible.

When using 3.2.4 again as a node, the values vote again. Also when using 3.2.4 in the desktopapp, the values are correct again and the console works without any problems.

As soon as the 3.2.5 is used, the problems occur again. At 3.2.4 the problems disappear again.
Tested on 2 different hardware on Ubuntu and 3 different databases.
The same when using the new snapshot.

**Comment by shohamc1** [comment]
Did you `rescan` after updating to 3.2.5?

**Comment by luckythai** [comment]
No, 
Since I had 3.2.4, only an drop in-upgrade was made and also a new snapshot.
It also works again when using the same database and putting back to 3.2.4.

Is it certain that it works after Rescan at 3.2.5 again. When using the desk.App, the node is just as faulty and also using the console there is not possible there. It does not provide any results on the console and the result remains empty.
The use of the console normally has nothing to do with rescan.

Upgrade Notes
For >= 3.2.0 and <= 3.2.3, reindex is recommended, but optional and can be drop in-upgrade.

**Comment by shohamc1** [comment]
A rescan is always required when using a snapshot.

From the 3.2.5 release notes: `For nodes that are being restored from recent snapshot, as with all updates before: -rescan for the wallet txs `

Your balances should show up once the rescan is done.

**Comment by luckythai** [comment]
He does a rescan of the addresses by using a snapshot. I wrote when used 3.2.4 back everything is normal. The answer is always not correct here and a real value in getting balaces is not normal either. A rescan was only necessary for the correct display of all transactions.
But not for the correct display of the tokens.

But ok I'll make a rescan and report afterwards.

**Comment by Bushstar** [comment]
If you are happy to share can you post the output of gettokenbalances on 3.2.4 and 3.2.5?
