### ISSUE TITLE
Error: "There was an error sending the amount"

### ISSUE THREAD

**Issue by Darkman-Q-Tester** [DeFiCh/ain#178]
OS Version: Windows 10 (20H2, Build 19042.746)
Wallet App Version: 2.1.5

Issue:
Could not send DFI from DeFi App to other DeFi App DFI Address. Error is displyed "There was an error sending the amount". See attached screenshot.
What is the root cause of this issue?
What to do now?

Expected behavior :
It should be possible send DFI from DeFi App to other DeFi App/DFI address without error.

Proposal:
- In case of this error please display a readable message which makes it clear what the root cause of the error is. Use an unique error Code which is explained in detail in the Help Menu or in a FAQ section, add a link to it on this App page. Also explain what the user should do now.
- The DeFi App "Logs" menu should lead to specific Log files (or a function witch creates a DebugInfo.zip which can be uploaded here) to support the developer.

Steps to Reproduce:
Launch the wallet app
Select the DFI Wallet
Click on "Send"
Capture an amount that is 10% less than available amount of DFI.
Capture target DFI Address
Click "Next" --> Error will be displayed

Comment:
Looks like there is probably a mismatch between available coins and tokens. The point is the end user can not know what the issue is here and what to do next. The system should fix this in the background.

I have a fast internet line and high-end PC.

Please let me know if I can support you.

Attachment:
![grafik](https://user-images.githubusercontent.com/77509687/104850756-443ad100-58f1-11eb-8569-11395d489008.png)
![grafik](https://user-images.githubusercontent.com/77509687/104850766-4c930c00-58f1-11eb-9280-fd871ff72e28.png)

**Comment by DanielZirkel** [comment]
Hi @izzycsy 
Can you move that issue to the app, please?
This is the wrong place, I think.

**Comment by Darkman-Q-Tester** [comment]
Will retest and reopen in the correct section.
