### ISSUE TITLE
Fresh sync with 3.2.6 and 3.2.7 stuck

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/ain#1824]
## Summary

- Delete all Blockchainfolders and sync from Block 0. With version 3.2.6 the Sync stopped:
`2023-03-01T00:00:49Z ERROR: ConnectBlock: Consensus::CheckTxInputs: 53d98a9aa82da514a77a9b7b3ff4b7fab08fa91dce12775e8a7faaf2c1ca1fa5, bad-txns-inputs-missingorspent, CheckTxInputs: inputs missing/spent (code 16)
2023-03-01T00:00:49Z InvalidChainFound: invalid block=af8329bf76978bbe18cdbc0f369850b8603481371d41b83ece73f428c874e14a  height=2295170  log2_work=86.596306  date=2022-10-05T07:19:54Z`

With reconsiderblock af8329bf76978bbe18cdbc0f369850b8603481371d41b83ece73f428c874e14a the sync goes on.

- With 3.2.7 again delete all Blockchainfolders and sync from scratch. Same problem, another TX/Block:
`2023-03-15T01:10:44Z ERROR: ConnectBlock: Consensus::CheckTxInputs: c8169c8dc671aa348c466aea4231a51540ebda7de22cf0cb6b19feb867a73f30, bad-txns-inputs-missingorspent, CheckTxInputs: inputs missing/spent (code 16)
2023-03-15T01:10:44Z InvalidChainFound: invalid block=ba0bbd3d9bcabb3af66402fe7b4555b855708246f87bdfd53280e80f091be4c5  height=2652198  log2_work=87.093355  date=2023-02-06T18:26:23Z
2023-03-15T01:10:44Z InvalidChainFound:  current best=24c07c57ca0eb0d238deabef3df266bd9ec5bced77f6434fb94047bf4fc2fd9e  height=2652197  log2_work=87.093354  date=2023-02-06T18:26:12Z`

I  have not used reconsiderblock in case further analysis is needed.

## Steps to Reproduce

Fresh sync.

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: 3.2.6 and 3.2.7
- Block height on bug if applicable:
-- 3.2.6: Block #2295170
-- 3.2.7: Block #2652198
- TX or TX type on bug if applicable: 
-- 3.2.6: 53d98a9aa82da514a77a9b7b3ff4b7fab08fa91dce12775e8a7faaf2c1ca1fa5
-- 3.2.7: c8169c8dc671aa348c466aea4231a51540ebda7de22cf0cb6b19feb867a73f30
- OS with version: Ubuntu 20.04
- Any other relevant environment info:  No

**Comment by prasannavl** [comment]
Thanks for the report and the specific TX info @Stonygan - we have a few fresh sync tests, all of them at tip (all on Ubuntu 18.04 however, though it's unlikely to make a difference). Could you help with the following to investigate this further?

1. Are you able to recreate this consistently? 
1. During the run, are you able to add any RPCs that were used, if any? (listaccounts, gettokenbalances, etc)
1. Was this node ever restarted or was it a single run?

**Comment by Stonygan** [comment]
> Thanks for the report and the specific TX info @Stonygan - we have a few fresh sync tests, all of them at tip (all on Ubuntu 18.04 however, though it's unlikely to make a difference). Could you help with the following to investigate this further?
> 
> 1. Are you able to recreate this consistently?
> 2. During the run, are you able to add any RPCs that were used, if any? (listaccounts, gettokenbalances, etc)
> 3. Was this node ever restarted or was it a single run?

1. Try it only one time with 3.2.6 and one time with 3.2.7
2. Yes, thats possible. This commands run every 5 minutes during sync: https://snapshot-de.mydefichain.com/api/
3. Single Run, restart after sync stops, but same behaviour.

**Comment by Stonygan** [comment]
> Additionally if you still have this node (super helpful if you do assuming from `I have not used reconsiderblock in case further analysis is needed.`):
> 
> * Could you do `logaccountbalances` and `logstoredinterests` at that point and share the output files?

https://snapshot-de.mydefichain.com/logaccountbalances.txt
https://snapshot-de.mydefichain.com/logstoredinterests.txt

**Comment by prasannavl** [comment]
Thank you for the quick info, we'll investigate and try to see if we can recreate it. Just one more piece of info:

> https://snapshot-de.mydefichain.com/logaccountbalances.txt
https://snapshot-de.mydefichain.com/logstoredinterests.txt 

Could you share the blockheights and the version of this ouput?

**Comment by Stonygan** [comment]
```
~/.defi/defi-cli getblockcount
2652197
```
```
~/.defi/defi-cli getnetworkinfo
{
  "version": 3020700,
  "subversion": "/DeFiChain:3.2.7/",
  "protocolversion": 70036,
  "localservices": "0000000000000409",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 34,
```

**Comment by Stonygan** [comment]
Addition, following switches are set in defi.conf:

```
txindex=1
acindex=1
vaultindex=1
dexstats=1
```

**Comment by prasannavl** [comment]
Thanks @Stonygan -- we tried to re-create this repeatedly, but not been able to reproduce it. Would be curious to know if you have been able to, or perhaps if the cleanup of the delete was incomplete / some file handles being kept open by a lingering process or so that corrupted the DB.
