### ISSUE TITLE
Light wallet: instead of a payback loan the walled swapped the tokens

### ISSUE THREAD

**Issue by DEFICHAINFAN** [DeFiCh/ain#1830]
## Summary
I was trying to pay back a dBITI loan after removing liquidity:
https://defiscan.live/transactions/3201c0ed309198e210088d2f3cb196a3ab59bed466cfe659579d07f2410aa0d2

The loan was of 25 dBITI the amount I removed 23, after I clicked on pay,  the wallet only paid 5 dBITI and 20 still remain as a loan.
Interesting enough there is no record for the payback of the 5 dBITI among the transactions.

And instead of paying 23 out of 25, the wallet swapped the 23 tokens into dUSD:

- https://defiscan.live/transactions/f47b1fe6688de743f9da2081479b3a8f6be7ac12390340bf7038fde7266f2cb4

## Steps to Reproduce

[Please use step-by bullet points to help the team reproduce the bug]

- Removed liquidity
- Open the vault and clicked on pay dBITI
- Selected 100%
- Clicked on "Continue"
- Confirmed payback

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: 
- Block height on bug if applicable: 
- TX or TX type on bug if applicable:  https://defiscan.live/transactions/f47b1fe6688de743f9da2081479b3a8f6be7ac12390340bf7038fde7266f2cb4
- OS with version: iOS 16.3.1
- Any other relevant environment info:

**Comment by dcorral** [comment]
Hello @DEFICHAINFAN ,

Please open the issue in the [LW repository](https://github.com/BirthdayResearch/defichain-wallet/issues/new/choose)
