### ISSUE TITLE
Transaction didnt go through and remains as pending.

### ISSUE THREAD

**Issue by DEFICHAINFAN** [DeFiCh/ain#1840]
## Summary
The following swap transaction remains as pending. 

- 

## Steps to Reproduce

[Please use step-by bullet points to help the team reproduce the bug]

- Went to Swap
- Selected the coins I wanted to swap dUSD
- Selected the dToken I wanted to buy FB.
- Confirmed amounts
- Confirmed with PIN
- 

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: 
- Block height on bug if applicable: 
- TX or TX type on bug if applicable:  12687531917e82f026b1e7f6865098c2cd0ce902fc492cd0dd696eeb7e8dce2e
- OS with version: IOS 16.3.1
- Any other relevant environment info:  I am using the oficial ocen endpoint.

**Comment by dcorral** [comment]
Hello @DEFICHAINFAN ,

- Please open the issue in the [LW repository](https://github.com/BirthdayResearch/defichain-wallet/issues/new/choose)
- The TX mentioned corresponds to a `WithdrawFromVault` transaction which is already in block 2778975. Please double check the pending TX id.

**Comment by DEFICHAINFAN** [comment]
Thank you I will open a issue there, the transaction is the one I got yesterday, indeed which is even more strange is that it appears as a withdraw now, when it was a swap.

**Comment by dcorral** [comment]
Discussion moved to https://github.com/BirthdayResearch/defichain-wallet/issues/3943
