### ISSUE TITLE
The defichain image used in a Dockerfile doesn't exist any more

### ISSUE THREAD

**Issue by dbilousov** [DeFiCh/ain#1845]
Hi guys,

the docker image defichain-x86_64-pc-linux-gnu used in the Dockerfile https://github.com/DeFiCh/ain/blob/master/contrib/dockerfiles/dockerhub/x86_64-pc-linux-gnu.dockerfile doesn't exist any more:
https://hub.docker.com/_/defichain-x86_64-pc-linux-gnu/

Kind regards
Dennis

**Comment by prasannavl** [comment]
- That file required the `defichain-x86_64-pc-linux-gnu` builder to be built first which created the tag `defichain-x86_64-pc-linux-gnu`. 
- Please see `./make.sh` (`docker-build` flow) or the CIs worflow for more info on how was built. 

That being said there was a recent change in the build process that has simplified this much further and the direct dockerfile can now be built independently as well.
