### ISSUE TITLE
ETH-JSON RPC Spec Implementation

### ISSUE THREAD

**Issue by canonbrother** [DeFiCh/ain#1852]
## Summary

- Issue dedicated to track and document ETH-JSON RPC in ain.
  - Reference:
    - https://ethereum.org/en/developers/docs/apis/json-rpc/
    - https://ethereum.github.io/execution-apis/api-documentation/

#### Status 
- The major RPCs for MetaMask usage and contract deployments are in place.
- Priority based on eco-system usage. 
- All RPCs that are a part of ETH-JSON spec are in scope to be implemented. 
- What's not in scope: Additional geth, and debug RPCs that aren't a part of the spec.

### `block`

- eth_getBlockByHash 
    - [x] impl @shohamc1 #1864
    - [x] unit test
- eth_getBlockByNumber
    - basic
        - [x] impl @shohamc1 #1882
        - [ ] unit test
    - full
        - [ ] impl
        - [ ] unit test
- eth_getBlockTransactionCountByHash
    - [x] impl
    - [x] unit test
- eth_getBlockTransactionCountByNumber
    - [x] impl @dcorral #1905
    - [ ] unit test
- ~~eth_getUncleCountByBlockHash~~
- ~~eth_getUncleCountByBlockNumber~~

### `client`
- eth_chainId
    - [x] impl @shohamc1 #1891
    - [x] unit test
- ~~eth_syncing~~
- ~~eth_coinbase~~
- eth_accounts
    - [x] impl @DocteurPing #1916
    - [x] unit test 
- eth_blockNumber 
    - [x] impl @shohamc1 #1882
    - [ ] unit test 
- net_version 
    - [x] impl @shohamc1 #1891
    - [x] unit test    

### `execute`

- eth_call
    - [x] impl
    - [ ] unit test
- eth_estimateGas
    - basic
        - [x] impl @Mixa84 #1940
        - [x] unit test
    - full
        - [ ] impl
        - [ ] unit test
- ~~[ ] eth_createAccessList~~

### `fee market`
- eth_gasPrice
    - basic
        - [x] impl @Mixa84 #1940
        - [x] unit test
    - full
        - [ ] impl
        - [ ] unit test
- eth_maxPriorityFeePerGas
    - [ ] impl
    - [ ] unit test
- eth_feeHistory
    - [ ] impl
    - [ ] unit test

### `filter`

- [ ] eth_newFilter
- [ ] eth_newBlockFilter
- [ ] eth_newPendingTransactionFilter
- [ ] eth_uninstallFilter
- [ ] eth_getFilterChanges
- [ ] eth_getFilterLogs
- [ ] eth_getLogs

### `mining`

- eth_mining
    - [x] impl @shohamc1 #1892
    - [ ] unit test 
- eth_hashrate
    - basic
        - [x] impl @DocteurPing #1916
        - [x] unit test 
    - full
        - [x] impl
        - [x] unit test
- [x] eth_getWork 
    - basic
        - [x] impl @Bushstar #1943
        - [ ] unit test 
    - full
        - [ ] impl
        - [ ] unit test
- [x] eth_submitWork
    - basic
        - [x] impl @Bushstar #1943
        - [ ] unit test 
    - full
        - [ ] impl
        - [ ] unit test
- [x] eth_submitHashrate
    - basic
        - [x] impl @Bushstar #1943
        - [ ] unit test 
    - full
        - [ ] impl
        - [ ] unit test

### `sign`

- eth_sign @canonbrother
    - [ ] impl
    - [ ] unit test
- eth_signTransaction @canonbrother
    - [x] impl #2110
    - [x] unit test #2110

### `state`

- eth_getBalance
    - basic
        - [x] impl
        - [x] unit test 
    - full
        - [ ] impl
        - [ ] unit test
- eth_getStorageAt
    - basic
        - [x] impl @shohamc1 #1911
        - [ ] unit test 
    - full
        - [ ] impl
        - [ ] unit test
- eth_getTransactionCount
    - [x] impl @shohamc1 #1917
    - [ ] unit test 
- eth_getCode
    - basic
        - [x] impl @shohamc1 #1911
        - [x] unit test 
    - full
        - [ ] impl
        - [ ] unit test
- eth_getProof
    - basic
        - [ ] impl
        - [ ] unit test 
    - full
        - [ ] impl
        - [ ] unit test

### `submit`

- eth_sendTransaction 
    - [x] impl @canonbrother #1984 
    - [x] unit test @canonbrother #1984 
- eth_sendRawTransaction 
    - [x] impl @shohamc1 #1913
    - [x] unit test @canonbrother #1984 

### `transaction`

- eth_getTransactionByHash 
    - [x] impl @Jouzo #1908
    - [x] unit test
- eth_getTransactionByBlockHashAndIndex
    - [x] impl @Jouzo #1908
    - [x] unit test
- eth_getTransactionByBlockNumberAndIndex
    - [x] impl @Jouzo #1908
    - [x] unit test
- eth_getTransactionReceipt
    - basic
        - [x] impl @shohamc1 #1927
        - [ ] unit test
    - full
        - [ ] impl
        - [ ] unit test
    
### `misc`
- eth_pendingTransactions
    - [x] impl @Bushstar #1933
    - [x] unit test

**Comment by fullstackninja864** [comment]
Can we please add below methods which will get consumed in metascan explorer
1. `eth_getBlockByNumber` : with `latest` as a parameter, which will gives us information related to the most recent block related data
2. `txpool_content`: to get the pending and queued transactions

**Comment by DocteurPing** [comment]
for the test of the RPC i haven't had the time to check everything but here are the few difference i noticed yet. All the other RPC has been tested on a local nodes and seems to behave as expected. For the tests i pull the last version of feature/evm and run alll the differents request from curl. they are returning the correct output when all the parameters are correct and they are returning an error if the parameters are wrong/missing.
state_root not working (not tested yet)
eth_gasprice
eth_estimateGas
eth_sendtransaction (not implemented)
eth_getUncleCountByBlockNumber (not implemented)
eth_syncing (not implemented)
eth_coinbase(not implemented)
eth_createaccesslist (not implemented)
eth_maxPriorityFeePerGas(not implemented)
eth_feeHistory(not implemented)
eth_sign(not implemented)
eth_signtransaction(not implemented)
eth_getproof(not implemented)
All the filter function (not implemented)
eth_getStorageAt (to check)
eth_sendRawTransaction (to check)
eth_getTransactionByHash (to check)
