### ISSUE TITLE
MAX PRICE NOT BEING TRIGGERED

### ISSUE THREAD

**Issue by Dieth22** [DeFiCh/ain#1910]
<!-- 

## Summary
I submitted a transaction VIA python API for eth and the max price was set to 2030 but the buy price was 2005 so the max price feature is not working and people are ending up paying more than they set their max price for.

## Steps to Reproduce

do a sell order via python api.

[Please use step-by bullet points to help the team reproduce the bug]

- 
- 

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: 3.2.1
- Block height on bug if applicable:  [2841827](https://defiscan.live/blocks/2841827)
- TX or TX type on bug if applicable:   https://defiscan.live/transactions/d18d02744a6f980fbc89d3b86aa7af41a245e9df877df613589815b25e94aadb
- OS with version:  Mac catalina 10.15.7
- Any other relevant environment info:

**Comment by prasannavl** [comment]
Please note: This is a technical issue tracker. Issues without helpful explanations, examples or unclear intent where there's no clear actions will be closed.

**Comment by prasannavl** [comment]
Please follow the template given: 

```
<!-- 
- This issue tracker is only for technical issues related to the DeFi Blockchain.
- Please use this template while reporting a bug and provide as much info as possible.
- If the matter is security related, please disclose it privately via security@defichain.com
- Please use bullet points as much as possible.
- If you'd like to add details notes, split the summary with a "Details" section.  
-->

## Summary

- 

## Steps to Reproduce

[Please use step-by bullet points to help the team reproduce the bug]

- 
- 


## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: 
- Block height on bug if applicable: 
- TX or TX type on bug if applicable:  
- OS with version: 
- Any other relevant environment info:  
```

I'm closing this since there's nothing actionable here. Please feel free to re-open with the proper explanations or create a new one. Thanks.

**Comment by Dieth22** [comment]
## Summary

- Max price is not working properly when trying to sell ETH to USDT on
the DEX via a python bot.

- Max price was set to 2,023.10063318 when selling eth to USDT and the
end price I ended up getting was 2000.77/eth

## Steps to Reproduce

[Please use step-by bullet points to help the team reproduce the bug]

- Do a composite swap on the DEX via python API
- Swap DETH to DUSDT


## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: 3.2.1
- Block height on bug if applicable:
2841827
- TX or TX type on bug if applicable:
d18d02744a6f980fbc89d3b86aa7af41a245e9df877df613589815b25e94aadb
- OS with version: Catalina 10.15.7
- Any other relevant environment info:  I have included images to show
you that max price did not stop TX
