### ISSUE TITLE
txn-mempool-conflict (code 18)

### ISSUE THREAD

**Issue by Alex080988** [DeFiCh/ain#193]
Hi,
i have an issue. Maybe you can help me out.
I want to put Liquidity in the Liquidity Mining. In
Both in BTC-DFI and ETH-DFI I get the same error.
It is showing up:

> txn-mempool-conflict (code 18)

What can I do?

**Comment by BenThrottle85** [comment]
This issue was already closed. 
https://github.com/DeFiCh/app/issues/241

**Comment by INQB1** [comment]
But issue #241 was closed with no explanation what it was. I new v.2.1.9 was just released. 
I have the same issue now. So the error is back again. 

I there a list of all the Defichain errors codes somewhere for look up?
