### ISSUE TITLE
UI user experience

### ISSUE THREAD

**Issue by skironDotNet** [DeFiCh/ain#1950]
there is nothing more fun than scary away the user with an impression, "you must start over" after typo, so to fix that, better label would be 
"Try Again" than "Close"

This makes me vote again, just provide a text area to paste the whole 24 words https://github.com/BirthdayResearch/defichain-app/issues/1258#

![image](https://user-images.githubusercontent.com/2981715/235567368-50612736-082c-4bcb-800b-6e86893a89b7.png)

**Comment by prasannavl** [comment]
Hi. As you've mentioned, you've already found the right place to add feedback. Closing this as it's not actionable here.
