### ISSUE TITLE
EVM Bug Tracker 

### ISSUE THREAD

**Issue by prasannavl** [DeFiCh/ain#1991]
## Summary

- This is a tracker to gather, collect and resolve known issues related to EVM before hitting testnet
- For early testers: Please feel free to add it as comment to this issue on issues related to EVM, metamask, or EVM tooling, and we'll add it to the thread once we gather enough data. 

### What Works

-  :heavy_check_mark: `TransferDomain` to move funds across domains.
  - :heavy_check_mark: EVM: Transparently represented on EVM through the `TransferDomain` contract.
- :heavy_check_mark: Seamless connection to metamask
- :heavy_check_mark: Metamask basics
- :heavy_check_mark: Execution of EVM TXs
- :heavy_check_mark: Smart contract deployment and execution

### Known Issues

- ~~Miner fees impl is currently partial~~
  - ~~Temp. workaround: Irrelevent as it has no side-effects~~
- ~~Gas estimation fixes still pending~~
  - ~~Temp. workaround: Manually set fees for TX, if you encounter cases where this is an issue~~
- ~~Rollback impl still partial enough to enable a testing network.~~
  - ~~Temp. workaround: Pending.~~
- Impl pending:
  - `debug_traceTransaction`
  - pending transactions
  - Subscriptions

**Comment by Jouzo** [comment]
Missing `debug_traceTransaction` for Remix and metascan integration

**Comment by Meiswinkel1991** [comment]
I get the following error message when deploying a compiled smart contract: "Error: (Awaiting internal transactions for reason)".

This error only occurs when I want to execute a function call in the constructor. 
If I only change state variables in the constructor the deploy transaction runs fine.

If necessary, I could pass the byte codes for both scenarios.

**Comment by prasannavl** [comment]
Closing as completed.
