### ISSUE TITLE
defid 4.0.0.-beta1 not running with GLIBC 2.31

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/ain#2046]
## Summary

defid 4.0.0-beta1 not running with Debian GLIBC 2.31-13+deb11u6) 2.31

## Steps to Reproduce

~/.defi/defid

`.defi/defid: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.32 not found (required by .defi/defid)`
`.defi/defid: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.34 not found (required by .defi/defid)`
`.defi/defid: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.33 not found (required by .defi/defid)`

same with defi-cli.

Is it planned to compile defid the same as with previous versions or is this beta the current build status as it will be later?

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: defid 4.0.0-beta1
- Block height on bug if applicable: NA
- TX or TX type on bug if applicable:  NA
- OS with version: debian 11.7
- Any other relevant environment info:  
- Linux 5.10.0-23-amd64 x86_64

**Comment by prasannavl** [comment]
Quick glance: https://tracker.debian.org/pkg/glibc - old stable seems to be on: [2.28-10+deb10u1](https://packages.debian.org/source/oldstable/glibc). 

Ubuntu 20.04: https://launchpad.net/ubuntu/+source/glibc is on 2.31.

However, will still have to look at why your logs went as high up as GLIBC_2.33. We'll check it out - and lower our bases if possible. Ideally would like to support Debian 11. Although this has now moved to oldstable as of 2 days ago.
