### ISSUE TITLE
Limitation of transactions per block evm

### ISSUE THREAD

**Issue by Darkchicken1991** [DeFiCh/ain#2055]
Hello,
I tried to send 50 transactions at the same time on changi. But only a few transactions were recorded per block ( about 5 ). Thus it took several blocks ( 15 blocks ) until all transactions were processed. Is this a bug or is it intentional?

Last 50 Transaction of this address:
https://testnet-dmc.mydefichain.com:8444/address/0x29950466546472A62c1281a9Bc4069D2B2Bbfa81/transactions#address-tabs

**Comment by shohamc1** [comment]
This is a known limitation of the current implementation. We will likely improve the transaction ordering system later on down the line.
