### ISSUE TITLE
changi node crash `Block magic mismatch`

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#2106]
## Summary
during normal operation of beta 3 node, it suddenly crashed with error:
```
ERROR: ReadRawBlockFromDisk: Block magic mismatch for FlatFilePos(nFile=8, nPos=5245339): 0b110907 versus expected 0d111109
Assertion failed: (!"cannot load block from disk"), function ProcessGetBlockData, file net_processing.cpp, line 1510.
Abort trap: 6
```
crash happened at block 1718466 (but I think it is unrelated to the block), right after a new outbound peer got connected (but the new peer had an 500k blocks older chain)

after restart, it resynced all the way from 1695721.

after the resync it continued working normally.

## Steps to Reproduce

not reproducable yet, but I got reports from others that it happened there too. 

## Environment

- Node Version: 4.0.0 beta3
- OS with version: OSX

**Comment by Bushstar** [comment]
Were these nodes all clean syncs of changi or was a snapshot used and if a snapshot was used where did you get it from?

**Comment by kuegi** [comment]
Snapshots from testnet at block 1695720

**Comment by prasannavl** [comment]
Closing stale / outdated issues.
