### ISSUE TITLE
NFT mint transactions failing on DMC

### ISSUE THREAD

**Issue by dSEA-DFI** [DeFiCh/ain#2112]
## Summary
The dSEA smart contract got successfully deployed on DMC but we are unable to mint any NFT via this contract.
It doesn’t seem to be the low gas fee issue, since we have tried to mint several times with 10000GWEI and a 5M gas limit.
All transaction always fail..

The same smart contract has been deployed on goerli beforehand and worked perfectly fine, we unfortunately can’t make out what the issue seems to be.

## Environment

Smart contract ID: https://testnet-dmc.mydefichain.com:8444/address/0xA3F0b3275f73884664814cbd78c3CA39531F97aD
Failed TXID: https://testnet-dmc.mydefichain.com:8444/tx/0xc450ba7f8e623ba6217f801f9fac7fa77e9c453a9932ce9edadf407fd7e66492

SC code: 

https://testnet-dmc.mydefichain.com:8444/address/0xA3F0b3275f73884664814cbd78c3CA39531F97aD/contracts#address-tabs

**Comment by prasannavl** [comment]
Thanks for the report @dSEA-DFI. We'll look into the coming week.

**Comment by shohamc1** [comment]
Hi, could you please verify the contract on the explorer or alternatively provide the contract source code here?

**Comment by dSEA-DFI** [comment]
The code is now up on the explorer :)

https://testnet-dmc.mydefichain.com:8444/address/0xA3F0b3275f73884664814cbd78c3CA39531F97aD/contracts#address-tabs

**Comment by dSEA-DFI** [comment]
> Hi, could you please verify the contract on the explorer or alternatively provide the contract source code here?

The code is now up on the explorer :)

https://testnet-dmc.mydefichain.com:8444/address/0xA3F0b3275f73884664814cbd78c3CA39531F97aD/contracts#address-tabs

**Comment by shohamc1** [comment]
Hey, there seems to be an execution error on the transaction (hash: `0xc450ba7f8e623ba6217f801f9fac7fa77e9c453a9932ce9edadf407fd7e66492`). The revert message is `Invalid Payment currency`.

**Comment by dSEA-DFI** [comment]
Ok, thanks for the information, we updated the smart contract during the last days and got it to work now, minting seems to work fine :)
