### ISSUE TITLE
UTXO Remains at Zero Balance

### ISSUE THREAD

**Issue by shanedallas76** [DeFiCh/ain#2131]
## Summary
My DEFI Wallet desktop app remains at zero UTXO balance. So, I can't send DEFI to another wallet address.
- 

## Steps to Reproduce

[Please use step-by bullet points to help the team reproduce the bug]
1 - open DEFI desktop PC app (v. 3.2.9)
2 - Balances
3 - UTXO displays zero
4 - go to settings / wallet helper options /  "PRE-FUND TXNS" - this will hang infinitely
5 - go to UTXO Recharger (https://[utxo.mydefichain.com](https://utxo.mydefichain.com/) / I enter in each of my wallet addresses / click Recharge / status = "successful" / desktop app remains at zero balance
6  - access 2nd desktop PC to repeat steps 1-5 > same results

## Environment
wallet address 1 - dLf6JkoLNKgFwD945nozLh9rehFoQJB7yg
wallet address 2 - dSVfsEphrDaP4Z5e9sd4GB8KAtjpAFXDJ7

most recent block explorer for recharge for wallet address #2 - https://chainz.cryptoid.info/dfi/tx.dws?fed1fa8c6a7cfce68c82e8e346a5be602eb322c60f15902016b510fb7d2043d8.htm

[Please fill all of the following or NA if not applicable]

- Node Version: 3.2.9
- Block height on bug if applicable: 3060217 (or latest block height)
- TX or TX type on bug if applicable:  
- OS with version: Windows 11, version 22H2
- Any other relevant environment info:  This issue is approximately one month old. I have been able to transfer DEFI before then, mostly successfully. However the PRE-FUND TXNS tool usually hangs 60% of the time in the past. Now it hangs 100% of the time. 
![github_1](https://github.com/DeFiCh/ain/assets/39530738/74ee3cba-3693-4093-af20-8f74acca8eba)
[app_log.log](https://github.com/DeFiCh/ain/files/11896154/app_log.log)
[node_log.log](https://github.com/DeFiCh/ain/files/11896155/node_log.log)

**Comment by prasannavl** [comment]
Closing, invalid.
