### ISSUE TITLE
evm: `eth_call` should return revert messages

### ISSUE THREAD

**Issue by shohamc1** [DeFiCh/ain#2138]

**Comment by andyrobert3** [comment]
can i tackle this issue @shohamc1 !

**Comment by shohamc1** [comment]
Feel free to open a PR @andyrobert3 🙂

**Comment by cuongquangnam** [comment]
Can't wait for your PR @andyrobert3

**Comment by shohamc1** [comment]
`eth_call` already returns revert messages when available.
