### ISSUE TITLE
Poolswap executed without any user interaction!

### ISSUE THREAD

**Issue by tommuhm** [DeFiCh/ain#215]
Version used: App 2.1.15
OS: Manjaro Linux

**Update: The Problem was caused by a conflict with old transactions which never made it to the blockchain**
Question: How can we delete old transactions which were not received by the blockchain?

**The problem:**
Today at 12:10 two pool swaps were executed without any action from my side!

**What did I do:**
I performed a poolswap today from DFI to DOGE.

**What happened:**
The swapped DOGE were automatically swapped back to DFI in the same Block without any action from my side!

The containing block of the 3 swaps:
**deleted**

Info from the block explorer: All 3 transactions were received in the same second:  Feb 5, 2021, 12:10:59 PM 

Here are the swaps:
**deleted**

**Additional Infos:**
I just noticed that the 2 automatically generated swaps contain walletconflicts when i view them with `listtransactions`. What does this mean?, Can this be the cause for the generation of the swaps?

**Comment by tommuhm** [comment]
I just discovered that the mentioned wallet conflicts are my transactions from yesterday. Yesterday there were a lot of transactions which never made it to the blockchain. There were also many other users on telegram with the same issue. It seems that this transactions were new rebroadcast after I performed a new swap.

**New Question:**
Is there a way to delete this old transactions which never made it to the blockchain?

**Comment by uzyn** [comment]
You can't delete mempool but you can try restarting your node. See if it helps. 

Alternatively you can try https://bitcoin.stackexchange.com/questions/79004/how-to-cleanup-mempool

**Comment by tommuhm** [comment]
It worked, thanks a lot! 

I used `zapwallettxes` and now all the old transactions which appeared in `listtransactions` with 0 or negative confirmations disappeared. It seems that this transactions never made it to the mempool and were only rebroadcast because a conflict with a new transaction was discovered.
