### ISSUE TITLE
Exchange Rate calculation wrong

### ISSUE THREAD

**Issue by gsi2help** [DeFiCh/ain#216]
at the moment the calculation of the exchange-process is wrong, because the amount of the change depends on the amount of the coins in the pool - in my example (simulated with testpoolswap-command) you get - depending on the size of your transaction - less LTC out of pool than you gave in DFI - and after a great swap (or many less swaps in the same direction) the pool is totally unbalanced - and the next step is, that you can get out more money then you gave in

**my example is done today (the address in the command is not mine... it was the last address in the DFI-Richlist; the Result of the call is marked as bold - and size is 10, 100, 1000, 10k, 100k, 1m and 10m DFI as input, the output is not in the same proportion - DFI was about 3,02 USD, LTC about 155 USD):**
defi-app_v2.1.15
getpoolpair "LTC-DFI"
{
  "10": {
    "symbol": "LTC-DFI",
    "name": "Litecoin-Default Defi token",
    "status": true,
    "idTokenA": "9",
    "idTokenB": "0",
    "reserveA": 5869.64442322,
    "reserveB": 297019.60779815,
    "commission": 0.002,
    "totalLiquidity": 40931.15562124,
    "reserveA/reserveB": 0.0197618,
    "reserveB/reserveA": 50.60265773,
    "tradeEnabled": true,
    "ownerAddress": "8UAhRuUFCyFUHEPD7qvtj8Zy2HxF5HH5nb",
    "blockCommissionA": 2e-7,
    "blockCommissionB": 0.00000102,
    "rewardPct": 0,
    "customRewards": [
      "0.02000000@0"
    ],
    "creationTx": "75a25a52c54d12f84d4a553be354fa2c5651689d8f9f4860aad8b68c804af3f1",
    "creationHeight": 614026
  }
}
testpoolswap {"from":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenFrom":"DFI","amountFrom":"10.00000000","to":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenTo":"LTC","maxPrice":"0.0197618"}
**0.19721622@9**
testpoolswap {"from":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenFrom":"DFI","amountFrom":"100.00000000","to":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenTo":"LTC","maxPrice":"0.0197618"}
**1.97156597@9**
testpoolswap {"from":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenFrom":"DFI","amountFrom":"1000.00000000","to":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenTo":"LTC","maxPrice":"0.0197618"}
**19.65623837@9**
testpoolswap {"from":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenFrom":"DFI","amountFrom":"10000.00000000","to":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenTo":"LTC","maxPrice":"0.0197618"}
**190.81148593@9**
testpoolswap {"from":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenFrom":"DFI","amountFrom":"100000.00000000","to":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenTo":"LTC","maxPrice":"0.0197618"}
**1476.21362939@9**
testpoolswap {"from":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenFrom":"DFI","amountFrom":"1000000.00000000","to":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenTo":"LTC","maxPrice":"0.0197618"}
**4523.41037858@9**
testpoolswap {"from":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenFrom":"DFI","amountFrom":"10000000.00000000","to":"dR7Huoh5HFkdSjW1gHUYkqvYbyzFApG5KU","tokenTo":"LTC","maxPrice":"0.0197618"}
**5700.00385125@9**

**Comment by gsi2help** [comment]
To fix this problem - it is necessary to to more things:
- change the calculation the swap on the actual rates in worth of USD from the coin-ration between the 2 coins in the pool - 0.2% fee for the change only
- limit the transaction to e.g. max. 20% of the coin going out of the pool (in this example LTC)

this above 2 changes will save the money of the pool and the right calculation of the swap - with a balanced or unbalanced pool

another thing is, that you can change the receiver of the commission fee from each pool-pair-owner to the pool directly

this would grow the worth of the TVL in the pools

**Comment by bvbfan** [comment]
```
"reserveA/reserveB": 0.0197618,
"reserveB/reserveA": 50.60265773,
```
Is that ratio you looking for?

**Comment by gsi2help** [comment]
No. This is the rate DFI/LTC in the pool. not the worth in USD of DFI/LTC. At the moment the pool is a little unbalanced. But the calculation is totally wrong - look at the different sizes of my example

**Comment by uzyn** [comment]
Thanks for your report.

We are aware of an issue on slippage protection, which becomes quite prominent on smaller pools that are starting up.

The team is working on an [improved slippage protection](https://github.com/DeFiCh/ain/pull/214) that is expected to be roll out at the next consensus upgrade targeted for release this month. For now, we urge that you take caution when performing swaps for smaller pools and perform smaller swaps to lessen the effect of this.

**Comment by gsi2help** [comment]
hi @uzyn, thank you for your answer and the report, that the team is working on the problem. 
but for me it seems, that you do not understand the totally problem at the moment. so, let me try to summarize my calculation by the following sheet:

[20210205Berechnung Swap DFI-LTC für Issue216.pdf](https://github.com/DeFiCh/ain/files/5933770/20210205Berechnung.Swap.DFI-LTC.fur.Issue216.pdf)

I hope you now see the problem a little bit clearer... otherwise call me please. the fix as I see does not fixes the problem with an unbalanced pool. So please read my issue more than one time. and when you have any questions please call me. please do not upgrade before you save the money of the pool and of the owner of the swap!

Nobody can perform a smaller swap at the moment because he do not know which swaps are in the same block ... and the calculation of the swap is total different to the result in the blockchain.

**Comment by gsi2help** [comment]
as long as you do not believe the problem as I wrote you... you can't fix this in the right way.
when you have done all recalculations from the swaps of the past... then you definitive will know what I mean - and you will do nothing else than fixing this issue.

**Comment by gsi2help** [comment]
At the moment the defichain does not work as explained here: https://julianhosp.com/impermanent-loss-other-liquidity-mining-risks-explained/

Maybe you only forgot that at the moment the Exchange Rate changes with each Block depending on the ratio between the amount of both coins in the Pool and Not on the worth of the coins in US-Dollar. So After a done swap the next swap gets out More Money or had to pay More for the Same coins (because of the unbalanced Pool) When the US-Dollar value does Not change!

And both is Bad.

**Comment by Stonygan** [comment]
A decentralized exchange dont know $-values. The price at the DEX is every time calculated with the amount in it. ReserveA/ReserveB. When the pool has only 50 LTC and e.g. 2500 DFI and you want to swap 1250 DFI to 25 LTC, you dont get this 25 LTC, maybe only 10 or 15 LTC, thats a normal behaviour with small pools. To bring back the pool in balance, the Arbitrage-Trader must do their work.

**Comment by aentan** [comment]
Like @Stonygan commented, DEX rates depend on the pair ratio, not USD values nor external rates. The rates swing organically between the pair and is motivated by arbitrage opportunities created by the difference between the DEX and outside world.

**Comment by gsi2help** [comment]
@aentan @Stonygan thank you for your comment
as @uzyn has mentioned above that the team will fix this issue by https://github.com/DeFiCh/ain/pull/214

is then guaranted, that the swap was executed as calculated with the testpoolswap-command - because otherwise the confirmed transaction from the swap will differ totally - as in the past (see my comment with screenshot at https://github.com/DeFiCh/app/issues/453#issuecomment-773209593). 

Is it guaranted that all the transactions in the same block will have the same conversion-rate in the future - and not as block height 614374 in the pool LTC-DFI?: 
<img width="2020" alt="Bildschirmfoto 2021-02-01 um 18 25 39" src="https://user-images.githubusercontent.com/78414425/107144177-b07d8300-6939-11eb-8580-1f4986c9d448.png">

Can you start a test on TESTNET with the new code and following example (marketprice USD 150:3, calculation without fees for easier understanding):
Start at Pool LTC-DFI, Pool-Size 3k LTC 150k DFI (TVL USD 900k), **balanced**, **ratio** are **50 / 0.02**

- a Swap of 30k DFI to 600 LTC (or 20 Swaps a 1500 DFI to 30 LTC from different accounts at the same block height) take place
 
--> after this Swap the Pool has 2.4k LTC and 180k DFI (TVL USD 900k), is **unbalanced**, **Ratio** is now **75 / 0.013333333333**; USD-worth of coins has not changed

- wait for 10 minutes (for the next 2-20 blocks....), no swaps in this time, no marketprice changes, ...
- a Swap of 600 LTC to 45k DFI (or 20 Swaps a 20 LTC to 2250 DFI from different accounts at the same block height) take place

--> after this Swap the Pool has 3k LTC and 135k DFI (TVL USD 855k), is **unbalanced**, **15k DFI (TVL USD 45k) from the Liquity-Providers is gone** out from the pool to the receiver of the 45k DFI.... (maybe that is the arbitrage guy in your description), Ratio is now **45 / 0.0222222222**

At a normal DEX all the commissions will stay in the DEX. Wouldn't it be better to do the same in DeFiChain, instead of paying the commissions to the Token-Pair-Owners to reach a growing pool-worth with each trade?
