### ISSUE TITLE
Panic while sending used nonce via `rpc.evmtx`

### ISSUE THREAD

**Issue by canonbrother** [DeFiCh/ain#2165]
## Summary

- Docker hangs while sending a used nonce via evmtx, it was good before `defi/defichain:master-b6fc51097`, btw binary is ~good~ same as well.
- should throw error instead of panic

## Steps to Reproduce

[Please use step-by bullet points to help the team reproduce the bug]

- run ain via defi/defichain:master-8594d0aec
- send evmtx with same nonce twice

#### Logs
```
2023-07-11T07:27:48.154516Z [default wallet] keypool added 1 keys (1 internal), size=2000 (1000 internal)
defid: /work/src/validation.cpp:921: bool AcceptToMemoryPoolWorker(const CChainParams &, CTxMemPool &, CValidationState &, const CTransactionRef &, bool *, int64_t, std::list<CTransactionRef> *, bool, const CAmount &, std::vector<COutPoint> &, bool): Assertion `result.ok' failed.
qemu: uncaught target signal 6 (Aborted) - core dumped
```

**Comment by sieniven** [comment]
This seems like an emulation issue - are you running on a different architecture to the docker image architecture?

**Comment by canonbrother** [comment]
hmm.. i think its not CI issue anymore after i tested the binary 😅 .. its panic as well
properly the Result type is accidentally removed somewhere...

**Comment by canonbrother** [comment]
closed 
missing flag
https://github.com/BirthdayResearch/jellyfishsdk/pull/2105/commits/ab8a04a631a1709fbfcbd042c5e5167cc9d5e0f0
