### ISSUE TITLE
Unable to start Blockchain

### ISSUE THREAD

**Issue by gorg1919** [DeFiCh/ain#220]
Hello!
System is iMac os Big Sur Vers. 11.2, Defichain-App-Vers. 2.1.215 (download from the homepage)
after trying to send DFI from the app to cake and getting several days the error "insufficient funds" and also not being able anymore to convert DFI-Token to DFI-Coins on version 2.1.15 (did it twice before with the reddit instructions but in earlier versions, I think it was with 2.1.10 & 2.1.13) I first tried to reindex, no effect. 
Then I tried to use the new "reload UTXOS" button, no effect. 
Then i tried to restart the app and I waited till the app closed and started it again and since that I got the error "unable to start blockchain".
I hear about the beta release to the 2.1.16 and gave it a try (download from GitHub). installed the beta of 2.1.16 in hope it would fix it but no effect.
the next day official announcement of the 2.1.16 (download from homepage again) and thought maybe some updaten in the back and tried it again, no effect!
so last hope was to delete everything from my Mac and try to reinstall everything, I bet you can guess already, no effect. same issue.
so far every time I start the app the loading circle under the app version starts turning and after a while the error appears  "unable to start Blockchain".

I hope all necessary data is provided!

![photo_2021-02-09 03 43 24](https://user-images.githubusercontent.com/78722964/107308510-0e6cb080-6a89-11eb-955b-ccc852374581.jpeg)
![photo_2021-02-09 03 43 19](https://user-images.githubusercontent.com/78722964/107308513-0f9ddd80-6a89-11eb-8edd-5e853af015b1.jpeg)
![Bildschirmfoto 2021-02-09 um 03 30 00](https://user-images.githubusercontent.com/78722964/107308553-23e1da80-6a89-11eb-93cf-0cc4f659379a.png)

[Archiv.zip](https://github.com/DeFiCh/ain/files/5948379/Archiv.zip)

**Comment by gorg1919** [comment]
Tried it with 2.2.17 today -> same result. :-(

**Comment by eagleel** [comment]
Exactly the same problem here.....I have tried installing a new app but I cannot get around the apple security this time either

**Comment by eagleel** [comment]
Now managed to get a version of the app 2.1.17 to try and load, it came with the same fault 'unable to start blockchain '

**Comment by gorg1919** [comment]
now after restart the Mac an reinstall again the newer version of the 2.1.17 (I write newer because the previous did not have that feature) a pop up came and asked if I want to delete all peers, I clicked yes, the app restarted completely and had to sync again and everything and after this it works now fine... except the DFI Token to DFI Coin issue is still a thing on my end which is pretty annoying...
