### ISSUE TITLE
EVM miner to mine evm tx with higher priority fee first

### ISSUE THREAD

**Issue by sieniven** [DeFiCh/ain#2217]
## Summary
- Miner should prioritize evm transactions with the highest priority fees when mine evm transactions. The current miner pipeline mines all evm transactions into the block based on the DVM transaction (using mempool's indexed_transaction_set sorting priority).

**Comment by prasannavl** [comment]
The most ideal way would be let the EVM part of the Tx sets to plug into the existing MEV world, and just have enough machinery for miners to make this choice on their own. [LATER]

**Comment by sieniven** [comment]
Closing this issue since with our current mempool design, we will prioritize txs by default via ancestor score on the legacy btc side. Txs with fees that do not hit the next block base fees will be excluded from the block automatically, which is the best design at the moment.
