### ISSUE TITLE
Defi-app does not starting anymore

### ISSUE THREAD

**Issue by Mihalis1312** [DeFiCh/ain#225]

**Comment by Mihalis1312** [comment]
The app doesnt start and shows the failure "unable to start the blockchain". App Defi app v. 2.1.17 on Mac. reinstal didn't help. Would be great to get an idea what to do…

Txt a lot

**Comment by RalfMV** [comment]
I have the same problem with Windows 10 and the v.2.1.16

**Comment by uzyn** [comment]
This is for app. Please open an issue at https://github.com/defich/app if it's still relevant.
