### ISSUE TITLE
EVM block rejected because block total fees / Keypool ran out, keypoolrefill and restart required

### ISSUE THREAD

**Issue by bernd-mack** [DeFiCh/ain#2385]
## Summary
Masternodes in change does not mint any blocks after attached errormessage. 
![image](https://github.com/DeFiCh/ain/assets/76614620/414d0315-cbfb-44ba-b091-da36c0d7dc86)
This affects ALL masternodes at the same time and no block is created until someone restarts the defid manually

- 

## Steps to Reproduce

Just let a masternode run in changi and wait until someone creates the "magic tx that kills the minting"

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version:  beta10
- Block height on bug if applicable:  NA
- TX or TX type on bug if applicable:  NA
- OS with version: linux windows, i think it isindependent from OS
- Any other relevant environment info:

**Comment by kuegi** [comment]
same error here on mac. so not OS related.
