### ISSUE TITLE
masternode data is different: blockchain (full node) != ocean api

### ISSUE THREAD

**Issue by RoMi1981** [DeFiCh/ain#2429]
## Summary

Masternode status stays on PRE_ENABLED on ocean but is ENABLED on blockchain.

Ocean data differs from blockchain data for cli cmd:

getmasternode 917178fe9b27a8f02b98f691f3ebadb890d6ea67d93d0517395309d97e0e800f
{
  "917178fe9b27a8f02b98f691f3ebadb890d6ea67d93d0517395309d97e0e800f": {
    "ownerAuthAddress": "tf1qk369a9rt0jrqdrlq20erh759u590m2h927cyel",
    "operatorAuthAddress": "748Sz2MAQ93ctBB5m8SU6JpCaVWe8S7Pd2",
    "rewardAddress": "tf1qx5s5w33u0u7apzry0wrvaxplw37wj9ajuyeus9",
    "creationHeight": 1877660,
    "resignHeight": -1,
    "resignTx": "0000000000000000000000000000000000000000000000000000000000000000",
    "collateralTx": "0000000000000000000000000000000000000000000000000000000000000000",
    "state": "ENABLED",
    "mintedBlocks": 0,
    "ownerIsMine": false,
    "operatorIsMine": false,
    "localMasternode": false,
    "targetMultipliers": [
      1,
      1
    ]
  }
}

ocean api: https://testnet.ocean.jellyfishsdk.com/v0/testnet/masternodes or https://testnet-ocean.mydefichain.com:8443/v0/testnet/masternodes

{"data":[{"id":"917178fe9b27a8f02b98f691f3ebadb890d6ea67d93d0517395309d97e0e800f","sort":"001ca69c917178fe9b27a8f02b98f691f3ebadb890d6ea67d93d0517395309d97e0e800f","state":"PRE_ENABLED","mintedBlocks":0,"owner":{"address":"tf1qk369a9rt0jrqdrlq20erh759u590m2h927cyel"},"operator":{"address":"748Sz2MAQ93ctBB5m8SU6JpCaVWe8S7Pd2"},"creation":{"height":1877660},"timelock":0},.......

Node was created on Block height: 1877660

As I write this issue we have the block height: 1877992 and status still is different.

## Steps to Reproduce

- create an testnet operator node
- run the command createmasternode

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: docker defi/defichain:3.2.8
- Block height on bug if applicable: 1877992
- TX or TX type on bug if applicable:  917178fe9b27a8f02b98f691f3ebadb890d6ea67d93d0517395309d97e0e800f
- OS with version: arch linux docker host
- Any other relevant environment info:  testnet environment

**Comment by RoMi1981** [comment]
![Screenshot_20230907_190747_Chrome](https://github.com/DeFiCh/ain/assets/51130674/596d8b98-f289-4922-933c-a6d9a783bb57)

Pre enabeld masternodes has minted a block. This shows also the bug.

**Comment by shohamc1** [comment]
This is likely due to ocean indexing being behind the chain tip, or some caching issue. The data seems to be correct at the moment. If you find any more discrepancies in Ocean, you can open an issue in the [jellyfishsdk](https://github.com/BirthdayResearch/jellyfishsdk) repo.
