### ISSUE TITLE
Corrupted block database detected. Please restart with -reindex or -reindex-chainstate to recover. Do you want to restart? - NOT WORKING

### ISSUE THREAD

**Issue by nasilemak06** [DeFiCh/ain#252]
[DEFI_binary_error.log](https://github.com/DeFiCh/ain/files/6041670/DEFI_binary_error.log)
[DEFI_error.log](https://github.com/DeFiCh/ain/files/6041671/DEFI_error.log)

#### What happened:
I closed the DEFI APP normally and restarted my machine.
It seems the app was removed after the restart without any warnings
I downloaded and installed DEfi 2.30. After launching the app, i am getting "Corrupted block database detected. Please restart with -reindex or -reindex-chainstate to recover. Do you want to restart? "

There is no option to access the setting.

I restart but always getting the problem with the pop-up error message.
I re-install it but getting the problem with the pop-up error message.

#### What are your environment parameters:

Windows 10 Pro
Thinkpad T14S Ryzen 5 Pro
SSD

![image](https://user-images.githubusercontent.com/79631989/109127481-70b3f980-7789-11eb-95ce-d32276239871.png)

**Comment by AltCoiFish** [comment]
I am not sure @nasilemak06 this sounds like a wallet problem. 
The issue you did open is for the AIN (DFI-Node) . 

Perhaps a good idea to get better response (quick) if you move your issue to DFi-App: https://github.com/DeFiCh/app/issues

**Comment by nasilemak06** [comment]
Open in https://github.com/DeFiCh/app/issues/560
