### ISSUE TITLE
Access to fetch ... has been blocked by CORS policy

### ISSUE THREAD

**Issue by millionpixeldfi** [DeFiCh/ain#2545]
## Summary
I'm developing a web application and utilizing ethers.js to interact with smart contracts on the DMC network. However, when I use the JsonRpcProvider, I encounter the following error in my browser console:
_Access to fetch at 'https://testnet-dmc.mydefichain.com:20551/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

I have this issue since 2 month or so, before my code worked as expected. Did you changed something which I have to address ?

## Steps to Reproduce

      const customNetwork = {
        chainId: 1133,
        name: "DMC Testnet"
      }
      const provider = new ethers.providers.StaticJsonRpcProvider("https://testnet-dmc.mydefichain.com:20551", customNetwork);
      let contract = new ethers.Contract(
        contractAddr,
        abi,
        provider
      );
      latestBlock = await contract.provider.getBlock("latest"); // <-- Here I am getting the CORS error

## Environment
- Node Version: 18.16
- OS with version: Windows 10
- Ethers version:  5.4

**Comment by shohamc1** [comment]
CORS support was [recently merged](https://github.com/DeFiCh/ain/commit/5c084e693e311ddb9aca0e3029168826f349a858), however this has not been in a release yet. 

This issue is not related to the node, this RPC is provided by the community and we do not control the environment or configuration. You can try contacting the RPC providers to help solve your issue.

**Comment by Stonygan** [comment]
Maybe you can test if this RPC works for you: https://dmc.mydefichain.com/changi

**Comment by millionpixeldfi** [comment]
Changing RPC URL to https://dmc.mydefichain.com/changi solved the issue!

Thank you all for the help!
