### ISSUE TITLE
Execution of send, transfer and call function from Solidity fail

### ISSUE THREAD

**Issue by marija-mijailovic** [DeFiCh/ain#2576]
## Summary

- I've written a simple payable smart contract in Solidity. I sent some DFI to the contract, but when I tried to withdraw the funds using the 'call' function, the transaction was reverted.

```
// Function to withdraw all DFI from this contract.
    function withdraw() public {
        // get the amount of DFI stored in this contract
        uint amount = address(this).balance;

        // send all DFI to owner
        (bool success, ) = owner.call{value: amount}("");
        require(success, "Failed to send DFI");
    }

```

In addition, I tried using 'send' and 'transfer,' but the transaction was also reverted.

## Steps to Reproduce

Write and deploy a smart contract with some low-level functions, and then attempt to execute it using ethers.js

## Environment

- Node Version: 
- Block height on bug if applicable: 
- TX or TX type on bug if applicable:  

> ```
> {
>   "input": "0xdc1bd21a20df599bf7b4a72acb57d5f67dc8d1c47d3ba943e32885e6d71a2a36",
>   "type": "TxHashEVMToDVM",
>   "output": "a1288473b302f01a54a80fbfc296d58e0cf15ded048a098b90334f1b617b2ef3"
> } 
> ```

> [blockscout tx](https://blockscout.changi.ocean.jellyfishsdk.com/tx/0xdc1bd21a20df599bf7b4a72acb57d5f67dc8d1c47d3ba943e32885e6d71a2a36)

- OS with version: MacOs
- Any other relevant environment info: 

> - Solc Version: 0.8.21+commit.d9974bed.Darwin.appleclang
> - Hardhat - 2.17.4

**Comment by cuongquangnam** [comment]
I think this may be related to gas estimation. Can you try again with 50000 gas limit?

**Comment by cuongquangnam** [comment]
And can you help verify the smart contract or send the source code here?
I deployed a similar smart contract and then executed same function. It's successful with lower gas used.
https://testnet-dmc.mydefichain.com:8444/tx/0x014f2bafbb31520c125ca192d0cbd971caca618eb15f910e443bb17ffbe316ef

**Comment by cuongquangnam** [comment]
Just curious, how did you get the gas Limit from, just to check whether you are using any of our RPC methods, haha

**Comment by sieniven** [comment]
With the gas estimate fixes in https://github.com/DeFiCh/ain/pull/2633, this issue should no longer be present on stable.
