### ISSUE TITLE
DMC - smart contract gas estimation/call does not fail for invalid function parameters

### ISSUE THREAD

**Issue by luigijr44** [DeFiCh/ain#2617]
## Summary
As-is:
- a smart contract function which is called with invalid parameters does not return an error message on the DMC
- if the function is then executed, the transaction will be mined but the function will fail

To-be:
- calling a function with invalid parameters/or parameters that will obviously result in a revert should return an error message, so the user does not have to spend time and gas on a transaction that will fail anyway.

## Steps to Reproduce

Please see the attached videos for reproducing the behavior with Remix.
One video is showing the behavior on [Ethereum Sepolia](https://github.com/DeFiCh/ain/assets/39170831/19cb5920-c69f-4ff5-89a6-e71a4fc19c0c) and one on [DMC Changi](https://github.com/DeFiCh/ain/assets/39170831/c769d705-1fb1-43f7-8de7-7cffcd253144).

The inserted data for createChallenge is invalid in both cases (the due date is not in the future).
The following require inside the contract is then expected to fail:
`require(
            _dueDate >= block.timestamp + MINIMUM_CHALLENGE_PERIOD,
            "Due date must be bigger than current time plus minimum challenge period"
        );`

As you can see, on Sepolia an error message is shown right after clicking on "transact" (the error is already returned on the gas estimation).
On DMC no error message is shown after clicking on "transact", only once the transaction has been mined you can see that it failed.

## Environment

This can be reproduced on both Changi and Testnet 3, with v4.0.0-rc1.
This is also not limited to Remix, but can be reproduced from a JavaScript application using web3.js (with both web3.js versions 1.x and 4.x).
And it is also not related to the smart contract, since I was able to reproduce this with another one and with other functions as well.

The example failed transaction on DMC Changi can be found here:
https://testnet-dmc.mydefichain.com:8444/tx/0xb163290a9e8f470442d019cf51649929e7ffabbc412270fde7772efee430ec5d/state
The source code can be found here:
https://testnet-dmc.mydefichain.com:8444/address/0x3b556d6D551036522a15C47d0baec131D7469272/contracts#address-tabs

**Comment by sieniven** [comment]
The underlying eth RPCs should have been resolved and fixed on stable. The defid gas estimation pipeline should align with geth, and your contract function call should fail on the gas estimation pipeline now similar to the behaviour on ethereum. If the behaviour isnt the same, please feel free to re-open the issue. Many thanks.
