### ISSUE TITLE
Contract Call Error: (Awaiting internal transactions for reason) when sending funds other than DFI

### ISSUE THREAD

**Issue by RoMi1981** [DeFiCh/ain#2627]
## Summary

- it is not possible to send funds (except DFI) between different external EVM addresses, check block explorer transactions: https://testnet3-dmc.mydefichain.com:8445/address/0x9fdD94027e262A1A66A0070aFAf3FE3080E2714d/transactions#address-tabs
- as to address the token contract address is shown
- final results:
Sending from DVM to any EVM address with any token is working
Sending from external EVM to any EVM address is only working with dfi

## Steps to Reproduce

[Please use step-by bullet points to help the team reproduce the bug]

- create a metamask ERC55 address
- send ETH, BTC or any other DVM token to this new created address (transferdomain or lightwallet)
- try to send these tokens back to a lightwallet or node ERC55 address 

## Environment

[Please fill all of the following or NA if not applicable]

- Testnet3
- Node Version: 4.0.0-rc1
- Block height on bug if applicable: evm Block #15915
- TX or TX type on bug if applicable:  -
- OS with version: tested all with Android LW 2.27.0 and metamask mobile
- Any other relevant environment info:  see above

**Comment by Jouzo** [comment]
Was able to reproduce with these steps but manage to transfer fund through using Metamask aggresive fee

**Comment by RoMi1981** [comment]
Could you share your transaction hash?

**Comment by Jouzo** [comment]
`0x22ccf57f3aa784c36756f7214ce4c01bf920b3715252af8c1eaa82e3ea484af2`
and
`0xa3efb0087f3cecf169330e4730a04ad542c80e975f368600667d6eecfacbf326`
Both on changi

**Comment by RoMi1981** [comment]
https://blockscout.testnet.ocean.jellyfishsdk.com/tx/0x3ff3653c08912fb2c3be28e780f5a8efa305b991df9b15baeef90060062215e2

Also with aggressive fee setting in metamask, transaction is failing for BTC send.

I'm on the testnet3, not Changi

**Comment by kuegi** [comment]
@RoMi1981 it looks like all your txs are running out of gas. I don't know why, but your MM is setting a far too low gas limit.

your tx has a limit of 39k gas
I just sent 1 BTC on testnet3: https://blockscout.testnet.ocean.jellyfishsdk.com/tx/0x9f0043dff4a23769465127a8ad40e0c392cff87c849e8a33f9d42d3bc797ee0e
MM set a gaslimit of 84k and it used 56k

**Comment by RoMi1981** [comment]
Thanks for the hint @kuegi I have to retest this issue after testnet3 is running again with rc2

Actual it is messed up :)

**Comment by RoMi1981** [comment]
Due to @kuegi 's hint I tested a little bit, here are my DMC testnet3 settings:

![Screenshot_20231027_081030_MetaMask](https://github.com/DeFiCh/ain/assets/51130674/b220ecd9-13fa-4700-aef9-79a65fe35618)

If I try to send with default gas settings (untouched)

![Screenshot_20231027_084641_MetaMask](https://github.com/DeFiCh/ain/assets/51130674/695d5a10-1bb9-48a1-a674-87e04533214e)

Tx will fail like described above.

I have to raise the gas limit on each transaction to (example):

![Screenshot_20231027_084658_MetaMask](https://github.com/DeFiCh/ain/assets/51130674/492e4f7b-8ab8-4983-ad5c-014405370b96)

Then I'm able to send the BTC and tx will finish successful.

https://blockscout.testnet.ocean.jellyfishsdk.com/tx/0x63e7588ca60bdb399aebfdc56202c8206a3707c066684138279d421848a5680f

I'm on MetaMask for Android. On MetaMask browser plugin it seems to work. There is a higher default gas value. But please double check it.

Thanks and BR

**Comment by sieniven** [comment]
PR #2633 should resolve this issue - the PR fixes the estimate_gas RPC to align with geth, using a binary search to determine the gas limit from a eth call context.
