### ISSUE TITLE
4.0.0.0 crash

### ISSUE THREAD

**Issue by leeado-stack** [DeFiCh/ain#2673]
## Summary

defid crash

## Steps to Reproduce
Testnet from snapshot 1150129

2023-11-03T07:13:02Z Cache configuration:
2023-11-03T07:13:02Z * Using 4.0 MiB for block index database
2023-11-03T07:13:02Z * Using 8.0 MiB for chain state database
2023-11-03T07:13:02Z * Using 500.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
2023-11-03T07:13:02Z DfTxTaskPool: Init (0)
2023-11-03T07:13:02Z DfTxTaskPool: Size: 1
2023-11-03T07:13:02Z init message: Loading block index...
2023-11-03T07:13:02Z Opening LevelDB in /home/ubuntu/.defi/testnet3/blocks/index
2023-11-03T07:13:02Z Opened LevelDB successfully
2023-11-03T07:13:02Z Using obfuscation key for /home/ubuntu/.defi/testnet3/blocks/index: 0000000000000000
2023-11-03T07:19:32Z LoadBlockIndexDB: last block file = 6
2023-11-03T07:19:32Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=48077, size=84548634, heights=1102166...1150129, time=2022-07-06...2023-10-17)
2023-11-03T07:19:32Z Checking all blk files are present...

2023-11-03T07:21:05Z Opening LevelDB in /home/ubuntu/.defi/testnet3/chainstate
2023-11-03T07:21:05Z Opened LevelDB successfully
2023-11-03T07:21:05Z Using obfuscation key for /home/ubuntu/.defi/testnet3/chainstate: 9f207ea4e85c2dc2
2023-11-03T07:21:05Z Opening LevelDB in /home/ubuntu/.defi/testnet3/enhancedcs
2023-11-03T07:21:05Z Opened LevelDB successfully
2023-11-03T07:21:05Z Using obfuscation key for /home/ubuntu/.defi/testnet3/enhancedcs: 0000000000000000
2023-11-03T07:21:05Z Opening LevelDB in /home/ubuntu/.defi/testnet3/history
2023-11-03T07:21:05Z Opened LevelDB successfully
2023-11-03T07:21:05Z Using obfuscation key for /home/ubuntu/.defi/testnet3/history: 0000000000000000
2023-11-03T07:21:05Z Opening LevelDB in /home/ubuntu/.defi/testnet3/burn
2023-11-03T07:21:05Z Opened LevelDB successfully
2023-11-03T07:21:05Z Using obfuscation key for /home/ubuntu/.defi/testnet3/burn: 0000000000000000
2023-11-03T07:21:05Z [ain_grpc] Init rs services
2023-11-03T07:21:05Z [ain_evm::services] Starting tokio waiter
thread '<unnamed>' panicked at 'Error initializating handlers: RocksDBError(Error { message: "Invalid argument: Column families not opened: code_map" })', ain-evm/src/services.rs:71:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'panic in ffi function ain_rs_exports::ffi::ain_rs_init_core_services, aborting.', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cxx-1.0.110/src/unwind.rs:37:9
stack backtrace:
   0:     0x55aecd47cb57 - std::backtrace_rs::backtrace::libunwind::trace::h66dc1c6acf794faa
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55aecd47cb57 - std::backtrace_rs::backtrace::trace_unsynchronized::ha80d20099a67f790
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55aecd47cb57 - std::sys_common::backtrace::_print_fmt::h7b959d43f35f16d4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55aecd47cb57 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdaa196410d9ee0b9
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55aecd2d0bef - core::fmt::rt::Argument::fmt::h0ddfbbe8be3f80d0
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/rt.rs:138:9
   5:     0x55aecd2d0bef - core::fmt::write::h66b3c629f3d623e4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/mod.rs:1094:21
   6:     0x55aecd44e346 - std::io::Write::write_fmt::hb6d80fba4115e0c2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/io/mod.rs:1714:15
   7:     0x55aecd47e2af - std::sys_common::backtrace::_print::h1a49cfb0cf3cce17
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55aecd47e2af - std::sys_common::backtrace::print::hca95c2d0055e42a2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55aecd47de70 - std::panicking::default_hook::{{closure}}::hc03c01c56bca600c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:269:22
  10:     0x55aecd47ee88 - std::panicking::default_hook::hb2cb5315b6634f1c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:288:9
  11:     0x55aecd47ee88 - std::panicking::rust_panic_with_hook::h75cd912a39a34e8a
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:705:13
  12:     0x55aecd47e972 - std::panicking::begin_panic_handler::{{closure}}::h1498b46f7849e167
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:597:13
  13:     0x55aecd47e8d6 - std::sys_common::backtrace::__rust_end_short_backtrace::hd36a39b27b98086b
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55aecd47e8c1 - rust_begin_unwind
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
  15:     0x55aecc7e6df2 - core::panicking::panic_fmt::h98ef273141454c23
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
  16:     0x55aecc7e7757 - <cxx::unwind::Guard as core::ops::drop::Drop>::drop::hbe1548815c2964a6
  17:     0x55aecd27cc26 - core::ptr::drop_in_place<cxx::unwind::Guard>::h73ae1f36fa9b6fee
  18:     0x55aecd28058b - cxxbridge1$ain_rs_init_core_services
  19:     0x55aecce4f7d3 - _Z25ain_rs_init_core_servicesR19CrossBoundaryResult
  20:     0x55aecc8918a1 - _ZZ11AppInitMainR14InitInterfacesENK3$_8clEv
  21:     0x55aecc88b823 - _Z11AppInitMainR14InitInterfaces
  22:     0x55aecc867ab1 - main
  23:     0x7fac07e92d90 - <unknown>
  24:     0x7fac07e92e40 - __libc_start_main
  25:     0x55aecc866dce - _start
  26:                0x0 - <unknown>
thread '<unnamed>' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
   0:     0x55aecd47cb57 - std::backtrace_rs::backtrace::libunwind::trace::h66dc1c6acf794faa
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55aecd47cb57 - std::backtrace_rs::backtrace::trace_unsynchronized::ha80d20099a67f790
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55aecd47cb57 - std::sys_common::backtrace::_print_fmt::h7b959d43f35f16d4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55aecd47cb57 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdaa196410d9ee0b9
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55aecd2d0bef - core::fmt::rt::Argument::fmt::h0ddfbbe8be3f80d0
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/rt.rs:138:9
   5:     0x55aecd2d0bef - core::fmt::write::h66b3c629f3d623e4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/mod.rs:1094:21
   6:     0x55aecd44e346 - std::io::Write::write_fmt::hb6d80fba4115e0c2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/io/mod.rs:1714:15
   7:     0x55aecd47e2af - std::sys_common::backtrace::_print::h1a49cfb0cf3cce17
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55aecd47e2af - std::sys_common::backtrace::print::hca95c2d0055e42a2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55aecd47de70 - std::panicking::default_hook::{{closure}}::hc03c01c56bca600c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:269:22
  10:     0x55aecd47ee88 - std::panicking::default_hook::hb2cb5315b6634f1c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:288:9
  11:     0x55aecd47ee88 - std::panicking::rust_panic_with_hook::h75cd912a39a34e8a
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:705:13
  12:     0x55aecd47e943 - std::panicking::begin_panic_handler::{{closure}}::h1498b46f7849e167
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:595:13
  13:     0x55aecd47e8d6 - std::sys_common::backtrace::__rust_end_short_backtrace::hd36a39b27b98086b
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55aecd47e8c1 - rust_begin_unwind
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
  15:     0x55aecc7e7379 - core::panicking::panic_nounwind_fmt::hd751fcb82a791f5b
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:96:14
  16:     0x55aecc7e73ea - core::panicking::panic_nounwind::hc62d0ba7772d7051
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:126:5
  17:     0x55aecc7e7396 - core::panicking::panic_cannot_unwind::ha2a820cb42f0ce8a
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:189:5
  18:     0x55aecd280592 - cxxbridge1$ain_rs_init_core_services
  19:     0x55aecce4f7d3 - _Z25ain_rs_init_core_servicesR19CrossBoundaryResult
  20:     0x55aecc8918a1 - _ZZ11AppInitMainR14InitInterfacesENK3$_8clEv
  21:     0x55aecc88b823 - _Z11AppInitMainR14InitInterfaces
  22:     0x55aecc867ab1 - main
  23:     0x7fac07e92d90 - <unknown>
  24:     0x7fac07e92e40 - __libc_start_main
  25:     0x55aecc866dce - _start
  26:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: 4.0.0.0
- Block height on bug if applicable: 1150129 testnet
- TX or TX type on bug if applicable:  
- OS with version: Ubuntu 22.04.3 LTS
- Any other relevant environment info:

**Comment by shohamc1** [comment]
Seems like you need to do a reindex, try launching the node with `-reindex`.

**Comment by sieniven** [comment]
This is a known issue with the old testnet snapshot pre rc-2, as the snapshot contains invalid EVM directory post rc-2 which will cause the crash. Please re-download the snapshot [here](https://storage.googleapis.com/team-drop/snapshots/testnet/snapshot-testnet-1150129.tar.gz)
