### ISSUE TITLE
Binary release: defid v.4.0.0 does not start on Debian 10 b/c of glibc > 2.28 required

### ISSUE THREAD

**Issue by defijeff** [DeFiCh/ain#2688]
## Summary

defid v4.0.0 does not start on Debian 10 (Buster) / glibc 2.28 based systems 

## Steps to Reproduce

Download v.4.0.0 binaries and trying to start on Debian throws error "GLIBC_2.29 / GLIBC_2.30 not found"

## Environment

- Node Version:  4.0.0
- Block height on bug if applicable:  n/a
- TX or TX type on bug if applicable:  n/a
- OS with version:  Debian 10 Buster (10.13)

* v 3.2.x binary releases worked fine on Debian 10, v 4.0.0 doesn't start as it requires glibc > 2.28. Ideally cross-compilation of the binaries could be done on a system still featuring glibc 2.28. If this is not possible, at least give a warning for the upgrade process, that it's mandatory to have a newer operation system.

**Comment by shohamc1** [comment]
Debian 10 is no longer supported as of 4.0.0. Please update your OS to Debian 11 or 12.

**Comment by prasannavl** [comment]
Thanks for report @defijeff. We should add it to release notes. Was missed. 

Additionally, Debian 10 hasn't still reached EOL (though it will in early 2024). If llvm-15 works on Debian 10, we can in theory support it by moving the CI back though. Would be keen to move to Debian stable for CI soon so this is less of an issue.
