### ISSUE TITLE
which is the AIN (latest) version to safely use?

### ISSUE THREAD

**Issue by AltCoiFish** [DeFiCh/ain#270]
#### What happened:
There was/is some confusion in my mind in which version of `ain` is now the one we should all be using?
I in particular did receive a lot of `release` e-mails/github requests of changing `ain version` numbers.

At the moment my servers are running with:
```
# ./defid --version
DeFi Blockchain Daemon version 1.5.1
Copyright (C) 2009-2020 The DeFi Blockchain developers

```

but on Gihub https://github.com/DeFiCh/ain/releases/tag/v1.5.1 is marked as `pre-release` ? (while writing this issue) 
Two days ago it was the `latest` version, which we are using currently.

**Questions:**

+ (1) Can we safely use the v1.5.1 on our servers? or should we roll back to latest version which is currently v.1.5?
+ (2) Ca a master-node operator safely use the v1.5.1 

Can you also please explain the `release` cycle issues you having last 2 days?

**Some background information:** 
We are checking the GitHub repository for new `latest` releases based on some GitHub commands and do compile the source for our servers at the moment. But with the software changes we run into some compiling problems and rolled back to the provided v.1.5.1 binaries aprox. 1-2 days ago.

**Comment by monstrobishi** [comment]
Hi I just changed the build process so pre-release won't become latest while building (earlier we have to set to latest for an hour while it builds).

From now on you should see latest is the latest (1.5.0).

Having said that, 1.5.1 should be safe to use.

**Comment by AltCoiFish** [comment]
> Having said that, 1.5.1 should be safe to use.

Thank you for clarifying it, but perhaps it should be in the interest of all `ain` operators and administrators that you specify that people should upgrade **their version `1.5.1`  to `1.5.1` to the latest version.** Otherwise we run the risk having `ain` nodes on different `current``version which should be no problem hopefully? 

Because currently I am running on `defid` version `1.5.1` on my servers which differs from the current version 1.5.1.

**On servers:**
```
/opt/dfi/server/defichain/bin# ./defid --version | head -n 4
DeFi Blockchain Daemon version 1.5.1
Copyright (C) 2009-2020 The DeFi Blockchain developers
Copyright (C) 2009-2020 DeFi Blockchain Developers

dfi01:/opt/dfi/server/defichain/bin# sha256sum defid 
9bbb3e221cf8336154d333df804bd3a2f3efa5832c65d7962952d27d6ca3accf  defid
```

**from the current github repo as of ` 6dc990c`**

```
sha256sum defid 
29fb272a1fa5f1dfed6def7baea506739d3765c780d2e90d44696b43f36d98db  defid
```

**Comment by MCM-Mike** [comment]
New binaries are now compiled at https://github.com/DeFiCh/ain/releases/tag/v1.5.1 should be fine to upgrade now.
But I still it was confusing having one versions with different binaries. 

You could close this ticket now.

**Comment by AltCoiFish** [comment]
I am closing this ticket now, even it was still confusing the one version with two different binaries released as `latest` .
