### ISSUE TITLE
V4.0.1: ERROR: ReadBlockFromDisk: OpenBlockFile failed for FlatFilePos(nFile=-1, nPos=0) maybe "pruning problem"

### ISSUE THREAD

**Issue by neuriGH** [DeFiCh/ain#2704]
## Summary
After upgrading to V4.0.0 thy system (Ubuntu) worked well for a couple of days, after that the node can not be started with the following error: ERROR: ReadBlockFromDisk: OpenBlockFile failed for FlatFilePos(nFile=-1, nPos=0)  (Same happens after upgrading to 4.0.1)
- 

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version:  V4.0.1
- Block height on bug if applicable: 
- TX or TX type on bug if applicable:  
2023-11-19T07:16:03Z New outbound peer connected: version: 70038, blocks=3471324, peer=6
2023-11-19T07:16:15Z UpdateTip: new best=41f5cf9de9f69e794c15a03daadede8353e592787e299c4c04970d175f1f1a12 height=3464100 version=0x20000000 log2_work=87.939705 tx=27139796 date='2023-11-16T22:27:02Z' progress=0.998614 cache=0.1MiB(786txo)
2023-11-19T07:16:15Z ERROR: ReadBlockFromDisk: OpenBlockFile failed for FlatFilePos(nFile=-1, nPos=0)
- OS with version: ubuntu-jammy-22.04-amd64-server-20221201
- Any other relevant environment info:

**Comment by prasannavl** [comment]
Hi. This seems like a corrupt data (possibly unclean shutdown?). 
Please try restoring from a recent snapshot / backup or full sync.

**Comment by neuriGH** [comment]
Hi, have found a second user with exactly the same problem. For him, the problem occurs every time he activates pruning. This is reproducible. In my case, pruning is also activated. Perhaps you can check whether activated pruning also leads to this error in your test lab. (In the meantime I have updated to V.4.0.4 - same problem)

**Comment by prasannavl** [comment]
Closing. Outdated issues cleanup.
