### ISSUE TITLE
4.0.4 and 4.0.5 and 4.0.6 defid crash at Tokio waiter on windows11

### ISSUE THREAD

**Issue by bernd-mack** [DeFiCh/ain#2720]
## Summary
- Node on windows stops immediatelly after "starting wokio waiter" without errormessage or log entry.
![image](https://github.com/DeFiCh/ain/assets/76614620/a4f6fd77-fb4d-4054-a811-120bde73439f)

## Steps to Reproduce
- latest desktopwallet and replace manually defid with v4.0.4
- then start wallet

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: 4.0.4
- Block height on bug if applicable: n/a
- TX or TX type on bug if applicable:  n/a
- OS with version: Windows 11 with desktopwallet
- Any other relevant environment info:  structure of zip file is a bit different to the other versions: defichain-4.0.4-x86_64-w64-mingw32.zip\__w\ain\ain\build\defichain-4.0.4

**Comment by DanielZirkel** [comment]
Also on my side the node SW 4.0.4 is not working
It starts running, but stops without any error after tokio waiter. No clue what happened and what's the reason.
![image](https://github.com/DeFiCh/ain/assets/68841661/a9e38bf2-a6ae-4df5-a9ca-ba0dbd230bf7)

**Comment by lazydrone** [comment]
I experienced the same.  Windows Desktop wallet would stall at the splash screen.  Logs show it stopped at "starting tokio waiter"
reverted to 4.0.3 which loaded without issue.

**Comment by NMF1812** [comment]
I am having problems with the 4.0.7
How can I download 4.0.6 again?

**Comment by bernd-mack** [comment]
same issue with v4.0.6
2023-12-14T22:25:12Z [ain_evm::services] Starting tokio waiter

and then crash.
3 weeks and new version for node does not work on windows. Also desktowallet is not useable.

**Comment by prasannavl** [comment]
Hi @bernd-mack - apologies for the delay on this - December slow down + Covid resurgence ended up with longer than usual delays in the team and had to triage.  

We should be able to dig into this early next week. Quick glance through the changeset, looks like this could be related to boost dep update https://github.com/DeFiCh/ain/commit/d7c7b834b81a766d6bff192e9c580f00c4746f5d. 

If you're able to compile, would be helpful to know if reverting this PR resolves the issue. Otherwise, someone from the core team should be able to look at the coming week

**Comment by prasannavl** [comment]
In the off-chance any one has a core dump from Windows, that would be great

**Comment by marcelkb** [comment]
i have the same problem, win 11 with newest defi version 4.0.6
only says
2023-12-17T09:03:29Z Opened LevelDB successfully
2023-12-17T09:03:29Z Using obfuscation key for C:\Users\XXX\AppData\Roaming\DeFi Blockchain\burn: 0000000000000000
2023-12-17T09:03:29Z [ain_grpc] Init rs services
2023-12-17T09:03:29Z [ain_evm::services] Starting tokio waiter
PS C:\Windows\System32\WindowsPowerShell\v1.0>

no reason for shutdown, linux version works fine, 4.0.0 too

**Comment by M-Stege** [comment]
Hello @prasannavl,

is there anything new about Desktopwallet under Windows? https://github.com/DeFiCh/ain/issues/2720

best regards from Germany

**Comment by canonbrother** [comment]
@M-Stege 
can you download the release and try again? it should be working for the new one
https://github.com/DeFiCh/ain/releases
![image](https://github.com/DeFiCh/ain/assets/8097901/82f24171-2241-4dc6-9836-223410323b05)

**Comment by Stonygan** [comment]
This version is not working. See a new devbuild with https://github.com/DeFiCh/ain/pull/2757
But this version not working, too.

**Comment by M-Stege** [comment]
@canonbrother thanks this Wallet starts
@Stonygan Die Node-Version startet zumindest. Sie wurde aber ausgewechselt. Ich hatte mir noch die "defichain-4.0.6-x86_64-w64-mingw32.zip" heruntergeladen als Sie verfügbar war. die heißt aber jetzt "defichain-latest-x86_64-w64-mingw32.zip"
Ist also etwas ungüstig gelaufen das man die selbe Version ersetzt hat statt es als neue Version einzustellen.

**Comment by bernd-mack** [comment]
@canonbrother thank your, this one https://github.com/DeFiCh/ain/releases/download/v4.0.6/defichain-latest-x86_64-w64-mingw32.zip looks good so far ✅

**Comment by prasannavl** [comment]
Closing as it's been fixed.
