### ISSUE TITLE
Desktop Full-Node Wallet 4.0.8 for Windows is always just loading but never showing its UI!

### ISSUE THREAD

**Issue by AmigoCrypto** [DeFiCh/ain#2761]
Desktop Full-Node Wallet 4.0.8 for Windows is always just loading but never showing its UI since its release! Please help or fix this! Thank You!
![Screenshot 2023-12-23 182420](https://github.com/DeFiCh/ain/assets/151651329/f85fca4b-6447-4445-a32d-5bff5d8fc893)

**Comment by prasannavl** [comment]
Closing, different project.
