### ISSUE TITLE
Deploy Multicall3 to DeFiChain EVM layer

### ISSUE THREAD

**Issue by gjj** [DeFiCh/ain#2767]
## Summary

`Metacall3` lets you batch deploy contract calls into a single tx, useful to save on gas fees, especially for multichain dApps that already use this pattern in other chains, and would like to have it on EVM.

For more info on https://www.multicall3.com/

Related
- https://github.com/wevm/viem/pull/1642 added to viem chain definitions
- https://github.com/mds1/multicall/pull/192 added to multicall3 repo

Deployment addresses
- https://meta.defiscan.live/address/0xcA11bde05977b3631167028862bE2a173976CA11
- https://meta.defiscan.live/address/0xcA11bde05977b3631167028862bE2a173976CA11?network=TestNet

**Comment by gjj** [comment]
Deployed at
- https://meta.defiscan.live/address/0xcA11bde05977b3631167028862bE2a173976CA11
- https://meta.defiscan.live/address/0xcA11bde05977b3631167028862bE2a173976CA11?network=TestNet

**Comment by prasannavl** [comment]
Neat. Thanks @gjj!
