### ISSUE TITLE
Broken win-x64 binary when cross compiled on host OS Ubuntu versions 20.04

### ISSUE THREAD

**Issue by sieniven** [DeFiCh/ain#2768]
## Summary

- defid binaries targeted for win-x64 architecture crashes on start up when cross compiled on linux-x64 host architecture running Ubuntu 20.04.
- However, defid win-x64 binaries cross compiled on Ubuntu 22.04 works fine.

**Comment by prasannavl** [comment]
Closing outdated / stale issues.
