### ISSUE TITLE
Add support for blockscout internal transaction indexing

### ISSUE THREAD

**Issue by Jouzo** [DeFiCh/ain#2786]
## Summary

- Add `trace_replayBlockTransactions` implementation as required by blockscout for indexing internal transaction

## Rationale

- Blockscout needs to pick up addresses as contract when created by factory contract and/or Create2 opcode. 

See :
https://blockscout.testnet.ocean.jellyfishsdk.com/address/0x3500Aa51d046aaE9C2691CBcfbCeb98B1438dd0B?tab=logs deployed via factory deployer. Should be correctly picked up as a contract.

Creation TX : https://blockscout.testnet.ocean.jellyfishsdk.com/tx/0xb9edca2ba22e040659adfe97b1878b26282a23e7b350eb9f64db4c7a1bd02303

## RPCs

- `trace_replayBlockTransactions`

## Flags

- Behind `ethdebugtrace` node flag

## Potential Implementation Timeline

- Ideally within the next few weeks, multiple community projects are blocked because of it.

**Comment by prasannavl** [comment]
Completed as of https://github.com/DeFiCh/ain/commit/8a0e0d8221851709845d30dcf3ae44b6847b9d95
