### ISSUE TITLE
Ocean: Transaction indexing

### ISSUE THREAD

**Issue by Jouzo** [DeFiCh/ain#2800]
## Summary

- [x] Fix Vin and Vout typing
- [x] Fix Vin indexing key -> (txid, vout.txid, vout.n)
- [x] Fix Vout indexing key -> (txid, vout.n)
- [x] Add missing Vin/Vout invalidation handling
- [x] Properly index transaction in `index_block`

**Comment by nagarajm22** [comment]
Transaction indexing for above task is fixed :) @Jouzo

**Comment by Jouzo** [comment]
Fixed in https://github.com/DeFiCh/ain/pull/2802
