### ISSUE TITLE
Zertificate of the webpage https://api.defichain.io/v1/stats is no more valid

### ISSUE THREAD

**Issue by wuschew** [DeFiCh/ain#2840]
Pls renew as soon as possible the certificate, because is no more possible to get api data. Security error prevent to use get function. Thx

**Comment by Stonygan** [comment]
it is possible that coingecko use this API? no new price for DUSD since 2-3 days.

**Comment by prasannavl** [comment]
Believe this is now resolved - even though these are deprecated APIs to support those still in migration.
