### ISSUE TITLE
"refreshing UTXOs" never finishes in ver. 4.0.9

### ISSUE THREAD

**Issue by yhurynovich** [DeFiCh/ain#2848]
I have two addresses linked to my wallet.

It is the second attempt to pre-fund transaction now with no success. The " _Refreshing UTXOs. This may take some time._ " message stays for hours. I have to restart the wallet app to unblock the screen.

![UTXO](https://github.com/DeFiCh/ain/assets/6166796/f799bf0a-042b-4a0a-9eb4-e131b06e5075)

CLI Output:
getbalance
0

gettokenbalances
[
  "349.45066631@0",
  "0.00061369@1",
  "0.04330003@2",
  "37.86704970@4",
  "82.57753585@5",
  "0.38956572@9",
  "400.69367706@10",
  "0.00000001@14",
  "1.24698488@15",
  "0.06736695@29",
  "124.85974359@46"
]

listaccounts {} false false true
[
  {
    "key": "a914...@0",
    "owner": "dRL...",
    "amount": "43.74221498@DFI"
  },
  {
    "key": "a914...@1",
    "owner": "dRL...",
    "amount": "0.00003472@ETH"
  },
  {
    "key": "a91...@2",
    "owner": "dRL...",
    "amount": "0.00000050@BTC"
  },
  {
    "key": "a914...@4",
    "owner": "dRL...",
    "amount": "1.43380687@ETH-DFI"
  },
  {
    "key": "a914...@5",
    "owner": "dRL...",
    "amount": "0.51723940@BTC-DFI"
  },
  {
    "key": "a914...@9",
    "owner": "dRL...",
    "amount": "0.00030631@LTC"
  },
  {
    "key": "a914...@10",
    "owner": "dRL..",
    "amount": "0.36594642@LTC-DFI"
  },
  {
    "key": "a914...@15",
    "owner": "dRL...",
    "amount": "0.37898965@DUSD"
  },
  {
    "key": "a914...@29",
    "owner": "dRL...",
    "amount": "0.01858128@SLV"
  },
  {
    "key": "a914...@46",
    "owner": "dRL...",
    "amount": "19.59383686@SLV-DUSD"
  },
  {
    "key": "a914...@0",
    "owner": "dak7...",
    "amount": "305.77273191@DFI"
  },
  {
    "key": "a914...@1",
    "owner": "dak7...",
    "amount": "0.00057897@ETH"
  },
  {
    "key": "a914....@2",
    "owner": "dak7...",
    "amount": "0.04329953@BTC"
  },
  {
    "key": "a914....@4",
    "owner": "dak7...",
    "amount": "36.43324283@ETH-DFI"
  },
  {
    "key": "a914...@5",
    "owner": "dak7...",
    "amount": "82.06029645@BTC-DFI"
  },
  {
    "key": "a914...@9",
    "owner": "dak7...",
    "amount": "0.38925941@LTC"
  },
  {
    "key": "a914...@10",
    "owner": "dak7...",
    "amount": "400.32773064@LTC-DFI"
  },
  {
    "key": "a914...@14",
    "owner": "dak7...",
    "amount": "0.00000001@USDC-DFI"
  },
  {
    "key": "a914...@15",
    "owner": "dak7...",
    "amount": "0.86799523@DUSD"
  },
  {
    "key": "a914...@29",
    "owner": "dak7...",
    "amount": "0.04878567@SLV"
  },
  {
    "key": "a914...@46",
    "owner": "dak7...",
    "amount": "105.26590673@SLV-DUSD"
  }
]

**Comment by prasannavl** [comment]
Closing. Please create an issue in the desktop wallet repo if you continue to have issues. This is for the node and blockchain and is not actionable here.
