### ISSUE TITLE
IPs in seed.defichain.io not longer available

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/ain#285]
#### What happened:
In chainparams.cpp is a URL seed.defichain.io with 2 IP-Adresses.
Name:    seed.defichain.io
Addresses:  
173.230.129.187
172.105.126.56

172.105.126.56 is reachable and runs a Node on it over Port 8555.

173.230.129.187 has no open port 8555, cant reach the Node.

#### What you expected to happen:
Masternode or Fullnode reachable on Port 8555 at this IPs.

#### How to reproduce it (as minimally and precisely as possible):
nslookup seed.defichain.io
Test Port 8555 or use bitnodes.io

I create a new DNS-Seed seed.mydeficha.in with multiple Community Fullnodes or Masternodes. Please let me know, if its possible to hardcode this DNS-Seed in the Code, too. Must i open a separate Feature Request?

**Comment by uzyn** [comment]
Thanks for reporting. Fixing it.

**Comment by asyrafnorafandi** [comment]
Fixed it. Point to 4 different working Masternodes now.

**Comment by uzyn** [comment]
@Stonygan 

> I create a new DNS-Seed seed.mydeficha.in with multiple Community Fullnodes or Masternodes. Please let me know, if its possible to hardcode this DNS-Seed in the Code, too. Must i open a separate Feature Request?

Yes, please open a PR on your seed nodes. Thanks!
