### ISSUE TITLE
Mixed vaults may not convert their vault to DUSD-only collateral with active loans. 

### ISSUE THREAD

**Issue by misterpiggie49** [DeFiCh/ain#2890]
## Summary
- Vault users with mixed vaults cannot change their vault to DUSD-only collateral while having active loans. 

## Steps to Reproduce
- Place 1 DFI as collateral
- Place 1 DUSD any amount
- Borrow a small amount of any dToken (in this case DFI < DUSD, so DUSD cannot be borrowed)
- Attempt to remove all DFI, as if you wanted to borrow DUSD with an only-DUSD vault.
- An error is received, you cannot convert a mixed vault to DUSD-only.

## Environment
- TX or TX type on bug if applicable: OP_DEFI_TX_WITHDRAW_FROM_VAULT
- Any other relevant environment info: This occurs on the DeFiChain Light Wallet (untested on Desktop)
![IMG_0536](https://github.com/DeFiCh/ain/assets/117684008/8c749654-fd59-4a2a-aa53-6f3ef9377346)
![IMG_0537](https://github.com/DeFiCh/ain/assets/117684008/1ca5c9aa-5623-4591-84a1-41002ee7f266)

**Comment by prasannavl** [comment]
Closing. Not actionable here, as it's seems to be a wallet app issue. Not related to the chain. Please report here if there are issue in the vault mechanism on chain.
