### ISSUE TITLE
Defichain desktop wallet for windows only gets to splash screen, then stops

### ISSUE THREAD

**Issue by Ausafari** [DeFiCh/ain#2894]
## Summary

- Please help, so I can proceed!

## Steps to Reproduce

[Please use step-by bullet points to help the team reproduce the bug]
Just launch the desktop wallet - that's as far as I get.
- 
- 

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: 
- Block height on bug if applicable: 
- TX or TX type on bug if applicable:  
- OS with version: 
- Any other relevant environment info:  
- 
Windows 10 or 11

**Comment by prasannavl** [comment]
Closing. Please create an issue in the desktop wallet app. This is for the node and blockchain only. And it's not actionable here.
