### ISSUE TITLE
EVM token split: intrinsic.migrateToken does not create tokentransfers

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#2895]
## Summary

when using the migrateToken function on the intrinsic SC, it directly replaces the balances in the DST-20 contracts, but no token transfer is created. so looking at the logs, there is no trace of the split.

Better we add a burn of the old token and mint of the new token to the logs. Otherwise I guess that trackers geht confused/messed up.

see https://testnet-dmc.mydefichain.com:8444/tx/0x5292bf4eef163adff3816cb40a8d5117633f7ddf436b90bc536c984b813b2752 as an example call.

## Environment

- Node Version: 4.1.0-alpha

**Comment by prasannavl** [comment]
Thanks for this report @kuegi. This is indeed something to cleanup.  

@Jouzo is currently working on a refined iteration of the handling on the EVM layer.

**Comment by Jouzo** [comment]
Fixed in https://github.com/DeFiCh/ain/pull/2903
