### ISSUE TITLE
EVM: Deploy smart contract with salt and bytecode not possible!

### ISSUE THREAD

**Issue by Meiswinkel1991** [DeFiCh/ain#2905]
## Summary

Deploying a contract using a salt and a bytecode leads to a successful transaction. But the address of the deployed contract does not contain any bytecode after the transaction.
This means it is not possible to use the precomputed address with CREATE2. 

## Steps to Reproduce

Example:

I created a contract factory. I can also determine my future address using CREATE2, but deploying the contract doesn't work. I'll send the address of the deployed contract. This has no bytecode but events are tracked. This seems like a bug to me.

[Example contract deployed with salt and bytecode](https://blockscout.testnet.ocean.jellyfishsdk.com/address/0xe91babc7c5cd168c0ae4783e983b0c10ee9bdd2f)

The following link shows the FactoryContract. A new contract with a “salt” should be deployed in the “createWallet” function. But it doesn't work.

[Example contract of a contract factory](https://blockscout.testnet.ocean.jellyfishsdk.com/address/0xde3d321C668D3D561377F9fdd43793EAD569f34A?tab=contract)

**Comment by Jouzo** [comment]
This should work. I'll look into it.

**Comment by prasannavl** [comment]
Closing this as it indeed is possible and works as expected. 
Please feel free to open another issue in case you continue to have issues.
