### ISSUE TITLE
EVM: token transfers on stock split (upgradeToken) misses inflow

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#2909]
on 4.1.0-beta3. 

when doing a stock split on EVM, the tokentransfers contain the creation of the new token, but miss the removal of the old token.
example: https://testnet-dmc.mydefichain.com:8444/tx/0xedb21367809270dd94b61c0320d0cac213c57499a4c051f14869669cc92367b1
This converts 1 TWTR/v1 (0xff0..0a) to 10 TWTR (0xff0...01c). but tokentransfers only include the transfer of 10 TWTR.

So any tool would miss the change in balance of TWTR/v1

**Comment by Jouzo** [comment]
Good catch, the internal burn was overlooked. Should be fixed in #2911
