### ISSUE TITLE
4.1.0 defid.exe crashes on Windows

### ISSUE THREAD

**Issue by AsteraDE** [DeFiCh/ain#2914]
## Summary

- When defid.exe is started, the error message ‘Assertion failed: fs::equivalent(result, path), file /__w/ain/ain/src/util/system.cpp, line 333’ appears and the application exits

## Steps to Reproduce

- Start defid.exe

![image](https://github.com/DeFiCh/ain/assets/9354836/bf366496-6fb0-4ef0-99c3-032ac921b015)

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: 4.1.0
- Block height on bug if applicable: 
- TX or TX type on bug if applicable:  
- OS with version: Windows 11 and Windows Server 2022
- Any other relevant environment info:

**Comment by AsteraDE** [comment]
thanks for your quick response. it looks a little better now, but crashes at a different point:

![image](https://github.com/DeFiCh/ain/assets/9354836/31fe6db7-870a-4661-855a-9a5725e21568)

**Comment by bernd-mack** [comment]
> Thanks for the report. The Windows binaries on the release have been updated. Please download the binaries again.

Works on Win 11 with 48GB Ram 
but defid.exe is pretty big in relation to the other versions :)
<img width="473" alt="image" src="https://github.com/DeFiCh/ain/assets/76614620/14bfbe42-86ba-48e4-945d-2ddeeedd0ff6">

**Comment by AsteraDE** [comment]
I have now tested it again.
If I call the defid.exe without parameters, it works.

With the parameter -conf=<path to defid.conf> the node crashes

**Comment by bernd-mack** [comment]
i use a shortcut to start it with extra config:
"C:\Program Files\DeFi Wallet\resources\bin\win\defid.exe" -conf="C:\Users\bmack\.defi\defi.conf"
has anyone else tested it?

**Comment by Bushstar** [comment]
Will resolve the other issue with .conf files which may already be fixed due to subsequent work in the PR and will strip debug info from the binary before uploading to reduce size.

**Comment by Bushstar** [comment]
This does appear to be already fixed. I've uploaded newer smaller binaries to the release page, they uploaded quicker today, thought they took a while yesterday!
