### ISSUE TITLE
-ascendingstaketime should be enforced when v0/params/feature/ascending_block_time is active

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/ain#3040]
## Summary

currently, the miner needs to explicitly set `ascendingstaketime` to only mine blocks with ascending time. But when the attribute is active, other blocks are rejected by the network. So it makes no sense to not have it active -> node should automatically behave as if the flag is set, when the attribute is active.

**Comment by prasannavl** [comment]
Fixed by https://github.com/DeFiCh/ain/pull/3041
