### ISSUE TITLE
Defid terminating with Out of memory error

### ISSUE THREAD

**Issue by jha749** [DeFiCh/ain#322]
#### What happened:
During syncing (e.g. syncing starting from the last, freshly downloaded snapshot), defid stops with a memory error, e.g.:
```
2021-04-07T07:31:07Z UpdateTip: new best=4e346808358efc5ff8692d2dabb7ff6c9afcbd8ba4bc5d92eb71a60c619a7125 height=755334 version=0x20000000 log2_work=79.977349 tx=2172395 date='2021-04-03T23:34:31Z' progress=0.976186 cache=1.1MiB(9187txo)
2021-04-07T07:31:19Z Error: Out of memory. Terminating.
terminate called without an active exception
```
I'm running on a Raspberry Pi 4 8GB ram and memory usage is nowhere near 100% (more like 10%). See also my initial thread here with more context: https://www.reddit.com/r/defiblockchain/comments/mlza60/memory_errors_during_sync_of_node_since_162_how/
It always terminates after approximately the same amount of blocks, but it's not always the same block. The cache is only increasing from startup (never resets to 0).

I tried several things, but to no avail:
* increasing memory (with `-maxmempool=600 -dbcache=900`) (it still goes out of memory, but at a later stage)
* compiling the last version (1.6.3) directly on my Pi
* cross compiling from my Windows laptop

When I manually quit defid before the error normally occurs, it does terminate correctly and saves the syncing progress. I have been able to successfully sync it up to 100% by just quitting and restarting defid every 20 mins or so.

#### What you expected to happen:
Defid to keep running

#### How to reproduce it (as minimally and precisely as possible):
Download source 1.6.3, (cross) compile it for linux/arm/v7 (aka arm-linux-gnueabihf), add compiled binary to a Ubuntu 20.10 docker image (debian 10 doesn't work on ARM as it gives a glibc version error, that it should be newer than 2.29), and run.

#### What are your environment parameters:
Raspberry Pi 4 8GB with latest version of Raspberry Pi OS running (32-bit), WD elements external HDD
Latest docker version, using Ubuntu 20.10 as base image.

I know at least one other person with slightly different configuration having the same issue.

#### Anything else we need to know?:
The debug.log does not contain any more information than the error message above. I'm willing to do more research but I don't really know where to start, so any pointers what I can do to get more descriptive error messages are welcome.

Edit: corrected guest OS version (Ubuntu 20.10)

**Comment by jha749** [comment]
> > increasing memory (with -maxmempool=600 -dbcache=900)
> 
> You should minimize cache storage (cache means to use more memory)

True, my hunch was to give it more memory to work with, but I will try the opposite case as well, will let you know when I did.

> Can you try running 32 bits in Docker as well? 32 bits is not often tested.

What do you mean exactly? Using a different guest OS? So my host OS is Raspberry Pi OS, which is 32-bit. My guest OS (base image for docker) is Ubuntu 20.10 (for arm), that is probably 64 bit. You mean picking a docker base image for a 32 bit linux distro? Will try to find one :)

I'm not sure if it's 64bit vs 32bit related though - another user on Reddit I spoke to has the same problem, but he's running 64 bit host OS on the Pi4.

**Comment by bvbfan** [comment]
> You mean picking a docker base image for a 32 bit linux distro?

You don't need new image, you can use 32 bit compiler, but if finding image is easier. So another one can be endianness or musl vs glibc.

**Comment by jha749** [comment]
> You don't need new image, you can use 32 bit compiler, but if finding image is easier. So another one can be endianness or musl vs glibc.

Afraid I'd need some help here, my knowledge goes as far as knowing there is musl vs glibc (believe musl is what Alpine uses), but wouldn't really know how to compile with different compiler. Wouldn't that require rewriting parts of the Makefile? Any pointers you can give?

Am I correct in believing that when I followed the instructions for cross compiling for armhf, it compiles 32bit?

My other thought is that the Bitcoin client seems to be running just fine on Raspberry Pis in a docker container, so shouldn't be too difficult.

Alright, what I will try more:
* Running with decreased memory using the flags
* Running the compiled binaries directly on the host os (to check whether it's a docker issue)
* Compiling using another compiler (would need help here)
* Check if compiling Bitcoin client for ARM using the same setup works, if yes, investigate differences

**Comment by jha749** [comment]
Update:
Other user I referred to earlier also was using 32bit host OS when his problems occurred, so it could be 32bit related after all. We're both running with lower memory setting using the flags (in my case `-maxmempool=150 -dbcache=225`) and so far no memory errors yet. Have been running a few hours now, will keep watching it.

**Comment by crypto-r** [comment]
My Docker Container runs perfect since 1 week with defid 1.6.3 with the flags `-maxmempool=64 -dbcache=128` on a Raspberry 400 with Raspbian buster

**Comment by benzmuircroft** [comment]
On Ubuntu 20 dedicated server I am also having this issue every time I try to load blocks it stays on for about 15-30 seconds and dies
