### ISSUE TITLE
void CChainState::PruneBlockIndexCandidates(): Assertion `!setBlockIndexCandidates.empty()' failed.

### ISSUE THREAD

**Issue by benzmuircroft** [DeFiCh/ain#342]
#### What happened:

I started the daemon for the first time

defid: validation.cpp:2943: void CChainState::PruneBlockIndexCandidates(): Assertion `!setBlockIndexCandidates.empty()' failed.

then I use -reindex and the same thing happens.

#### What you expected to happen:

Load blockchain and be awesome

#### How to reproduce it (as minimally and precisely as possible):

my defi.conf
```
rpcuser=xxx
rpcpassword=xxx

prune=0
txindex=1

maxconnections=100
port=8555
rpcport=8554
listen=1

datadir=/home/xxx/disk/DFI/data

walletnotify=node /home/xxx/disk/DFI/tx.js %s
blocknotify=node /home/xxx/disk/DFI/block.js %s

addnode=185.244.194.174:8555
addnode=45.157.177.82:8555
```
#### What are your environment parameters:
raspberry pi 4 
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

**Comment by benzmuircroft** [comment]
anyone alive on this project?

**Comment by bvbfan** [comment]
Somehow you end-up with corrupt data. You still experience same issue? It's very unlikely to happen.

**Comment by benzmuircroft** [comment]
@bvbfan It is a fresh install and it does it every time

maybe it is this `prune=0`

**Comment by bvbfan** [comment]
The default of prune is 0, you can remove it. Make sure you clean the data dir `/home/xxx/disk/DFI/data`

**Comment by sandrich** [comment]
same issue in testnet with 1.7.2 and 1.7.3

**Comment by jha749** [comment]
I've seen this as well on my Pi4. For me it would start with an out of memory error though, if I'd restart after such an error sometimes the data would be corrupt and I would get this error.

Can it be that your error was also after an out of memory error? I've been running relatively stable on the Pi with `-maxmempool=64 -dbcache=128` flags added to defid command. I'd advise to try those flags (after you cleaned the data dir) and see if it keeps running ok.

See also my thread on Reddit [here](https://www.reddit.com/r/defiblockchain/comments/nsuo2d/raspberry_pi_arm_docker_images_now_on_available/) about running Defichain on the Pi where this same error popped up with another user.

**Comment by Bushstar** [comment]
This issue will occur if the node shuts down unexpectedly and results in an inconsistent state, the only solution is to reindex.
