### ISSUE TITLE
On-Chain Governance

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/ain#344]
#### What would you like to be added:

Refer to the Pinkpaper for implementation details: https://github.com/DeFiCh/pinkpaper/tree/main/governance

#### Why is this needed:

An on-chain governance system allows us to approve DFIPs (DeFiChain Improvement Proposals) in a decentralised manner.

**Comment by monstrobishi** [comment]
Provide adequate getter methods to be able to gather info and display on a companion website similar to https://www.dashcentral.org/budget

**Comment by Jouzo** [comment]
Addressed in PR:
https://github.com/DeFiCh/ain/pull/870
https://github.com/DeFiCh/ain/pull/1441
https://github.com/DeFiCh/ain/pull/1535
