### ISSUE TITLE
Include account system changes in block merkle root

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/ain#349]
#### What would you like to be added:

Include account system changes in block merkle root, by calculating the entire account state, hashing it and including it as part of the merkle root.

#### Why is this needed:

Account system state is not currently enforced strongly by the information in the block, encoding the account state as part of the merkle root ensures that account changes are reflected and strongly enforced at every block.

**Comment by uzyn** [comment]
Done with #337
