### ISSUE TITLE
Block, on consensus, any attempts at spending from burn address.

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/ain#352]
#### What would you like to be added:

Block, on consensus, any attempts at spending from burn address.

Burn address being `8defichainBurnAddressXXXXXXXdRQkSm`

#### Why is this needed:

Currently the burn address for mainnet is set as `8defichainBurnAddressXXXXXXXdRQkSm`. 

While it is technically improbable that the private key is known for the address, it is unprovable that the private key does not exist.

This consensus change it to block any attempts at spending it, _even_ if the private key is known.

Also related: https://github.com/DeFiCh/ain/issues/347

**Comment by Bushstar** [comment]
Spending from the burn address is prevented in 1.7.x.

https://github.com/DeFiCh/ain/pull/354/commits/4fa84b22cb94b202df11b49b1ccfedbafb80e101#diff-97c3a52bc5fad452d82670a7fd291800bae20c7bc35bb82686c2c0a4ea7b5b98R1411
