### ISSUE TITLE
Behavior of maxPrice is different for testpoolswap & poolswap

### ISSUE THREAD

**Issue by Sebz84** [DeFiCh/ain#353]
#### What happened:

When calling testpoolswap & poolswap, the maxPrice parameter behaves differently between the commands.
In testpoolswap the maxPrice seems to be defined by amountTo /  amountFrom. But sometimes it is also amountFrom /  amountTo.

**1. testpoolswap called with maxPrice=0.075422 ** 

defi-cli testpoolswap {\"from\":\"...\",\"tokenFrom\":\"DOGE\",\"amountFrom\":\"5534.511049\",\"to\":\"...\",\"tokenTo\":\"DFI\",\"maxPrice\":\"**0.075422**\"}
**413.57428279@0**

**2. Afterwards poolswap is called with maxPrice=0.075422 -> Fails**

defi-cli poolswap {\"from\":\"...\",\"tokenFrom\":\"DOGE\",\"amountFrom\":\"5534.511049\",\"to\":\"...\",\"tokenTo\":\"DFI\",\"maxPrice\":\"**0.075422**\"}
error code: -32600
error message:
Execution test failed:
ApplyPoolSwapTx: Price is higher than indicated.

**3. If poolswap is called with the DFI/DOGE price, maxPrice=13.375422 -> It works**

defi-cli poolswap {\"from\":\"...\",\"tokenFrom\":\"DOGE\",\"amountFrom\":\"5534.511049\",\"to\":\"...\",\"tokenTo\":\"DFI\",\"maxPrice\":\"**13.375422**\"}
6d72d9ca81c6xxxab18bef4ee0fbxxxx28a755f03dffa0c779xxxexxxx55xxxx

#### What you expected to happen:

The definition of maxPrice shall be always the same for all commands.

#### How to reproduce it (as minimally and precisely as possible):

Defichain release 1.6.3
See commands above.

**Comment by Bushstar** [comment]
Tested this locally and found the testpoolswap will give the same error, the price could have changed slightly on new blocks. If the max price was raised slightly I suspect on the failing call I suspect it should have gone through, or if left as is failed when testing with testpoolswap again. amountTo / amountFrom does appear to be the correct calculation.

**Comment by uzyn** [comment]
Closing this as it appears to not be a bug. 

Please reopen it if it is.
