### ISSUE TITLE
CI to build and push a docker image continuously at each PR

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/ain#362]
#### What would you like to be added:

Currently, a docker image is created and pushed on each release.
Jellyfish uses a docker container for hyper parallelized testing. Where multiple containers are spun up continuously for testing. It would be great if each PR in `DeFiCh/ain` creates a docker image and we can use that for testing.

This allows:
1. Building features in jellyfish quickly before the official `DeFiCh/ain` release
2. Write bindings and test once in jellyfish and have it as part of jellyfish package on day one
3. Testing binary compatibility with jellyfish before release
4. Use jellyfish CI process

This cannot be done with the GitHub container registry currently due to current limitations unless we use a `PAT` (should we should not). However, we could push to docker hub with the commit hash.

#### For reference

https://github.com/DeFiCh/jellyfish/blob/db95cd03fe85a6b395472214631da14c1ade58a2/packages/testcontainers/src/chains/container.ts#L95

**Comment by monstrobishi** [comment]
@fuxingloh 

Dev build now pushes to Dockerhub, see here: https://hub.docker.com/layers/defi/defichain/HEAD-52c9372/images/sha256-8cb43b65d0e6e6e7da4969d5c9a8c6bd18b8472b11f57b5d5d4f3dc897d5aeb3?context=explore

PR: https://github.com/DeFiCh/ain/pull/363
