### ISSUE TITLE
Proper hardfork transition to follow with the magic header numbers upgrade

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/ain#37]
https://github.com/DeFiCh/ain/pull/36 updates the header numbers for a security audit that is conducted and it would break the compatibility of the node with the current state of DeFiChain mainnet.

Hardfork mechanism needs to be implemented to properly transition to the new header numbers.

**Comment by uzyn** [comment]
Tasks:

- [ ] Parse: accepts both old and new magic numbers.
- [ ] Comm emission: sends out old numbers if before HF block; sends out new numbers if >= HF block

**Comment by monstrobishi** [comment]
As this change is to the network level protocol, I propose that block height is not used to determine whether we send the old or new magic header version. Instead, we control the release over 3 iterations, and ensure everyone has had enough time to upgrade before pushing a final release that only accepts the new magic headers.

This would make the tasks look like:

- [ ] Release one: accepts both old and new magic numbers, sends out old numbers
- [ ] Next HF, Release two: accepts both old and new magic numbers, sends out new numbers
- [ ] Next HF, Release three: accepts only new magic numbers, sends out new numbers

Let me know your thoughts
