### ISSUE TITLE
Prevent crashes when crafting custom tx on interchain exchange

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/ain#374]
#### What happened:

It's possible to crash interchain exchange code by passing in a custom tx with invalid token id and other invalid parameters.

#### What you expected to happen:

Doesn't crash, tx should be rejected.

**Comment by uzyn** [comment]
Fixed as part of commit of #335 https://github.com/DeFiCh/ain/commit/147be8ef8b25351ff04d9e4585ae761ab416854e
