### ISSUE TITLE
Increase difficulty adjustment period

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/ain#375]
Increase difficulty adjustmnet period to greater than the current one.

Something like 10 hours would be acceptable.

**Comment by bernd-mack** [comment]
We have already given some thought to this. It was some time ago. But certainly helps in the discussion of the appropriate adjustment period of the difficulty.
[20210317_DefiChain_Blocktime.pdf](https://github.com/DeFiCh/ain/files/6451217/20210317_DefiChain_Blocktime.pdf)
