### ISSUE TITLE
Refactor std::set usage in RPC calls

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/ain#402]
#### What happened:

When RPC calls use a std::set to construct custom tx meta data it can cause a difference in expected output. An RPC called with:
```
[
    {
      token: 'TESLA',
      currency: 'USD'
    },
    {
      token: 'TESLA',
      currency: 'EUR'
    }
  ]
```

Becomes:
```
[
    {
      token: 'TESLA',
      currency: 'EUR'
    },
    {
      token: 'TESLA',
      currency: 'USD'
    }
  ]
```

Refer to:
```
std::set<CTokenCurrencyPair> availablePairs;
```

#### What you expected to happen:

This can be replaced with std::vector or any standard array type implementation.

**Comment by fuxingloh** [comment]
`JSON` specification is not friendly with `Set` due to its varying order structure. I recommend the use of list/array.
