### ISSUE TITLE
Synchronizing 0%

### ISSUE THREAD

**Issue by ChingN** [DeFiCh/ain#406]
#### What are your environment parameters:
What type of machine are you observing the error on (OS/CPU and disk type)? Windows 10 Pro 64-bit, Intel Core m3 0.90 GHz, SSD.

**Comment by uzyn** [comment]
Try on another machine or network. The blockchain has no syncing issues. Or try to ask in Telegram for troubleshooting. 

Closing this as it's not a bug.
