### ISSUE TITLE
Concurrent spend of token may result in local double spending of the same token balance at wallet level (non-security concern)

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/ain#407]
#### What happened:

Rapidly sending of token from the same address may occasionally result in the same token balance being spent twice at wallet.

Resulting in 1 of the transactions encountering `ApplyAccountToTAccountTx amount XXX is less than XXX (code 16)` error.

#### What you expected to happen:

Only the first spend should be selected, regardless if it has been confirmed on the blockchain or not yet.

Same behavior as UTXO `sendtoaddress`

#### How to reproduce it (as minimally and precisely as possible):

Not very reliably by hand, but it occurs a lot on an automated system rapidly calling `accounttoaccount`.

One of the stuck transaction might get stuck and resending it would result in the following:

```sh
$ defi-cli sendrawtransaction XXXXXXXXXXXXXXX
error code: -26
error message:
ApplyAccountToAccountTx: amount 0.00000000 is less than 2.00000000 (code 16)
``` 

#### What are your environment parameters:
Linux

**Comment by Bushstar** [comment]
This issue should have been resolved by the following PR https://github.com/DeFiCh/ain/pull/517
