### ISSUE TITLE
Prometheus exporter

### ISSUE THREAD

**Issue by sandrich** [DeFiCh/ain#413]
#### What would you like to be added:
Create a prometheus exporter for metrics and monitoring. Typically exporter listens on /metrics

#### Why is this needed:
Prometheus is a very common time series database that can scrape exported content from servers. This is very handy for monitoring and alerting (Alertmanager) purposes but also to do advanced queries for graphing and statistics.

I am happy to do the implementation if there is interest in such a functionality

An alternative is a completely separate service that can be installed outside of this project.

**Comment by uzyn** [comment]
Thanks for your suggestion. This would not be a request for blockchain and can be implemented separately as an integration.

Closing your ticket. Thanks.
