### ISSUE TITLE
I suggest caching of GetMasternodeLastBlockTime

### ISSUE THREAD

**Issue by muirglacier** [DeFiCh/ain#427]
#### What would you like to be added:

GetMasternodeLastBlockTime() in the worst case loops through all master nodes, with each causing a DB lookup.
I suggest caching the lastBlockTime of each nodeId (and updating the cache in the "increment/decrement minted blocks" function)

#### Why is this needed:

When you have many master nodes running on one client, things get really slow. Each second, for each local masternode, big chunks of the DB are queried in the for-loop in GetMasternodeLastBlockTime() in order to compute the stakerBlockTime.
This not only causes a high CPU load but the last local master node in your list has a time disadvantage due to the delay in all stakerBlockTimes that had to be previously computed.

Also, the listmasternodes RPC command becomes a lot quicker. I have added the cache in my local defid and listmasternodes went from around 5 seconds down to 0.48 seconds.

**Comment by uzyn** [comment]
Thanks for this @muirglacier 

> I have added the cache in my local defid and listmasternodes went from around 5 seconds down to 0.48 seconds.

Would you like to submit a PR for this improvement?
