### ISSUE TITLE
Wrong targetMultiplier RPC-output

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/ain#437]
#### What happened:
listmasternodes show the actual TargetMultiplier of the Masternodes. With Version 1.6.4 all is fine, with Version 1.7.0 all Masternodes has value=1.

#### What you expected to happen:
Show the correct(?) Targetmultiplier-Value.

#### How to reproduce it (as minimally and precisely as possible):
~/.defi/defi-cli listmasternodes | grep -A 3 ENABLED | grep 'targetMultiplier":'

#### What are your environment parameters:
Debian 10 with new AIN 1.7.0, fresh reindex.

**Comment by uzyn** [comment]
Thanks @Stonygan Seems like a bug to be. @Bushstar please look into this one.

**Comment by uzyn** [comment]
Addressed with #434
