### ISSUE TITLE
some fields are not updated on `UpdateToken/UpdateTokenAny`

### ISSUE THREAD

**Issue by canonbrother** [DeFiCh/ain#440]
#### What happened:
Value is not updated after modified

## `UpdateToken`
- [ ] isDAT

## `UpdateTokenAny`
- [ ] finalized
- [ ] colleteralAddress
- [ ] creationTx
- [ ] isLPS

Note: Mark **DONE** or **REMOVE** as well if the field is immutable here via cmd.

eg: 
`UpdateToken` - isDAT
![updatetoken-bug](https://user-images.githubusercontent.com/8097901/119802522-2faabd00-bf11-11eb-986c-c75de50cfe57.png)

`UpdateTokenAny` - finalized
![image](https://user-images.githubusercontent.com/8097901/119801949-b6ab6580-bf10-11eb-95cd-6e58e770f5f0.png)

**Comment by Bushstar** [comment]
@canonbrother the behaviour you report is consistent when the block height is below the Bayfront hard fork height. For regtest this can be set with bayfrontheight in defi.conf. I updated `test/functional/feature_tokens_dat.py` with the code in the link below to test the issues you reported.

https://gist.github.com/Bushstar/6d5169176a9a5719044fd8fbad32df36

You can update the text in that test and run it as follows.

`./test/functional/test_runner.py feature_tokens_dat.py`

This my output.
```
./test/functional/test_runner.py feature_tokens_dat.py
Temporary test directory at /tmp/test_runner_₿_🏃_20210602_092811
WARNING! There is already a defid process running on this system. Tests may fail unexpectedly due to resource contention!
Remaining jobs: [feature_tokens_dat.py]
1/1 - feature_tokens_dat.py passed, Duration: 1 s

TEST                  | STATUS    | DURATION

feature_tokens_dat.py | ✓ Passed  | 1 s

ALL                   | ✓ Passed  | 1 s (accumulated) 
Runtime: 1 s
```
I find the Python functional test framework very useful for testing DeFi and even sharing issues.
