### ISSUE TITLE
icx_listorders does not show the offers to an order

### ISSUE THREAD

**Issue by Sebz84** [DeFiCh/ain#479]
#### What happened:

I did the following steps:

-> Created an order on mainnet via icx_listorders
-> Created an offer for the order via icx_makeoffer 
-> Polled icx_listorders to find out if there is an offer (as described in https://github.com/DeFiCh/ain/wiki/Interchain-Exchange-Tutorial)

Unfortunately icx_listorders does not show the offer.
I am not sure if this is an user error or a bug. 
Can someone give me a hint how to find out if there is an offer for an order?

#### What you expected to happen:

icx_listorders should show when an offer was made for an order.

#### How to reproduce it (as minimally and precisely as possible):

./defi-cli icx_createorder "{\"tokenTo\":\"LTC\",\"chainFrom\":\"BTC\",\"ownerAddress\":\"dazewCkFnaw4o67RQrS5FATMKy9mAcohNA\",\"amountFrom\":0.0001,\"orderPrice\":200.0,\"expiry\":2900}"
{
  "WARNING": "ICX and Atomic Swap are experimental features. You might end up losing your funds. USE IT AT YOUR OWN RISK.",
  "txid": "7baf50c0c1da103ae761d739229b2bd9f096ab46f6fe70a54369114d57eaeae7"
}

./defi-cli icx_listorders
{
  "WARNING": "ICX and Atomic Swap are experimental features. You might end up losing your funds. USE IT AT YOUR OWN RISK.",
  "7baf50c0c1da103ae761d739229b2bd9f096ab46f6fe70a54369114d57eaeae7": {
    "status": "OPEN",
    "type": "EXTERNAL",
    "chainFrom": "BTC",
    "tokenTo": "LTC",
    "ownerAddress": "dazewCkFnaw4o67RQrS5FATMKy9mAcohNA",
    "amountFrom": 0.00010000,
    "amountToFill": 0.00010000,
    "orderPrice": 200.00000000,
    "amountToFillInToAsset": 0.02000000,
    "height": 894049,
    "expireHeight": 896949
  }
}

./defi-cli spv_getaddresspubkey "bc1qq70k0em5tut0p9w4c8yxaftkurg2vc9k0xpl70"
02b8809fadb42a115069deec1e84095d4cf3a7e5a2042c64032f0f8af7bc3a07ce

./defi-cli icx_makeoffer "{\"orderTx\":\"7baf50c0c1da103ae761d739229b2bd9f096ab46f6fe70a54369114d57eaeae7\",\"amount\":0.0001,\"receivePubkey\":\"02b8809fadb42a115069deec1e84095d4cf3a7e5a2042c64032f0f8af7bc3a07ce\",\"ownerAddress\":\"dazewCkFnaw4o67RQrS5FATMKy9mAcohNA\"}"
{
  "WARNING": "ICX and Atomic Swap are experimental features. You might end up losing your funds. USE IT AT YOUR OWN RISK.",
  "txid": "09a6b85bb283e35e82f56837c50289173523f16463b2e0c2151dfa1951141aaf"
}

./defi-cli icx_listorders
{
  "WARNING": "ICX and Atomic Swap are experimental features. You might end up losing your funds. USE IT AT YOUR OWN RISK.",
  "7baf50c0c1da103ae761d739229b2bd9f096ab46f6fe70a54369114d57eaeae7": {
    "status": "OPEN",
    "type": "EXTERNAL",
    "chainFrom": "BTC",
    "tokenTo": "LTC",
    "ownerAddress": "dazewCkFnaw4o67RQrS5FATMKy9mAcohNA",
    "amountFrom": 0.00010000,
    "amountToFill": 0.00010000,
    "orderPrice": 200.00000000,
    "amountToFillInToAsset": 0.02000000,
    "height": 894049,
    "expireHeight": 896949
  }

***I would expect the offer to show up here, or alternatively have another CLI command to list the offers***

}

#### What are your environment parameters:
ain v1.7.4
Mainnet

**Comment by Mixa84** [comment]
icx_listorders when called without parameters shows open orders, if you want to see offers for specific order then it must be called with txid of the order: `icx_listorders '{"orderTx":"8819f37b222559a9164fbc4722da29ad05b84d52fa0ba7c2123a7dbf448f566c"}'`
