### ISSUE TITLE
ERROR: ConnectTip: ConnectBlock after 2.4.3 upgrade.

### ISSUE THREAD

**Issue by itmlgife** [DeFiCh/ain#484]
#### What happened:
This is on a Mac.

In preparation for the Eunos upgrade I have upgraded the DeFiChain app to 2.4.0 (on May 30th) then 2.4.1 (on June 1st) and today to 2.4.3.

2.4.1 worked just fine. After the upgrade to 2.4.3 the blockchain is not syncing. I get an error in the bin.log file that looks like 

2021-06-03T19:50:42Z ERROR: ConnectTip: ConnectBlock e42e16febb779aa817eb93c8a06466f1aa387af03d74d4803c4c4bc76b42c4ab failed, bad-txnmrklroot, hashMerkleRoot mismatch (code 16)
2021-06-03T19:50:42Z InvalidChainFound: invalid block=e42e16febb779aa817eb93c8a06466f1aa387af03d74d4803c4c4bc76b42c4ab  height=894001  log2_work=81.054922  date=2021-06-03T13:24:16Z
2021-06-03T19:50:42Z InvalidChainFound:  current best=ac416c3b0f3d849b05137c9e4338d83b1581c522b452e1924f5b49171369ed21  height=894000  log2_work=81.054919  date=2021-06-03T13:24:22Z

In addition:
- the defiid process is constantly 100% from when the app starts
- the debug.log file grows constantly adding error messages that look the same as what is in the bin.log, but it gets repeated every second so the debug.log is growing constantly because of this.

#### What you expected to happen:
I expected the upgrade to happen smoothly and the wallet to sync with the blockchain. I expected that since I did upgrade to 2.4.1 before block 

#### How to reproduce it (as minimally and precisely as possible):
I am not sure I can reproduce it. I would need to try. 

#### What are your environment parameters:
My system is a MacMini with an M1 processor and 0.5 TB of storage.
The version of the App that I had already installed, was 2.4.1 and I was upgrading to 2.4.3

#### Anything else we need to know?:
Through a suggestion from Bernd Mack from DeFiChain telegram, I tried invalidating 894000 block but the system just hanged when I ran the invalidateblock command in the command line utility.

**Comment by itmlgife** [comment]
Hello, I wanted to share additional information related to the problem I have opened a ticket for.

Following the suggestion from Bernd Mack I synced the blockchain starting from the snapshot and I was able to get the App to work and synchronize. After having done that, after a period of time, the Application stopped syncing and actually hung again.

When I checked the debug.log I found again similar error messages as reported in the prior message.

I am uploading 2 debug.log files, one before a restart of the App and one after the App restart.

The first log [debug-03-01.zip] is from before the restart. The second log [debug-03-02.zip] is from after the restart.
Please note that during the restart I have deleted to ensure it was as clean as possible.

I hope this helps the triage and the investigation.
[debug-03-02.zip](https://github.com/DeFiCh/ain/files/6595219/debug-03-02.zip)
[debug-03-01.zip](https://github.com/DeFiCh/ain/files/6595220/debug-03-01.zip)

**Comment by supervolot** [comment]
I got my servers live again. I delete the SPV=0 line in the defi.conf

**Comment by itmlgife** [comment]
Hi, I saw that a new version of the app has been released and it sounds like it resolves the issues indicated in this ticket: blockchain in a loop having issues with merkelroot.

I am currently upgrading and synchronizing from a snapshot. Windows version of the app seems to be good. Mac is still in progress. If things go well, I think this ticket could be closed.
