### ISSUE TITLE
Add Pool Liquidity not displaying, transaction stuck unconfirmed on explorer

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/ain#501]
#### What happened:
Users are reporting that they're adding `addPoolLiquidity`, it doesn't return any response. One user reported that transaction is stuck as unconfirmed in the explorer.

For more details:
https://github.com/DeFiCh/app/issues/925
https://github.com/DeFiCh/app/issues/933

**Comment by seb18781** [comment]
I would like to queue my issue, cuz I think it is linked. DeFiCh/app#943
