### ISSUE TITLE
`listprices` RPC documentation inaccurate

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/ain#510]
#### What happened:

`listprices` says:

```
                       "                  `ok` - validity flag,\n"
                       "                  `msg` - optional - if ok is `false`, contains reason\n"
                       "                   possible reasons for a price result to be invalid:"
                       "                   1. if there are no live oracles which meet specified request.\n"
                       "                   2. Sum of the weight of live oracles is zero.\n"
```

This is wrong, actually `ok` is set to true if there are no errors, otherwise `ok` is filled with the error message. `msg` is never populated.

#### What you expected to happen:
Update the docs.

#### How to reproduce it (as minimally and precisely as possible):

`defi-cli listprices`

**Comment by hidiego** [comment]
This will be fixed in #512
