### ISSUE TITLE
Pagination for `listoracles`, `listlatestrawprices ` and `listprices`

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/ain#512]
#### What would you like to be added:

Pagination for `listoracles` and `listprices`, should look something like:

```
  start: 0,
  including_start: true,
  limit: 1
```

#### Why is this needed:

The list might grow substantially especially for list prices, frontends will want to pull one page at a time.

**Comment by jingyi2811** [comment]
I would like to request pagination features to be added to

listOracles
**listlatestrawprices**
listPrices

I agree that listOracles missing pagination is not so bad. 
But in my code, I plan to combine listoracles and getOracleData(id) together

**Comment by jingyi2811** [comment]
For all the 9 Oracle rpcs, I would recommend adding another key named id. Its value should be a sequential number from 1..n (Like a primary key of a database table)

For the 3 Oracle rpcs that require pagination to be added. I would recommend the following sorting rules

listoracles - sort by the date when you create the oracle
llistlatestrawprices - sort by token+'-'+currency. If there are 2 records that have the same token and currency, sort by timestamps of the oracle
listprices - sort by token+'-'+currency (edited)

**Comment by jingyi2811** [comment]
I think we can omit `including_start`, `start` and `limit` only is good enough
