### ISSUE TITLE
Add hashes per second to `getmininginfo`

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/ain#523]
#### What would you like to be added:

Add hashes per second to `getmininginfo`, would be handy to see how many hashes the node is attempting per second

#### Why is this needed:

Looking at the logs is cumbersome

**Comment by monstrobishi** [comment]
This is more relevant for multi-miners, can also show out of total miners e.g. `19/20` hashes per second

**Comment by uzyn** [comment]
Thanks. This will be a useful QoL improvement.

Take note though that on new block found, the hash rate required to mine optimally is much higher than 1 hash per second per node.

Also this is external of the node, in order for the node to gain this insight, more analytical data has to be collected. It should ideally be done externally. See: https://github.com/DeFiCh/ain/wiki/How-to-check-that-your-masternode-is-mining-fine

**Comment by uzyn** [comment]
`getmininginfo` now shows the last attempt timestamp. It can be used to tell if a miner is efficient. 

Closing this as the node can't effectively track mining rate and is out of scope for node. It could be a separate tool to track it.

Thanks for the suggestion @monstrobishi
