### ISSUE TITLE
Incorrect Syntax getmasternodeblocks?

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/ain#536]
#### What happened:
defi-cli getmasternodeblocks returns Method not found or JSON value is not an object as expected, although Syntax from help is used.
getmasternodeblocks {"operatorAddress":"xxxxx"} - Error
getmasternodeblocks {"ownerAddress":"xxxxx"} - Error

#### What you expected to happen:
Return the blocks from the Masternode.

#### How to reproduce it (as minimally and precisely as possible):
Try to get masternodeblocks from defi-cli getmasternodeblocks

#### What are your environment parameters:
Debian 10, AIN 1.7.10

#### Anything else we need to know?:
APP syntax works, but wrong output. See https://github.com/DeFiCh/app/issues/966

**Comment by Bushstar** [comment]
@Stonygan when calling getmasternodeblocks use single quotes as follows, I'll update the help text for this.

`getmasternodeblocks '{"ownerAddress":"xxxxx"}'`

**Comment by Stonygan** [comment]
That works, thx, great.
Output is the same as in https://github.com/DeFiCh/app/issues/966
It listed the block of the creation of the MN, too. I think thats not correct.
