### ISSUE TITLE
getaccount API third parameter indexed_amounts always report error 

### ISSUE THREAD

**Issue by ShengguangXiao** [DeFiCh/ain#54]
Below API call already report parameter is not a valid json value.

```
./src/defi-cli -testnet getaccount 76a91417c6c6844421f0bd738cd2971305852fc82b03c988ac "{}" true
```

**Comment by monstrobishi** [comment]
@saurabh391 you managed to get this working right

**Comment by shengguang-blockone** [comment]
Don't input the third parameter will work

**Comment by ShengguangXiao** [comment]
Don't input the third parameter will work.

**Comment by ShengguangXiao** [comment]
fixed in PR https://github.com/DeFiCh/ain/pull/55
