### ISSUE TITLE
syncronisation stuck at 894000

### ISSUE THREAD

**Issue by kxkxkx111** [DeFiCh/ain#544]
Hello Guys,
i try to install a masternode on Debian 10 VPS.
After i installed the masternode, i started to syncro the blocks and it stuck all the time at the block 894000.
I also updated the defichain to 1.7.10 but it still dont work.
please help me!

Best Regards,
kxkx

**Comment by Bushstar** [comment]
@kxkxkx111 please install version 1.7.11 which fixes this issue.

https://github.com/DeFiCh/ain/releases/tag/v1.7.11

However the block it is stuck on might be considered invalid, if you open the end of the debug.log and look for the invalid block you can tell the node to reconsider it with the reconsiderblock RPC call. Alternatively you use the snapshot in the release linked above to sync the client. Copy the contents of the snapshot into your DeFichain data directory.
