### ISSUE TITLE
Wallet synchronisation stucks at Block 878369

### ISSUE THREAD

**Issue by MaReCoding** [DeFiCh/ain#549]
#### Actual behavior:
I started syncing from scratch with "checkpoints=0" in the config file to get the full transaction history back. Now, the sync stucks at block 878369 because it seems, the Block 878370 is invalid

#### Expected behavior:
I expect a smooth synch to the actual block

#### How to reproduce it (as minimally and precisely as possible):
Start reindex with "checkpoints=0" in the Defi.conf file.

#### What are your environment parameters?

- DeFi Wallet Version: 2.5.1
- Operating System (OS): macOS Big Sur
– Current free storage capacity: 250GB

#### Anything else we need to know?
The debug.log shows the current line:
2021-06-16T16:05:15Z ERROR: AcceptBlockHeader: block 047dfbe60b6622a7290a418aa16b2dfeef4c24dd636d48424b682b95421f4561 is marked invalid

Thereafter, the cpu load of the defid process goes to zero and nothing happens anymore.

**Comment by gamsterx** [comment]
@izzycsy

As I wrote before `1.7.10` threw an exception at block 878369/878370  (see my provided logs) and corrupted the database. So I can't test `reconsiderblock` right now.

 I'm currently reindexing with `1.7.11`. Will update this issue if I have more info.

**Comment by MaReCoding** [comment]
@izzycsy: Thanks for your tip!
Because normally I use the wallet, I tried the (pre-release) version 2.5.2 of the wallet (this contains the new node 1.7.11) and it worked fine for me. I started synching with my personal backup from Block 877000 and it runs smoothly up the actual Block (932181). 
So, thanks a lot!

**Comment by izzycsy** [comment]
Hi @MaReCoding , glad that it's working for you. In the future, kindly refrain from installing pre-releases, as it’s still in the midst of testing, use it at your own discretion. If the version has a green `release` marked, you can go ahead and update. Otherwise, wait for the official [DeFiChain Announcements (EN)](https://t.me/defichain_announcements). Thank you for your understanding.

**Comment by gamsterx** [comment]
Hi @izzycsy, I was just able to verify with `1.7.11`. This seems to be fixed. Sync is now complete.
