### ISSUE TITLE
Anchor Bug - anchors not detected OR Creation of invalid anchors

### ISSUE THREAD

**Issue by SacWheeler** [DeFiCh/ain#550]
#### What happened:
Several anchors got created and confirmed on the BTC chain but didn't show up in `spv_listanchors` and didn't get rewarded.

e.g. unrecognized/unrewarded Anchor - btc block: 687918 (2021-06-17 09:47), anchor btc tx:
b344a42484f9102f26b97b1fc054e1bf2df5acc36700d7d0c0ca8fc67e4ce3e4

This anchor referenced the previous anchor (btc tx: dcb3d2421fdd659b0066f1df39549df181027a32fe98eae053b3da52056e33dd) 
and got created by using anchor template
blockhight: 931230 (2021-06-17 06:42:25) , creationHight: 931650 (2021-06-17 09:44:02), defi hash: 9f26dc1bb39677054e1ab268f9e113f3e80f45e270b207dca05eace09a6e6014

As mentioned from @Bushstar in issue #524, 

> the DFI anchor block time should be at least three hours before the Bitcoin block time the anchor is embedded in.

which is the case for the anchor above.

#### What you expected to happen:
This should be a valid anchor and therefore should show up in `spv_listanchors` and get rewarded.
Or
`createanchortemplate` should through an error in case of invalid anchor data

**Comment by Bushstar** [comment]
Please upgrade to 1.7.11, anchor selection has been updated to not select anchor data that is less than three hours behind local time.

**Comment by SacWheeler** [comment]
will test 1.7.11 and report back after evaluation

**Comment by SacWheeler** [comment]
upgrading to 1.7.11 dose not solve this issue.

3 more anchors on the btc chain got **not** recognized by the `spv_listanchors` (or are invalid for some reason?):

- btc block: 688106 (2021-06-18 19:53), btc tx: eaa1c9f69d05a3475072270e642e7e3a9e88b9e0ead881b0529f5eb104a13d40

- btc block: 688134 (2021-06-19 05:40), btc tx: 
777ed0a99513b2cd0fd5ba8dbe6529c2ca8c188d8ee616ca359c29c5e5e12138

btc block: 688145 (2021-06-19 07:44), btc tx:
f9a94281f13c1ca04b4a9b1c42ac9222767621eeac54af7752dc6b68054720f2


I can confirm that 2 of the 3 mentioned anchors above were reverencing the correct, latest, previous anchor as listed by `spv_listanchors` while running 1.7.11.
Additionaly to 1.7.11, I double checked the DeFi Anchor hight. it was at least 3h back from current time before the btc anchor transaction got even sent to the network.

**Comment by Sebz84** [comment]
Btc Tx 777ed0a99513b2cd0fd5ba8dbe6529c2ca8c188d8ee616ca359c29c5e5e12138 was not discovered today. 
The anchor was set using `spv_createanchortemplate` and the latest node 1.7.11.

**Comment by Bushstar** [comment]
Thanks for the continued evaluation. There's something else amiss here. The Bitcoin time that is being shown in the logs does not seem to match the actual block time. Will investigate and get back to you.

/triage accepted

**Comment by SacWheeler** [comment]
@Bushstar How can one retrieve the bitcoin time from spv to analyze and compare it with the actual bitcoin network?

**Comment by Bushstar** [comment]
If you have debug=anchoring set in defi.conf you will see the anchor too new messages in the debug.log, the anchor and Bitcoin TX time are shown there.

**Comment by SacWheeler** [comment]
@Bushstar Thx for the quick reply. 
Ist there a defi-cli spv_command to get infos about previous anchor txs to retrieve used anchor date, especially: **Anchor defiBlockHeight**, **Anchor defiCreationHight**, **btc block time** (other than `spv_listanchors`)?
More like in bitcoin-cli `gettransaction ("txid")` to get information about previous invalid (too new) anchors and the corresponding data from the spv.

**Comment by Sebz84** [comment]
Some more undetected anchors:
fe32af168bcdd04c112be7474c4fd06d1e74e9ab7546af72235df38aa573b8fb
bceb153c5b0e15e931365f936c95167b06ffaf2a3222c152969c8d17466f0a8f
3eba88ac396b399bdbccfb0a6993e8d08c26762dd97e3f9092ab698f6a0b0000

**Comment by Bushstar** [comment]
@SacWheeler there's no such call, spv_listanchors gives the most complete info on anchors which would require you to use an external source to get TX times for Bitcoin. Anchors that are not accepted, like the ones reported in this thread, will not be included in that list as they are discarded.

Actually, the anchors that are discarded might actually be valid when running -spv_resync as if they are confirmed the correct Bitcoin block time will show. So next time there's a forced reindex and the anchor view is rebuilt across the network we may get a queue of unpaid anchors.

What I think is happening is that the time being used for the Bitcoin TX is the time SPV sees the TX, not the time it is confirmed. This was an issue before that was thought to be resolved. Fixing this would resolve the majority of missing anchors above which are generally very close to the time limit.

I'm working on this today and will link the commit if and when a solution is found.

**Comment by SacWheeler** [comment]
@Bushstar Thanks for your reply and sharing your thoughts.

> What I think is happening is that the time being used for the Bitcoin TX is the time SPV sees the TX, not the time it is confirmed. This was an issue before that was thought to be resolved. Fixing this would resolve the majority of missing anchors above which are generally very close to the time limit.

I checked some invalid anchors and compared the SPV BTC time with the TX time and Block time from BitcoinCore (BitcoinCore and DeFiChain running on the same machine).
I have found that the time the SPV is showing is even before the TX time BitcoinCore is showing. How can the SPV see the anchor TX even before the TX got send to the BTC network?
It looks like it is something else as you are referring to - or do I miss something?
<img width="904" alt="Screenshot 2021-06-23 at 09 20 44" src="https://user-images.githubusercontent.com/86059822/123073083-65f73180-d416-11eb-874f-f1dab1dd13fe.png">

**Comment by Bushstar** [comment]
When a TX is first relayed to SPV from the mempool, before it is added to a block, SPV will store that TX and set its time via the C time() function.

**Comment by Bushstar** [comment]
Actually, I've found the issue, SPV is not prescient, it sometimes sets the time as half of the current block time plus half of the last block time. For SPV we use breadwallet-core, I'll update to just use the actual block time. Line of code in question is linked below.

https://github.com/DeFiCh/ain/blob/master/src/spv/bitcoin/BRPeerManager.cpp#L1261

Taking the following error, the block time is 1624342316 however the actual block time is 1624342948.

2021-06-22T06:25:57Z Anchor too new. DeFi: 1624332030 Bitcoin: 1624342316 Anchor: bceb153c5b0e15e931365f936c95167b06ffaf2a3222c152969c8d17466f0a8f

 However if we take half the time of the previous block and half the time of the block the TX is in we get...

(1624342948÷2)+(1624341684÷2) = 1624342316

1624342316 is the time shown in the log.

**Comment by SacWheeler** [comment]
@Bushstar Thx for your investigation. This sounds right to me!
Does the change in the line of code linked above take place with the next hard fork (1.8.x) or as an update of the 1.7.x version?

**Comment by Bushstar** [comment]
Sometimes the correct time is used so we already have a situation where the anchor view is inconsistent, so we can roll this update out in the next release and get Cake MNs to update and run spv_resync to build a consistent anchor view.  The correct TX time is set when the node switches fork, in that a competing block that contains the same TX becomes part of the longer chain.
