### ISSUE TITLE
ICX icx_submitexthtlc with error message

### ISSUE THREAD

**Issue by ShengguangXiao** [DeFiCh/ain#555]
#### What happened:
```
./defi-cli icx_submitexthtlc '{"offerTx":"acc304ef3d494811df77c1587e07b5ee5a56df5bd0568c150fdcea69defec851","hash":"9a5a57656b47745fb6fabefc317be8d39efc553959d661cc6456d2db0336543a","amount":0.0001,"htlcScriptAddress":"3AqTafDs8VbAP3c9BoQivFbK6hbaGdbxdr","ownerPubkey":"02caa810fd93899abbf6b1691de94099301930ec4029c48101baaf67ee3b7e5e33","timeout":40}'
error code: -32600
error message:
Test ICXSubmitEXTHTLCTx execution failed:
negative amount: -0.00000021
```
#### What you expected to happen:
It should success with transaction id

#### Anything else we need to know?:

There are two places in the code may have problem.
https://github.com/DeFiCh/ain/blob/7a430185fd3029e9ee8974fde4e65c715fb9db04/src/masternodes/mn_checks.cpp#L1273
https://github.com/DeFiCh/ain/blob/7a430185fd3029e9ee8974fde4e65c715fb9db04/src/masternodes/mn_checks.cpp#L1396

**Comment by uzyn** [comment]
This affects partial acceptance of the offer.
