### ISSUE TITLE
Fee calculating algorithm

### ISSUE THREAD

**Issue by IhorSavva** [DeFiCh/ain#593]
Hello. Please tell me, when creating a transaction, what is the algorithm for calculating the fee?
Should I calculated of satoshi per byte, or just using a fixed fee per transaction or inputs/outputs?

**Comment by uzyn** [comment]
There's no fixed fee on blockchain. You can pay any fee. Highest fees is more likely to be included in the next block.

**Comment by bvbfan** [comment]
> Should I calculated of satoshi per byte, or just using a fixed fee per transaction or inputs/outputs?

Fee Per Kilobyte
You can use `getwalletinfo` field `paytxfee`
