### ISSUE TITLE
icx_submitdfchtlc encounter error

### ISSUE THREAD

**Issue by ShengguangXiao** [DeFiCh/ain#600]
#### What happened:
icx_submitdfchtlc get below error. It happens in the maker side, when the maker want to accept the offer from taker.
```
{
  code: -32600,
  message: "Test ICXSubmitDFCHTLCTx execution failed:\namount 0.00000000 is less than 0.00000050"
}
```

```
{
"orderTx":"290bc880f1a7401e3885fae28faf77208295ff913a546c8f03f26cdb8a1a3110",
"status":"OPEN",
"amount":0.0001,
"amountInFromAsset":0.0001
,"ownerAddress":"tk7nuNxJ96tCAM57eT7Wx6pQYut8yReoZt",
"takerFee":5e-7,
"expireHeight":440229
}
```
#### What you expected to happen:
It should success.

#### Anything else we need to know?:

It happens at here. https://github.com/DeFiCh/ain/blob/87a4760e06d286edcd481b810200b0b480e17282/src/masternodes/mn_checks.cpp#L1285

**Comment by Mixa84** [comment]
@ShengguangXiao can you check this is still an issue in 1.8?

**Comment by ShengguangXiao** [comment]
I didn't encounter this problem again. I think it can be closed.
