### ISSUE TITLE
`listaccounthistory` missing transactions

### ISSUE THREAD

**Issue by gamsterx** [DeFiCh/ain#610]
#### What happened:
`listaccounthistory` with option `mine` does not return all of my transactions. It only returns rewards from one pool and is missing rewards and commissions from the other one.

```
======================== List Account History =====================================
[
  {
    owner: 'dA',
    blockHeight: 1004031,
    blockHash: '056c2d535a846b71a4c776cc179b8f0995ae3a30f72b7f9dd8dd46788f84ec0a',
    blockTime: 1626094701,
    type: 'Rewards',
    poolID: '6',
    amounts: [ 'x.x@DFI' ]
  },
  {
    owner: 'dA',
    blockHeight: 1004030,
    blockHash: '28143f1543003208d7e159da7d6cf87305aec0300a2de8e6a86b17959c665e87',
    blockTime: 1626094805,
    type: 'Rewards',
    poolID: '6',
    amounts: [ 'x.x@DFI' ]
  },
  ...
]
```

#### What you expected to happen:
```
 {
    owner: 'dA',
    blockHeight: 1004031,
    blockHash: '056c2d535a846b71a4c776cc179b8f0995ae3a30f72b7f9dd8dd46788f84ec0a',
    blockTime: 1626094701,
    type: 'Rewards',
    poolID: '6',
    amounts: [ 'x.x@DFI' ]
  },
 {
    owner: 'dB',
    blockHeight: 1004031,
    blockHash: '056c2d535a846b71a4c776cc179b8f0995ae3a30f72b7f9dd8dd46788f84ec0a',
    blockTime: 1626094701,
    type: 'Rewards',
    poolID: '5',
    amounts: [ 'x.x@DFI' ]
  },
  {
    owner: 'dA',
    blockHeight: 1004030,
    blockHash: '28143f1543003208d7e159da7d6cf87305aec0300a2de8e6a86b17959c665e87',
    blockTime: 1626094805,
    type: 'Rewards',
    poolID: '6',
    amounts: [ 'x.x@DFI' ]
  },
  {
    owner: 'dB',
    blockHeight: 1004030,
    blockHash: '28143f1543003208d7e159da7d6cf87305aec0300a2de8e6a86b17959c665e87',
    blockTime: 1626094805,
    type: 'Rewards',
    poolID: '5',
    amounts: [ 'x.x@DFI' ]
  },
  ...
]
```

#### How to reproduce it (as minimally and precisely as possible):
`listaccounthistory` with option `mine` and `no_rewards=false`

#### What are your environment parameters:
Same behavior on `Windows` and `OSX`

defid.exe: `v1.7.11`

defi.conf:
```
rpcauth=usr:pw
rpcuser=usr
rpcpassword=pw
rpcconnect=127.0.0.1
testnet=0
regtest=0

[main]
rpcbind=127.0.0.1
rpcport=8555
spv=0
gen=0
wallet=some wallet.dat
walletdir=C:\Users\Usr\AppData\Roaming\DeFi Blockchain\wallets\main
checkpoints=0

[test]
rpcbind=127.0.0.1
rpcport=8555
```

#### Anything else we need to know?:
`listaccounthistory` with the explicit `owner` does return rewards which are not shown with `mine`

I used the jellyfish client to get the data:
```ts
const history = await this.jelly.client.account.listAccountHistory("mine", {
      no_rewards: false,
    });
```

Same behavior via export of transactions via the `defichain app v2.5.2`. Here all rewards and commissions of the pool `5` are missing.

Did a complete reindex with `checkpoints=0` and `spv=0` (see defi.conf)

**Comment by bvbfan** [comment]
You still have same issue?

**Comment by gamsterx** [comment]
yes, nothing changed.

**Comment by gamsterx** [comment]
Update: Used app `2.6.0` with node `1.8.0`. Same behaviour.

**Comment by gamsterx** [comment]
@bvbfan I´m still not getting all rewards with `1.8.1` . The bug seems to occur if you remove all liquidity from a pool.

Here is some historical data:

|block|type|Amount|Currency| Comment |
|------|-----|---------|---------| ----------- |
|846542 | AddPoolLiquidity|-X| USDT||
|846542 | AddPoolLiquidity|-X| DFI||
|846542 | AddPoolLiquidity|+X|USDT-DFI||
|846542|Rewards(USDT-DFI Pool)| +X.X|DFI| THESE rewards are missing|
|...| ...|...| ...||
|846546| AddPoolLiquidity|-Y| BTC||
|846546| AddPoolLiquidity|-Y| DFI||
|846546| AddPoolLiquidity|+Y.Y|BTC-DFI||
|846546|Rewards(BTC-DFI Pool)| +Y.Y|DFI| THESE rewards are shown|
|846542|Rewards(USDT-DFI Pool)| +X.X|DFI| THESE rewards are missing|
|...| ...|...| ...||
|859894| RemovePoolLiquidity|+X| USDT||
|859894| RemovePoolLiquidity|+X| DFI||
|859894| RemovePoolLiquidity|-X|USDT-DFI| ALL liquidity is removed from the pool|
|859894|Rewards(BTC-DFI Pool)| +Y.Y|DFI| <-- THESE rewards are shown|
|1XXXXXX| ...|...| ...| An export via the app or via jellyfish `listaccounthistory` yields only rewards from the BTC-DFI pool|

**Comment by RomanShumkov** [comment]
> The bug seems to occur if you remove all liquidity from a pool.
+1

**Comment by gamsterx** [comment]
@bvbfan 
@prasannavl 
I tried to verify the fix with https://github.com/DeFiCh/ain/runs/3337570374

Rewards from USDT-DFI Pool are still missing! The issue does not seem to be resolved.

**Comment by bvbfan** [comment]
I tested it, it works for me.

**Comment by gamsterx** [comment]
@bvbfan I removed `all` liquidity. What do you mean by `you should go to before remove liquidity tx to see rewards`

**Comment by bvbfan** [comment]
When you remove all liquidity you don't have share in liquidity pair, that's mean you will not receive rewards any more. Rewards are based on your share in the pool. By going before tx is you should increase `limit` to 1000 or more to see rewards before you remove the liquidity.

**Comment by gamsterx** [comment]
Ah ok. Yes of course! The problem here is that I don´t get the rewards from a certain range in the past. Can you check `listaccounthistory` for address `dEbzaH9hgvfG3652mPUfX9yLJvZkF8q2fe` at block `846542`. There you should see the `AddPoolLiquidity` tx of the `USDT-DFI` token , but no rewards

**Comment by gamsterx** [comment]
@bvbfan do you get the same output? Can we please reopen this issue until it is fixed and verified?

**Comment by bvbfan** [comment]
But you look before adding liquidity, you should look before removing. At block 846542 you add liquidity so you receive rewards after that block till you remove liquidity, so get block when you remove it and replace 846542 in the query.

**Comment by gamsterx** [comment]
@bvbfan When I check another address from the BTC-DFI pool I get the first reward the same block I get the BTC-DFI token. Even after the above mentioned block I don´t get the rewards to be listed. I encourage you to check it out and please give feedback.

**Comment by prasannavl** [comment]
@gamsterx - thanks for both the report and following up on this! I believe this was autoclosed with the PR merge. Let us have a look into this in the next few days and evaluate if we need to re-open again. Appreciate your patience!

**Comment by bvbfan** [comment]
Try like that `listaccounthistory dEbzaH9hgvfG3652mPUfX9yLJvZkF8q2fe {"maxBlockHeight":1000000} `

**Comment by nappy** [comment]
I am also missing all rewards from my doge pool, no matter whether I use owner "mine" or the share address. When I add the doge amounts of all my other transactions I will end up with a negative balance, so there is definitely something wrong still.

**Comment by bvbfan** [comment]
Rewards are redistributed in DFI don't add filter by token `listaccounthistory dLsskYoMhdFABFwZQ5ATjismcN4CcxA643`

**Comment by nappy** [comment]
Sorry I need to clarify: I am missing all rewards **AND** commissions from the DOGE-DFI pool. There are no reward or comission entries in my history with poolId = 8, no matter if I filter by token or not. The token filter was just added for your convenience.

**Comment by bvbfan** [comment]
Did you still have liquidity on that pair? I saw couple of remove liquidity on provided address, another issue, unrelated to this, is no history prior last checkpoint, say rewards prior block 895741 are unavailable. It should be considered as feature for next major release, right now nodes does not keep `all` history by default, it can be achieved by `-fcheckpoints=0` and full reindex.

**Comment by gamsterx** [comment]
@bvbfan At a later point in time I again added some small liquidity to the USDT-DFI pool to see if that would resolve the missing rewards issue. While I was holding USDT-DFI token > 0 I was able to get the "old" rewards (from block 846542 onwards from pool 6). Then I removed ALL liquidity again. And now the old rewards are missing again. 

I did a reindex with "checkpoints=0" in my defi.conf.

**Comment by nappy** [comment]
@bvbfan I have no liquidity on that pair anymore, and I already did the -reindex with checkpoins=0 in the configuration file as described in this issue (which I assume should be the same as -fcheckpoints=0 cli option?). Also iirc I did see no gaps of rewards for most the other pools (which I also removed all liquidity from), and I did see rewards for other pools before and after the removal of DOGE-DFI liquidity.

**Comment by gamsterx** [comment]
@prasannavl @bvbfan 
Any update on this? 
Again, please reopen this issue so that this issue can be tracked accordingly.

**Comment by bvbfan** [comment]
Rewards prior block `895741` needs reindex with `-fcheckpoints=0` #699 should allow doing it without reindex nor maintaining undo history.

**Comment by gamsterx** [comment]
@bvbfan thank you for your reply. Can you please explain the difference between `-checkpoints=0` and  `-fcheckpoints=0`?

I would like to keep the whole 100+GB of chain data.  I did a reindex with `checkpoints=0` in my `defi.conf`. I noticed that blockchain data is only a few GB. Is it pruned automatically in the current version?

What do I have to do to keep everything?

**Comment by bvbfan** [comment]
There is no `-fcheckpoints=0` it's just a misplaced because in the source code is with f prefixed. Correct name is `-checkpoints=0`

**Comment by gamsterx** [comment]
@bvbfan ok I see. Can you give an answer to the other questions? Thanks!

```
I would like to keep the whole 100+GB of chain data. I did a reindex with checkpoints=0 in my defi.conf. 
I noticed that blockchain data is only a few GB. Is it pruned automatically in the current version?

What do I have to do to keep everything?
```

**Comment by bvbfan** [comment]
We don't keep entire data anymore, so reindex with `-checkpoints=0` should give you all the data to see rewards history.

**Comment by gamsterx** [comment]
@bvbfan Ok, well this results in the issue which is mentioned in my [comment](https://github.com/DeFiCh/ain/issues/610#issuecomment-894807195). Will #699 fix this? Or should this issue indeed be reopened?

**Comment by bvbfan** [comment]
After
```
859894 | RemovePoolLiquidity | +X | USDT
```
if you don't have a share of USDT anymore, means you remove all liquidity, i will not receive rewards anymore. Rewards are redistributed if and only if you have some pool share.

**Comment by gamsterx** [comment]
@bvbfan  I think you misunderstood me. It is clear to me that I don´t get rewards if don´t have a liquidity token anymore. The problem is that the rewards (and commissions) between


`846542 | AddPoolLiquidity | +X | USDT-DFI `

and 

`859894 | RemovePoolLiquidity | -X | USDT-DFI` 

are missing

**Comment by nappy** [comment]
@bvbfan Sorry for repeating myself but you di seem to understand the issue: We are missing rewards and commission even after reindex with checkpoints=0. I do not expect rewards after selling all LP tokens, do you really think we are that stupid? 🙁

**Comment by izzycsy** [comment]
@gamsterx , reopening this issue as to prevent duplicated tickets.

**Comment by Kolibri1990** [comment]
#### What happened:

Hello dear Tech Team,

I'm getting back to you (Had some discussions during the older nodes with @bvbfan) about the history of Liquidity Mining Rewards and Commissions.

I still get incomplete results back from the node after full synchronization.

The funny thing is that during the synchronization (I didn't watch how long it will last) I get the complete history of the node back. 

And when I am full sync, then no more.

Is there pruning at the end of the sync?

My test RPC call via CLI:

`defi-cli.exe listaccounthistory mine {\"maxBlockHeight\":498600}`

and also with:

`defi-cli.exe listaccounthistory dWq7uW6vRypHQ3E8YcgT7MhSw7F7KipYaY {\"maxBlockHeight\":498600}`

During Sync:

```
{
    "owner": "dWq7uW6vRypHQ3E8YcgT7MhSw7F7KipYaY",
    "blockHeight": 498574,
    "blockHash": "3e0b1afeac8af21f224d363305a097341bd8c42ae79fd99394b9083b7669082b",
    "blockTime": 1607857202,
    "type": "Rewards",
    "rewardType": "Coinbase",
    "poolID": "5",
    "amounts": [
      "0.00585011@DFI"
    ]
  },
  {
    "owner": "dWq7uW6vRypHQ3E8YcgT7MhSw7F7KipYaY",
    "blockHeight": 498574,
    "blockHash": "3e0b1afeac8af21f224d363305a097341bd8c42ae79fd99394b9083b7669082b",
    "blockTime": 1607857202,
    "type": "Commission",
    "poolID": "5",
    "amounts": [
      "0.00002477@DFI"
    ]
  },
  {
    "owner": "dWq7uW6vRypHQ3E8YcgT7MhSw7F7KipYaY",
    "blockHeight": 498573,
    "blockHash": "fdf31441c63ec610372a54bc3e12f3d98009de93289d871f496a505991ff2685",
    "blockTime": 1607857166,
    "type": "AddPoolLiquidity",
    "txn": 2,
    "txid": "20b7a2a2a4805a3f07afa960c3e7a83f11794fa1c667c44248ec62c7131f93f6",
    "amounts": [
      "1.70327789@BTC-DFI"
    ]
  },
```
  
  **-> With Rewards and Commissions**
  
 After Full Sync:
  
```
  [
  {
    "owner": "dWq7uW6vRypHQ3E8YcgT7MhSw7F7KipYaY",
    "blockHeight": 498573,
    "blockHash": "fdf31441c63ec610372a54bc3e12f3d98009de93289d871f496a505991ff2685",
    "blockTime": 1607857166,
    "type": "AddPoolLiquidity",
    "txn": 2,
    "txid": "20b7a2a2a4805a3f07afa960c3e7a83f11794fa1c667c44248ec62c7131f93f6",
    "amounts": [
      "1.70327789@BTC-DFI"
    ]
  },
```

**-> It's like lottery if there are Rewards or Commissions at blocks**


Could it be that the node is too overloaded to read the DB if the wanted result are too far away from the current block?
But this is also sometimes the case with newer blocks.

With luck, the information is in the history DB and only the node does not manage to read it completely?

Is there an easy way to read the history database that the node creates without the node? It is a level DB or? 
How is the database built with which key value pairs? 
Is there a documentation or someone who can show me something? 
I'm not a C++ expert, I don't completely understand everything behind the code.


#### What you expected to happen:

I expect to get the matching rewards for each block as well. I think it would even be enough to save the rewards and commissions per pool per day and not to prune and throw away.

#### How to reproduce it (as minimally and precisely as possible):

Synchronized Node and try:

`defi-cli.exe listaccounthistory dWq7uW6vRypHQ3E8YcgT7MhSw7F7KipYaY {"maxBlockHeight\":498600}`

-> It should return some rewards and commissions and not only 2 entries:

```
[
  {
    "owner": "dWq7uW6vRypHQ3E8YcgT7MhSw7F7KipYaY",
    "blockHeight": 498573,
    "blockHash": "fdf31441c63ec610372a54bc3e12f3d98009de93289d871f496a505991ff2685",
    "blockTime": 1607857166,
    "type": "AddPoolLiquidity",
    "txn": 2,
    "txid": "20b7a2a2a4805a3f07afa960c3e7a83f11794fa1c667c44248ec62c7131f93f6",
    "amounts": [
      "1.70327789@BTC-DFI"
    ]
  },
  {
    "owner": "dWq7uW6vRypHQ3E8YcgT7MhSw7F7KipYaY",
    "blockHeight": 498556,
    "blockHash": "700aa96d1ab3bf4839a8fb53d586312c1a8bf204063df420502425db0cb5b4c0",
    "blockTime": 1607856650,
    "type": "receive",
    "txn": 0,
    "txid": "13666ef5b1ed855e61732cb610d9759008a247457e64b1fa4d7631bde2d8c195",
    "amounts": [
      "678.21782178@DFI"
    ]
  }
]
```

#### What are your environment parameters:
OS: Windows 10
CPU: 11th Gen Intel(R) Core(TM) i9-11900F @ 2.50GHz
RAM: 32GB

**Comment by salomonkarsten** [comment]
In order to get proper tax reports realistic and consistent data from the blockchain is essential.  Hope you fix this soon. I wonder how this command will look like for loans and minted coins

**Comment by bvbfan** [comment]
@Kolibri1990 i can confirm, will investigate, hopefully i can open PR.

**Comment by salomonkarsten** [comment]
PR means What?

**Comment by bvbfan** [comment]
> PR means What?

Fix

https://github.com/DeFiCh/ain/actions/runs/1425932251
When it's ready you can get executable and test it. No reindex is required at all.

**Comment by Kolibri1990** [comment]
> > PR means What?
> 
> Fix
> 
> https://github.com/DeFiCh/ain/actions/runs/1425932251 When it's ready you can get executable and test it. No reindex is required at all.

Hey @bvbfan,
nice with my address it's working :-) THANKS

With the argument "mine" instead of the address it does not work yet. 

Is it possible to fix this?

**Comment by bvbfan** [comment]
@Kolibri1990 
like `defi-cli.exe listaccounthistory mine {\"maxBlockHeight\":498600}` it does not show rewards to `dWq7uW6vRypHQ3E8YcgT7MhSw7F7KipYaY` or it does not show all rewards?

**Comment by Kolibri1990** [comment]
@bvbfan 

`defi-cli.exe -conf=C:\Users\danie\.defi\defi.conf listaccounthistory mine {\"maxBlockHeight\":498600}`

Shows no rewards... neither from this address nor from any other

**Comment by bvbfan** [comment]
@Kolibri1990 test with new patch while it's ready https://github.com/DeFiCh/ain/actions/runs/1433509961

**Comment by Kolibri1990** [comment]
> @Kolibri1990 test with new patch while it's ready https://github.com/DeFiCh/ain/actions/runs/1433509961

Hey @bvbfan 

Unfortunately, it did not change anything for me. I still don't get rewards and commissions with "mine".

And now I also don't see any rewards and commissions with using the address in command:

`defi-cli.exe listaccounthistory dWq7uW6vRypHQ3E8YcgT7MhSw7F7KipYaY {"maxBlockHeight\":498600}`

**Comment by bvbfan** [comment]
@Kolibri1990  new build https://github.com/DeFiCh/ain/actions/runs/1433885145
I can't confirm to `mine` i can see mine by parameters itself or by address.

**Comment by Kolibri1990** [comment]
> @Kolibri1990 new build https://github.com/DeFiCh/ain/actions/runs/1433885145 I can't confirm to `mine` i can see mine by parameters itself or by address.

@bvbfan Now it works again with a single address.

With `mine ` I still get no rewards/commissions

**Comment by bvbfan** [comment]
Strange mine starts on 526460 and i see them.

**Comment by Kolibri1990** [comment]
If you want I can move my assets to an other wallet and you can test it directly with my strange wallet.dat :D
