### ISSUE TITLE
Coinage increment for 5y and 10y lockup should be 2h15m and 1h15m respectively to achieve 1.5x and 2x effect

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/ain#619]
#### What would you like to be added:

Related: #546 & #562

Coinage increment should be updated as follows:

- Without lockup: increment every 6 hours (status quo)
- 5 years collateral lockup: increment every 2 hours 15 minutes (for 1.5x more return)
- 10 years collateral lockup: increment every 1 hour 15 minutes (for 2x more return)

The cap remains unchanged.

#### Why is this needed:

Likelihood of finding a block as a function of coinage increment is not a linear function, but a geometrical one. 

<img width="819" alt="Screen Shot 2021-07-19 at 15 41 52" src="https://user-images.githubusercontent.com/280505/126121820-d65711ce-d5b3-455a-922f-b2963316ec4d.png">

Monte Carlo simulation of 100k rounds has been worked out to affirm that the coinage increment as laid out above would achieve the desired effect:

```sh
$ node freeze-staking-montecarlo.js
CYCLES 100000
NODES [ 1000, 1000, 1000 ]
TARGET 0.01
COINAGE_EVERY [ 24, 9, 5 ]

Findings: [ 1993273, 2992969, 3883381 ]
Type 0: 1.993% success rate. (1.000x)
Type 1: 2.993% success rate. (1.502x)
Type 2: 3.883% success rate. (1.948x)
```

Simulation code: https://gist.github.com/uzyn/f9766cfd69ff6a586a0877b6cbae11c0

This is also observed by the community members after collecting data on Eunos Paya testnet. 

#### On the intention of DFIP

The next part to determine is on the intention of [DeFi Improvement Proposal](https://github.com/DeFiCh/dfips/issues/39) that was approved, if the intention is to achieve the outcome, i.e. 1.5x (5y) & 2x (10y) or the intention being the increment of coinage as laid out under the "Mechanism" section.

My opinion is that it is clear here that the intension that was approved is to achieve the desired outcome of 1.5x and 2x with the lockups. The mechanism, though contains calculation error, is clearly laid out with the intention to achieve the desired outcome. 

Without this change, locking up for 5 years would merely yield 1.125x more blocks and 10 years 1.35x more, which would be extremely unattractive to users who opted to do so.

**Comment by Stonygan** [comment]
> My opinion is that it is clear here that the intension that was approved is to achieve the desired outcome of 1.5x and 2x with the lockups. The mechanism, though contains calculation error, is clearly laid out with the intention to achieve the desired outcome.
> 
For me 100% same opinion. Voting was for 1,5x or 2x with locking.

**Comment by uzyn** [comment]
Superseded by #626
