### ISSUE TITLE
Change Masternode Rewardaddress

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/ain#629]
#### What would you like to be added:

Like described/start developing in Branch:
https://github.com/DeFiCh/ain/tree/feature-mn-rewardaddress
i think we need a solution to change or specify the rewardaddress to the Owneraddress or change it from the Ownerwallet witout the possibility to change it from the Operatornode.
Actual its possible for the Operatoraddress-Holder or with a compromised Operatoraddress to redirect the rewards to every address in the network. With the 5y/10y locking, this feature is important. I'm afraid the operator addresses on the VPS could otherwise be tried to be stolen to get the rewards of the locked masternode.

#### Why is this needed:
Make the Minting more secure, when Masternode is locked, a compromised Operatoraddress cant resigned and maybe lost 50% or more of his rewards.

Dont know why PR298 is no longer accessible or deleted, but some of the work already done i think.

 https://github.com/DeFiCh/ain/pull/298

Commit Summary

    

- added rewardAddress in masternode class
- Merge branch 'master' into feature-mn-rewardaddress
- setforcedrewardaddress rpc
- setforcedrewardaddress apply
- RemoveForcedRewardAddress rpc and apply
- coinbase script from mn reward address
- SetForecedrewardAddress tx code to type and make scriptPubKey
- functional test and isMine check
- fix typo and functional test for -gen param
- linter fix
- mn messages refactoring

**Comment by uzyn** [comment]
PR: https://github.com/DeFiCh/ain/pull/642
