### ISSUE TITLE
height in GetActivationDelay wrong

### ISSUE THREAD

**Issue by muirglacier** [DeFiCh/ain#635]
https://github.com/DeFiCh/ain/blob/1cdc7e05b8340fbd51ba76a1263a6e1fb194e6cd/src/masternodes/masternodes.cpp#L118-L124

Hi,

please check out the referenced code.
You are taking the ActivationDelay (and ResignDelay) from the current height, not from creationHeight. This can lead to problems when changing the delays in the future.

**Comment by uzyn** [comment]
Thanks @muirglacier 

/triage accepted

**Comment by bvbfan** [comment]
It's correct, when `height` is before `resignHeight` + resign delay it's in `PRE_RESIGNED` state.

**Comment by muirglacier** [comment]
No, it’s not correct ;-) Activation delay should be taken at the creation height and not at the current height

**Comment by bvbfan** [comment]
I don't think so.

**Comment by prasannavl** [comment]
@muirglacier, thank you for reporting this :)  Fixed. Should be in the shortly upcoming release.
