### ISSUE TITLE
UncreateMasterNode does not remove TimeLock

### ISSUE THREAD

**Issue by muirglacier** [DeFiCh/ain#636]
https://github.com/DeFiCh/ain/blob/1cdc7e05b8340fbd51ba76a1263a6e1fb194e6cd/src/masternodes/masternodes.cpp#L378-L388

See above

**Comment by uzyn** [comment]
Thanks @muirglacier 

/triage accepted

**Comment by bvbfan** [comment]
It's still not in use.

**Comment by muirglacier** [comment]
Of course it is in use :-) ... by the CustomTX Revert Visitor

https://github.com/DeFiCh/ain/blob/524070197b1696e418a851e4e19dd54f25d45287/src/masternodes/mn_checks.cpp#L1736-L1739

The way it is now could cause issues when a MN Create is reverted, and then reissued without a timelock. Then, it would still end up having a timelock.

**Comment by bvbfan** [comment]
https://github.com/DeFiCh/ain/blob/master/src/masternodes/mn_checks.cpp#L1882-L1888
We will enable it in the future, mainly we should better handle token / pool pair creation / reverts, masternodes probably not.

**Comment by muirglacier** [comment]
Oh sorry, I missed that it is not activated. But this leads me to the next question:

Isn't this super dangerous? What if a masternode gets created and the chain rolls back. Nodes that have been online will have this masternode in their database, while nodes that sync freshly after the roll back will not have heard about this masternode. Isn't a chain split possible here?

**Comment by bvbfan** [comment]
We use undos for that https://github.com/DeFiCh/ain/blob/master/src/validation.cpp#L1776, it's safe. `RevertCustomTx` algorithm is for edge cases, one edge case is accounts and burn history as well as token and pool pair ids. It can replace undos in the future, but for now it has a partial role.

**Comment by muirglacier** [comment]
Thanks for the explanation :-) I understand now
