### ISSUE TITLE
ARM builds

### ISSUE THREAD

**Issue by romainhaenni** [DeFiCh/ain#644]
#### What would you like to be added:
Please add ARM 64 builds to each release.

#### Why is this needed:
It makes it a lot easier to install defichain daemons on Raspberry PIs which are very popular to run nodes on as an individual. Nowadays, it must be built from source which takes about 2h even if one knows how to do it.

Thanks.

**Comment by uzyn** [comment]
Thanks for the suggestion @romainhaenni 

It's not in the official build process. Adding 1 more arch to support could add a major dependency on our development.

There is a community project that does precisely that! Check out https://github.com/definode/definode

**Comment by uzyn** [comment]
Closing for out of scope for now. Please use the community build.

**Comment by Martin8617** [comment]
Hallo @romainhaenni
Mittlerweile habe ich eigene repositories für die Raspberry releases geschrieben.
Have a look at https://github.com/Martin8617

**Comment by romainhaenni** [comment]
nice! that's really helpful! cheers!

**Comment by prasannavl** [comment]
Referencing for context: https://github.com/DeFiCh/app/issues/1030#issuecomment-905561464
