### ISSUE TITLE
typos in the rpc commands

### ISSUE THREAD

**Issue by bernd-mack** [DeFiCh/ain#650]
Just a few typos that could be corrected on occasion

#### What happened:
spv_listransactions
spv_gatrawtransaction "txid"

#### What you expected to happen:
spv_listtransactions
spv_getrawtransaction "txid"

#### How to reproduce it (as minimally and precisely as possible):
type help in the commandline

#### Anything else we need to know?:
no

**Comment by prasannavl** [comment]
Thanks for this @bernd-mack! This should have been fixed in 1.8.1
