### ISSUE TITLE
createpoolpair does not allow name clash

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/ain#68]
At the moment `createpoolpair` does not allow token symbol name clash, this allows someone to hijack a token pair. Even if different tokens are used to create the pair, if the same ID is generated e.g. `DFI-Test` this will result in the following error message:

```
{
  code: -32600,
  message: "Execution test failed:\nPoolPair creation DFI-Test: token 'DFI-Test' already exists!"
}
```

`createpoolpair` should allow clash of pool pair id **even** if the pool contains the exact same tokens as another pool pair. Users should be able to create multiple pool pairs for the same token combinations as these pools may have different qualities such as different commision.

**Comment by monstrobishi** [comment]
Note that you can override `symbol` in parameters to avoid the clash, but the default behaviour should still avoid clashing in a deterministic manner.

**Comment by ShengguangXiao** [comment]
When create a PoolPair, we also create a token named with this PoolPair symbol, what is the rational behind or it is just a bug? @DeFiDev

**Comment by monstrobishi** [comment]
@DeFiDev 

The solution to this is a non-consensus breaking change to the interface, to automatically generate a pool pair ID that will not clash because of similar symbol names
