### ISSUE TITLE
Api showing wrong/inconsistent Data

### ISSUE THREAD

**Issue by wmbst** [DeFiCh/ain#690]
#### What happened:

defichain Api is showing wrong/inconsistent data in supply section.

https://api.defichain.io/v1/stats

It shows total supply to be the same as circulating supply. this must be wrong, as there are burned tokens and tokens in the community fund pool. These two cannot be part of the circulating supply but have to be part of the total supply.

So both numbers are wrong total  is too low and circulating is too high. 
supply":{"total":481713649.3147338,"circulation":481713649.3147338,"foundation":0,"community":18785289.35339481},
It would be great, if in this part you could allow add the total sum of burned coins, to have all necessary supply numbers in one section.

Also Initial Distribution is wrong. After the hard fork and the elimination of Foundation coins. Within the initial distribution has the foundation coins have to be set to 0 as these have never been minted with the actual version defichain.

"initDist":{"total":588000000,"totalPercent":49,"foundation":288120000,"foundationPercent":49,"circulation":49,"circulationPercent":51}},"rewards":

#### What you expected to happen:

The Api _has_ to show the correct numbers. How can anybody trust defichain if not even such basics as supply numbers are right. The API, defichain-analytics, coinmarketcap, coin gecko all show different numbers. Please make these numbers right and consistent. Please make this top priority, as it is a huge burden for defichain. Just think how can an exchange, or an investor trust defichain, if he/she cannot trust the basic numbers at all.

**Comment by shohamc1** [comment]
This issue seems related to the Jellyfish API, please open an issue [here](https://github.com/JellyfishSDK/jellyfish/issues/new/choose) if the stats are still incorrect.
