### ISSUE TITLE
getmasternodeblocks give no blocks after Eunos Paya

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/ain#694]
#### What happened:
CLI-Command getmasternodeblocks give no blocks after the Hardfork EUNOS PAYA. Only blocks before this date.

#### What you expected to happen:
Get all blocks of the Masternode.

#### How to reproduce it (as minimally and precisely as possible):
~/.defi/defi-cli getmasternodeblocks {"operatorAddress":"xxxxx"}

#### What are your environment parameters:
APP 2.6.2 or AIN 1.8.2

#### Anything else we need to know?:
First output displays the block of the Creation as a output, too, thats not correct.

https://github.com/DeFiCh/app/issues/966

**Comment by prasannavl** [comment]
Thanks for the reporting this @Stonygan. We'll have a fix for this in, along with the next update.

**Comment by izzycsy** [comment]
Hi @Stonygan , moving your [issue](https://github.com/DeFiCh/app/issues/966) here. Thank you.

**Comment by Stonygan** [comment]
I think its not working, maybe only to count one of the Subnodes?

`~/.defi/defi-cli getmasternodeblocks '{"ownerAddress":"8Ynwzb9Z9FBrK8D7LTaDtruBJks4SCkhgf"}'
{
  "1152096": "0fabb95993622162a2502633a9e392e2aa2924ec4f44007fa1630a938b8e5363",
  "1139991": "a7ae4fe05f5203c32091a8a3707867cd223727dd9b08b787acd2ab338b0c4297",
  "1131190": "af69949f1bb341c357cf7776e1b0b1c18e5afc32f15a07d3013f87560b0048e6",
  "1117114": "3500551dc007074771e402feb6335cfd9a687931352af572dccec6ca477bc143",
  "1096928": "893037efb248930b86920ebcf7c2cda27002a9f19c19eee910a76ed4f73bbd11",
  "1080842": "8e0ecbf934c020913641277b5da8375933a44190f3d89b3a0fafe357ab89c8bb"
}
`

This MN minted 26 blocks in the last weeks.
https://chainz.cryptoid.info/dfi/address.dws?8Ynwzb9Z9FBrK8D7LTaDtruBJks4SCkhgf.htm

**Comment by prasannavl** [comment]
Thanks @Stonygan. This still does requires futher fixes - will leave this open - however, have to wait till Fort Canning release for it to be fully addressed, I'm afraid.
