### ISSUE TITLE
Getting no data with RPC call for Masternode addresses 

### ISSUE THREAD

**Issue by Lysanthe** [DeFiCh/ain#710]
#### What happened:
When using the RPC Calls: getaccount or accounthistorycount for an address with a masternode like
{
  "jsonrpc": "1.0",
  "id": "1",
  "method": "getaccount",
  "params": [
    "8WrcPiaoGhQgitWiBG6e3fW7dVTuZMvjot"
  ]
}
I do not get any results. That's the same for alle masternode addresses i tried. 

When you look up the address in the blockexplorer you get data:
https://explorer.defichain.io/#/DFI/mainnet/address/8WrcPiaoGhQgitWiBG6e3fW7dVTuZMvjot

#### What you expected to happen:
Do get Data from the RPC calls when using a masternode address

#### How to reproduce it (as minimally and precisely as possible):
Use the RPC Call

#### What are your environment parameters:
Linux Debian OS
1.8.2 and 1.8.3

**Comment by shohamc1** [comment]
Hey, this is working as expected as those RPCs return the account balances that are in account form. For UTXO balances, you can use the `getbalance` if the addresses are your wallet's, or `scantxoutset` otherwise.

```
$ defi-cli scantxoutset start '["addr(8WrcPiaoGhQgitWiBG6e3fW7dVTuZMvjot)"]'
{
  "success": true,
  "searched_items": 2399061,
  "unspents": [
       ....
 ],
  "total_amount": 20197.34814569 # UTXO balance
}
```
