### ISSUE TITLE
Sent BTC (from CEX Wallet) to DeFiChain BTC (beta) Wallet.  When try to send BTC from DeFiChain to CEX, "insufficient funds to cover fee" error message

### ISSUE THREAD

**Issue by ANONBartholomew** [DeFiCh/ain#719]
#### What happened: 
Sent BTC (from CEX Wallet) to DeFiChain BTC (beta) Wallet.  When try to send BTC from DeFiChain to CEX, "insufficient funds to cover fee" error message.  I have a UTXO balance and a dBTC balance as well.

#### What you expected to happen: 
Send BTC from DeFiChain Wallet to another BTC wallet

#### How to reproduce it (as minimally and precisely as possible):

100%
In BTC (Beta) Wallet in DeFi Chain

#### What are your environment parameters:
 MacBook Pro macOS Monterey

**Comment by Defi-nitiv** [comment]
Hello, is there any update on this? I have the same issue

**Comment by shohamc1** [comment]
This seems to be an issue with the DeFiChain Wallet, please open an issue [here](https://github.com/DeFiCh/wallet/issues/new/choose) if you are still facing this issue.
