### ISSUE TITLE
Reduce the likelihood of empty blocks by reducing backward time and forward time window

### ISSUE THREAD

**Issue by uzyn** [DeFiCh/ain#753]
#### What would you like to be added:

- Reduce backward mean time from last 11 blocks to last 3 blocks.
- Reduce forward time window from 5 minutes to 2.5 minutes (150 seconds).

#### Why is this needed:

We have a lot of empty blocks being mined. Even though our block time remains at 30 seconds on average, practically, we are seeing blocks with transactions every 5 minutes or more.

**Comment by prasannavl** [comment]
@defichain-bot /triage accepted

**Comment by uzyn** [comment]
Addressed at #793
