### ISSUE TITLE
Add estimateloan and estimatecollateral RPCs

### ISSUE THREAD

**Issue by Jouzo** [DeFiCh/ain#796]
#### What would you like to be added:

Add estimateloan RPC to calculate the amount of loan token a vault can take depending on collateral and loan scheme.
`estimateloan loantoken vault`
loantoken typed as string `amount@token`
vault should either be vaultId or (collateral amount, loan scheme) tuple

Add estimatecollateral RPC to estimate the collateral ratio.
`estimatecollateral collateralamount scheme loantoken `
or 
`estimatecollateral vaultId loantoken`

#### Why is this needed:

As of now, a vault owner as no information as to how much loan token he can take.

**Comment by prasannavl** [comment]
Fixed by #924, #927 and #933.
