### ISSUE TITLE
Warning when activating masternode without operator privkey

### ISSUE THREAD

**Issue by IraGraves** [DeFiCh/ain#856]
#### Which feature is your request related to?
Masternodes

#### Is your request related to a problem? Please describe.
I suggest to add a warning to spare others from some trouble I encountered. The warning would avoid seriously messing up the app/wallet in the following scenario: I set up a masternode on a VPS (creating the operator address on the VPS), and managing the owner address from the desktop wallet (following this: https://defichain-wiki.com/wiki/Masternode_installation_extended). This works fine. However, the desktop app shows the masternode as "local" and in a grey/inactive state, offering a button to "activate" it. This button is so tempting that, although I had a bad feeling, I clicked on it... The desktop app then tried to activate the masternode locally, which failed due to lack of the key for the operator address. This rendered the app/GUI unusable as after starting it every time it immediately lost connection to the node (debug showed that it was because of the missing privkey for the operator node). I fixed this by switching off the internet connection and feeding in the missing privkey which I exported from the VPS via the CLI.

#### Describe the solution you'd like:
When using the "activate" button on a masternode for which the wallet does not hold the private key for the operator address, a warning should be displayed before continuing.

#### Describe alternatives you've considered: 
An alternative would be not providing the "activate" button in this scenario at all (for masternodes which cannot be activated). Even better would be that the node is not shown as "locally" in the first place as it is in fact up and running in the VPS (maybe this can be done but I am not sure how; I simply followed the installation tutorial linked above).

**Comment by izzycsy** [comment]
Transferring issue here for reference on improving ux.
