### ISSUE TITLE
`help` rpc not working with `2.2.0`

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/ain#903]
#### What happened:
`help` rpc on the CLI of DeFi Wallet app is not working. 

![image](https://user-images.githubusercontent.com/25013382/141703218-e19e7e9e-2710-4949-bf83-db0b43c71781.png)

**Comment by prasannavl** [comment]
For now `dfi-cli -h` as well specific help: `defi-cli help blockchaininfo` should still continue to the work. 

The emergency update `2.2.0` currently breaks the listing when done through `help` RPC.

**Comment by thedoublejay** [comment]
Fixed with the latest app update. You may check it out here - https://github.com/DeFiCh/app/releases/tag/v2.7.2
