### ISSUE TITLE
Add `size` based pagination support for `spv_listanchors ` RPC

### ISSUE THREAD

**Issue by surangap** [DeFiCh/ain#910]
#### What would you like to be added:
currently `spv_listanchors ` supports `btc height` based data retrieval only. i.e. `minBtcHeight, minBtcHeight`.
But Whale requires size based paginated data retrieval. i.e should be able to retrieve `size` number of anchors from `startBTCHeight`.

#### Why is this needed:
anchors have gaps. `btc height` based retrieval might not exactly work for whale's requirement. 

Ref: https://github.com/DeFiCh/whale/pull/389/files#r750995359

**Comment by Bushstar** [comment]
Resolved by https://github.com/DeFiCh/ain/pull/921
