### ISSUE TITLE
Cannot bid on auction! Auth-Tx Error

### ISSUE THREAD

**Issue by muirglacier** [DeFiCh/ain#917]
Weird thing just happened:

I was bidding on a liquidation auction. I have bid 5001, then i have bid 5502, but when I tried to bid 5700 I got the following error:

placeauctionbid 48e0272298d26abac2434b51e1e63ecb10e56b0f11946444b30d21827f2aa0e2 0 dNisXkisihLGpBRDnwX1sa7VNkNWuE6iC2 5700@DUSD
Add-on auth TX failed: Insufficient funds

There were no insufficient funds, I had 11500 DUSD in this address at that time + 95 DFI UTXOS and 3000 DFI Token.

**Comment by prasannavl** [comment]
This is due to https://github.com/DeFiCh/ain/issues/913, which should be included in a roll up release shortly. 

You might also be interested in following this https://github.com/DeFiCh/ain/pull/919.

**Comment by Cultured-Man** [comment]
HI,

How can we actualy do the bidding?

**Comment by prasannavl** [comment]
This has been fixed by https://github.com/DeFiCh/ain/pull/911 and is already in the previous release (2.2.1). 

@Cultured-Man This should be helpful: https://github.com/DeFiCh/ain/wiki/Loan-and-Decentralized-Tokenization.
