### ISSUE TITLE
"help" - respond with error

### ISSUE THREAD

**Issue by skorilo** [DeFiCh/ain#920]
#### What happened:
~/.defi/defi-cli help 
error code: -32600
error message:
reward address change is disabled for Fort Canning
#### What you expected to happen:
old help 
#### What are your environment parameters:

same answer in macOS Monterey and Linux

#### Anything else we need to know?:

after updating to DeFi Wallet v2.7.1 and Node v2.2.0 
ain and app

**Comment by thedoublejay** [comment]
Hi @skorilo, this has been fixed with the latest app update. You may check it out here - https://github.com/DeFiCh/app/releases/tag/v2.7.2
