### ISSUE TITLE
sendtokenstoaddress error for send of token DFI

### ISSUE THREAD

**Issue by skorilo** [DeFiCh/ain#922]
#### What happened:
does not work for token DFI if you are not the owner of the destination address
#### What you expected to happen:
should work as for dBTC
#### How to reproduce it (as minimally and precisely as possible):

~/.defi/defi-cli sendtokenstoaddress '{}' '{"8...address..R":"0.001@DFI"}' 
error code: -5
error message:
The address (8...address..R) is not your own address

#### What are your environment parameters:

mac

**Comment by dell1503** [comment]
Same issue here.
https://www.reddit.com/r/defiblockchain/comments/rel3s0/deficli_cant_send_dfi_tokens/

**Comment by uzyn** [comment]
DFI must be sent as UTXO across wallets. Reason for this is practical, on external integrators' part, right now for exchanges to integrate with DFI, it's a drop in replacement with their already existent Bitcoin support. Requiring exchanges to support both UTXO and token (which is completely unique to DeFiChain) would make it unfeasible for any exchanges to support DFI entirely.
