### ISSUE TITLE
misstake in /Loan-and-Decentralized-Tokenization#take-a-loan

### ISSUE THREAD

**Issue by spectatormc** [DeFiCh/ain#923]
there is a misstake in the guide for loan taking.
https://github.com/DeFiCh/ain/wiki/Loan-and-Decentralized-Tokenization#take-a-loan

it should be "placeauctionbid" instead of "auctionbid"
also "loanpayback" seams to be wrong (but i did not check this yet)

THX Bastian

**Comment by Bushstar** [comment]
Thanks for the report, those errors have been corrected.
