### ISSUE TITLE
Token creation with Client with wrong settings

### ISSUE THREAD

**Issue by DanielZirkel** [DeFiCh/ain#93]
I created a Token on DefiChain via App with specific settings. The result was not like the specification

The token should have the following setting:
- mintable support = No
- Limit = 1000
- Decimal = 0
![image](https://user-images.githubusercontent.com/68841661/98356603-1ea56780-2024-11eb-827b-d80a7be9e20c.png)

After the creation I got the following result:
- mintable support = Yes
- Limit = 0
- Decimal = 8
![image](https://user-images.githubusercontent.com/68841661/98356723-557b7d80-2024-11eb-9ce1-0ebc746da4c0.png)

Not tried to create another Token.
But Daniel Mustermann reported same behavior for the ArbitrageToken and the mintable-Feature

all from WebSite, Client-Version 2.0.0

**Comment by DanielZirkel** [comment]
It seems not to be a viewing problem in the app.
Also the CLI with 
`defi-cli gettoken 133`
delivers the same result
![image](https://user-images.githubusercontent.com/68841661/98370676-3b00ce80-203b-11eb-9551-6c0940335187.png)

**Comment by ShengguangXiao** [comment]
@DanielZirkel Right now token decimal is fixed to 8. Check the below code, only `symbol`, `name` and `isDAT` is configurable.

```
token.symbol = trim_ws(metaObj["symbol"].getValStr()).substr(0, CToken::MAX_TOKEN_SYMBOL_LENGTH);
    token.name = trim_ws(metaObj["name"].getValStr()).substr(0, CToken::MAX_TOKEN_NAME_LENGTH);
    token.flags = metaObj["isDAT"].getBool() ? token.flags | (uint8_t)CToken::TokenFlags::DAT : token.flags; // setting isDAT
//    token.decimal = metaObj["name"].get_int(); // fixed for now, check range later
//    token.limit = metaObj["limit"].get_int(); // fixed for now, check range later
//    token.flags = metaObj["mintable"].get_bool() ? token.flags | CToken::TokenFlags::Mintable : token.flags; // fixed for now, check later
//    token.flags = metaObj["tradeable"].get_bool() ? token.flags | CToken::TokenFlags::Tradeable : token.flags; // fixed for now, check later
```

**Comment by monstrobishi** [comment]
Thanks for spotting this @ShengguangXiao , then we will remove those fields from the next version of the front end, as changing them does nothing for now

**Comment by DanielZirkel** [comment]
ok, Limit and decimal seems not to be parameter in token creation.
Thanks for the quick response.

What happened with the minting support? should this not be a setting parameter while creating a token?

**Comment by ShengguangXiao** [comment]
@DanielZirkel Do you mean the `mintable` flag, during create it is always true, but later can change it by `updatetoken`

**Comment by monstrobishi** [comment]
Closing as we discovered this is only changeable when updating, fixing in next hardfork
