### ISSUE TITLE
Bug Funds? 

### ISSUE THREAD

**Issue by Ricokingzzz** [DeFiCh/ain#935]
hello everyone. I have a question. I use the desktop wallet. I had sent BTC to myself from my Exodus wallet. Have also arrived and can be proven in the blockchain. The next day my DeFi wallet was empty and there was no BTC address left either. I reloaded my wallet from the seeds unfortunately no funds either. re-syncs nothing. with the Wallet.dat file restarted from the backup, unfortunately no success. Nothing changed on test network either. i have been trying everything for 2 weeks. is this a bug and why aren't my funds loaded? 
Greetings Rico

**Comment by Ricokingzzz** [comment]
triage accepted

**Comment by Ricokingzzz** [comment]
Need triage

**Comment by rambaldi014** [comment]
Have the same problem. Anyone who can help?

**Comment by shohamc1** [comment]
This may be related to the Bitcoin SPV sync, see [here](https://github.com/DeFiCh/app/issues/1043#issuecomment-921655598). Make sure that `current` in `spv_syncstatus` is close to or same as the latest Bitcoin block.

Closing this issue, feel free to reopen if this does not solve your issue.
