### ISSUE TITLE
Problem changing Token-property Minting with CLI

### ISSUE THREAD

**Issue by DanielZirkel** [DeFiCh/ain#94]
I want to change the token property "Minting Support" of an existing Token via CLI.
My command syntax failed (it seems to be not correct and I already had a look on the API-documentation)

Minting-Support of Token should be "no"/false

I used the following command 
_defi-cli updatetoken "DGT" ( {"symbol":"DGT", "name":"DeFi Genesis Token", "isDAT":false, "mintable":false, "tradeable":bool, "finalize":bool})_
and got the error shown on the screenshot
![image](https://user-images.githubusercontent.com/68841661/98357135-097d0880-2025-11eb-8378-c88abdaf0f07.png)

The error is reproduceable with the used syntax => seems to be wrong

Used Version: defichain-1.3.3-x86_64-w64-mingw32

**Comment by bvbfan** [comment]
Try this one
`defi-cli updatetoken "DGT" { "mintable":false }`

**Comment by monstrobishi** [comment]
@bvbfan it might need wrapping the JSON object in single quotes: `defi-cli updatetoken "DGT" '{ "mintable":false }'`

**Comment by DanielZirkel** [comment]
I tried several expressions, but always the same result:
![image](https://user-images.githubusercontent.com/68841661/98366586-8368be00-2034-11eb-9c9a-d995b7413459.png)

**Comment by monstrobishi** [comment]
Try this

defi-cli updatetoken ' "DGT#133" ' '{ "mintable":false }'

Note because your token is a custom token not a pegged asset, you need to add your token id `133`, you can find this by running `listtokens`:

![Uploading Screenshot 2020-11-06 at 8.39.21 PM.png…]()

**Comment by DanielZirkel** [comment]
Thanks monstrobishi, I am one step further.
With just using the ID the error is longer regarding the Token, now the problem is interpreting the second argument
![image](https://user-images.githubusercontent.com/68841661/98370598-19074c00-203b-11eb-8dbd-862310c4a083.png)

The starting seems to be correct: `defi-cli updatetoken 133`

**Comment by ShengguangXiao** [comment]
Try this

```
defi-cli updatetoken ' "DGT#133"' "{\"mintable\":false}"
```

There is some problem with the first parameter conversion, i will fix it.

**Comment by DanielZirkel** [comment]
Sorry, but I still can not execute the updatetoken command. I tried several things again, always an error and I am not familiar with the json-argument at the end
![image](https://user-images.githubusercontent.com/68841661/98372211-b4012580-203d-11eb-92c5-0c2b768716cb.png)

**Comment by monstrobishi** [comment]
I think you are very close with the first attempt, try again but move the single quote next to the double quote like so:

defi-cli updatetoken '"DGT#133"' "{\"mintable\":false}"

**Comment by DanielZirkel** [comment]
This was the second attempt in the screenshot above. 
The Token-description is not accepted

**Comment by bvbfan** [comment]
`defi-cli updatetoken '"DGT#133"' "[{\"mintable\":false}]"`

**Comment by DanielZirkel** [comment]
Sorry, Token is not correct
![image](https://user-images.githubusercontent.com/68841661/98378441-4efdfd80-2046-11eb-9800-3f6c7b47c01f.png)

**Comment by monstrobishi** [comment]
That's quite surprising,

`defi-cli updatetoken ' "DGT#133" ' '{"mintable":false}'` should really work. It must be a Windows related issue, as most of us devs are on Linux/Mac. Please give us some time to investigate this issue on Windows
