### ISSUE TITLE
Wrong command for Loan Pay Back in Wiki

### ISSUE THREAD

**Issue by tschmidiger** [DeFiCh/ain#945]
According to the Wiki https://github.com/DeFiCh/ain/wiki/Loan-and-Decentralized-Tokenization the pay back of a loan is accomplished by the following command:

loanpayback

Running loanpayback on the CLI (in the windows desktop app) results in a "Method not found" error.

However, running **paybackloan** worked - thus this seems to be a mistake in the Wiki.

**Comment by Jouzo** [comment]
Fixed, thanks !
