### ISSUE TITLE
Usage of Liquidity-Pool-Tokens as Collateral

### ISSUE THREAD

**Issue by defiprop** [DeFiCh/ain#951]
#### What would you like to be added:

Allow the usage of (selected?) Liquidity-Pool-Tokens as collateral in vaults.

#### Why is this needed:

The Liquidity-Pool-Tokens represent a value that is at least as valuable as the sum of the pooled tokens. Maybe give it a try with DFI-DUSD (and thereby make it more attractive to mint DUSD, in order to accelerate its devaluation of DUSD closer to its nominal value, which many people consider an issue). But I think this could be extended to any pool pair in the long term.

**Comment by defiprop** [comment]
@MX24C Yes, you might be right on that. But when you still have the constraint to have 50% DFI (either in form of part of a liquidity-pool-token OR pure DFI in combination with liquidity-pool-tokens that involve dTokens)? Thereby the collateral should be high enough in my opinion.

**Comment by Jouzo** [comment]
Should be discussed in a DFIP.
