### ISSUE TITLE
Make Liquidity Mining in Cold Storage more user-friendly

### ISSUE THREAD

**Issue by defiprop** [DeFiCh/ain#952]
#### What would you like to be added:

Liquidity Mining in Cold Storage is possible (I successfully do it for several months now) but a little bit complicated for the average user. It would be nice to have the possibility to create transactions online, transfer them to the offline system, sign them and transfer them back (I use a QR-Code serializer for that). This is currently only possible with a deep understanding of the protocol and by using the command line. Maybe have a look at [coinb.in](https://coinb.in/) for inspiration, it reflects the idea.

#### Why is this needed:

To attract high rollers it is important to make them know that their investments are safe. As the defi.conf can easily be read out and contains the information to access the node, the wallet could be cleared by an attacker once it is unlocked, e.g. for re-balancing, making transfers or whatever. With a bash script of far less than 100 lines, this can be done easily (and I am sure on Windows as well). Eliminate unnecessary risk.

**Comment by shohamc1** [comment]
This issue does not seem to be directly related to the node. If you think this is a mistake, please reopen the issue.

We reccomend all users to set a `timeout` when unlocking a wallet using `walletpassphrase` to prevent unauthorized access to wallet funds.
