### ISSUE TITLE
Make filters for the tables on the DeFiscan website

### ISSUE THREAD

**Issue by rocketeer76** [DeFiCh/ain#953]
#### What would you like to be added:

On https://defiscan.live/
Make filters for tables for each section of the website so it's easy to find the LM pair with highest APR or whatever.

#### Why is this needed:

Easier to find information.

![image](https://user-images.githubusercontent.com/7510893/144900904-740c2f10-ea9d-44b4-ad6c-2a530a8aecee.png)

**Comment by hidiego** [comment]
Please @rocketeer76 open this issue in the correct repository -> https://github.com/DeFiCh/scan
