### ISSUE TITLE
Can't sign TX: Witness program hash mismatch

### ISSUE THREAD

**Issue by mondsen** [DeFiCh/ain#964]
#### Actual behavior: Placing a bid for a vault auction via the App Console does not work. The error always is the same like this:
```
Can't sign TX: [{"txid":"6b98d2310a597af2888b5e52ef9d2685e174694668265b05ce677dc820297a0d","vout":0,"witness":[],"scriptSig":"160014dad86db6ee98d43e963f8dd57f69de5db6051550","sequence":4294967295,"error":"Witness program hash mismatch"}]
``` 

#### How to reproduce it (as minimally and precisely as possible):
Bidding for vault https://defiscan.live/vaults/6e212a7e52819070d73bf8c013067ec165502f74f691c0d8df5329bf1f6f0375/auctions/2 with index 2 expect Min. Starting Bid 3.67504143dBABA

Balance is sufficient
```
getbalance
10

gettokenbalances
  "3.74964208@19"
```

Call ```placeauctionbid "6e212a7e52819070d73bf8c013067ec165502f74f691c0d8df5329bf1f6f0375" 2 "dY67eowEwDye3N8WyeRjFSiahm9fCuZQ2c" "3.67504143@BABA"```

After this the above error message appears

#### What are your environment parameters?

- DeFiCh/app Version: 2.7.3
- Operating System (OS): Windows 10 x64
– RAM (GB): 16
– CPU (Intel Core i5/i7/etc.): Ryzen x3700
- Current free storage capacity: 500 GB

#### Anything else we need to know?

I am using a fresh Desktop wallet to bid for the auction. There is no vault. Can that be the issue? I only have a vault in the light wallet on my mobile. Do I need to have a vault for bidding for the tokens?

**Comment by muirglacier** [comment]
Mate, just unlock your wallet and it will work flawlessly
