### ISSUE TITLE
Payback of loans not possible. „Error 0 400 Bad Request“

### ISSUE THREAD

**Issue by brabo86** [DeFiCh/ain#967]
#### What happened:
Try to pay back a part of my loans. Got "Error 0 400 Bad Request". Payback loan not possible. 

#### What you expected to happen:
Loan got paid back.

#### How to reproduce it (as minimally and precisely as possible):
Tried to pay back small or full amount of minted dtoken via lightwallet app.

Everytime I try this, this error happens.

#### What are your environment parameters:
IOS 15.1 ; lightwallet 0.19.0

#### Anything else we need to know?:

Vault state is "good"
Defiscan says "healthy"
Vault was created and token were minted before rewards gone live.

**Comment by tommuhm** [comment]
Since the `FortCanningMuseum` hardfork I'm also not able to payback a lot of my loans. The error message is: `Cannot payback this amount of loan for GME, either payback full amount or less than this amount!` 
A full repayment still seems to work, but partial payments are only working up to a specific amount, afterwards I'm always receiving the error message. A payment above the full amount also does not seem to work.

**Comment by kpdt** [comment]
I confirm the same behavior in the IOS lightwallet 0.19.0. 
Additionally, after I import my seed  into the saiive wallet, where the error message a more verbose, I got the following:

`{"error":"{\"error\":{\"code\":400,\"type\":\"BadRequest\",\"at\":123456,\"message\":\"PaybackLoanTx: Cannot payback this amount of loan for DUSD, either payback full amount or less than this amount! (code 16)\",\"url\":\"/v0/mainnet/rawtx/send\"}}"}` ... etc

**Comment by kpdt** [comment]
After update on LW 1.19.2 same issue

**Comment by tommuhm** [comment]
This issue is still persistent with v2.3.1!, at least with the provided snapshot for block `1435343`! Do we need a older snapshot? 

I think this issue should be considered critical since we are not able to payback partial loans and some loans are just to big for a full repayment at once.

**Comment by kpdt** [comment]
@tommuhm  same here with `v2.3.1`

**Comment by sandrich** [comment]
I would probably close this and revert to https://github.com/DeFiCh/wallet/issues/1623 . There is also a form that can be filled out for further debugging.

**Comment by prasannavl** [comment]
Thanks for the report. Closing this to track on https://github.com/DeFiCh/wallet/issues/1623 and https://github.com/DeFiCh/ain/issues/983
