### ISSUE TITLE
ThreadStaker: ... waiting init... + high CPU consumption

### ISSUE THREAD

**Issue by McRange** [DeFiCh/ain#973]
#### What happened:

Since v2.3.0 / v2.3.1 we get ervery second this at our MasterNode:
**ThreadStaker: (1c2...) waiting init...**
In addition, the CPU load is relatively high (1-2 Threads additional permanent load).

At start of the service there is always this:
**Minting thread will start with empty coinbase address cause masternode does not exist yet. Correct address will be resolved later.**
No matter how long you wait or restart later, nothing changes in the message.
Our masternode exists of course (10 year freeze), 

#### What you expected to happen:
Behavior like before <2.3.0: non of these obove

#### How to reproduce it (as minimally and precisely as possible):
- version 2,3,0 or 2.3.1
- Linux
- default settings
- reindex (recommanded in notes for 2.3.1)

#### What are your environment parameters:
- Ubuntu 20.04
- headless

#### Anything else we need to know?:
The last reward was only 5 days ago, but my customers are already getting impatient with the error.

**Comment by Stonygan** [comment]
Please check your blockheight, seems you are not full synchronized. Sync from scratch need 15-24 hours.
~/.defi/defi-cli getblockcount
Check Blockheigt and compare with defiscan.live.

Maybe the better way for support for this problem is Telegram: https://t.me/DeFiMasternodes
