### ISSUE TITLE
Bring dTokens Prices closer to Real-World Prices in a fair Manner

### ISSUE THREAD

**Issue by defiprop** [DeFiCh/ain#978]
#### What would you like to be added:

A proportional inflation of dTokens (DUSD, dStocks and dETFs) to bring prices closer to oracle prices to attract more investors to the DeFiChain.

#### Why is this needed:

As argumented in [issue#947](https://github.com/DeFiCh/ain/issues/947), the difference in price of the dTokens w.r.t. their real-world counter parts prevents investors (who do not understand the difference between price and value) to come to DeFiChain. Proposal #947 has the plan to devaluate the dTokens by giving un-backed, "out-of-thin-air" printed dTokens exclusively to vault holders, **effectively _expropriating_ all other dToken holders** by the amount of the premium they paid to provide their service to the DeFiChain (in case they do liquidity mining).

The idea of bringing dToken prices closer to oracle prices is a good one. However, **this should be done in a _fair_ manner**. My proposal is to give free dTokens to all people involved at a fixed date (e.g. block 1.500.000). The dTokens should be added to **ALL** accounts (vaults, liquidity pools and simply resting dTokens) according to their premium at this time (and sure, for the non-DUSD tokens it has to be taken into consideration that the premium consists of the USD-DUSD premium **_plus_** the oracle-dToken premium).

**Edit:** As [LumpiesRevenge](https://github.com/LumpiesRevenge) pointed out (thanks a lot), premiums will rise again after prices are adjusted by the proposed airdrops, as their value is still higher than their real-world counterparts due to the LM rewards. So the airdrop should be repeated (e.g. every 50.000 blocks) as long as the dToken prices deviate from the oracle prices by an unacceptable amount (for me personally, the nominal prices do not matter as I am interested in value, not in prices, so "unacceptable" should be defined by someone else).

**Edit:** As [Wolfgang](https://github.com/wmbst) pointed out (many thx), it might be that premiums could turn into a discounts (i.e. the dToken prices could drop below the oracle prices). In this case I suggest an "air-pick" (negative air-drop), i.e. people who bought/hold dTokens at a discount will loose that discount in the "adjustment-event".

**Comment by LumpiesRevenge** [comment]
Hi.

I have some questions:
Who would collateralize the free dTokens?

Markets are dynamic. Let´s assume your plan is executed and everybody got "free dTokens".
Then the demand for dTokens rises further. The DEX prices deviate from the Oracle prices again (DEX price > Oracle price). What now? Donating free dTokens again? ;-)

**Comment by defiprop** [comment]
@LumpiesRevenge Yes, this is exactly what will happen. The "problem" is that the dTokens (even if they are inflated) have a higher value then their real-world counterparts (as you get DFI in addition to the fees). Thus, once the prices are adjusted, more investors will come in, and the premiums will rise again. So, you are right, this airdrop has to be repeated on a frequent basis (until the additional incentive for liquidity mining by the airdropped DFI fades away completely). However this would attract a lot of capital to the DeFiChain, making the (otherwise optimistic) #roadTo50 somehow realistic.

**Comment by wmbst** [comment]
In my opinion, the high dUSD prices are a temporary thing as long as rewards are that high. Once the rewards drop, people are not willing to pay the high premium anymore and prices will drop automatically.
If you artificially brought down the prices before this happens by free aidrops, the prices will fall below the oracle prices once people want to leave liquidity mining.
What will you do, when the dToken prices fall below the Oracle price? How will you remove the additional printed tokens from the system/users?
Influencing the prices by this extreme measurements is a very risky thing.

**Comment by defiprop** [comment]
@wmbst I totally agree with you. The prices should reflect the value (as they do). I actually do not want to manipulate them because - as you correctly pointed out - they will drop automatically over time. Nothing do be done in my opinion.

However, uzyn wants to manipulate them (by printing un-backed tokens) in a way that only vault holders will be compensated for the inflation, whereas all other dToken holders are screwed (as the premium the paid will be inflated away).

So I do not think manipulating the quantity of dTokens is a good idea. But when it is done it should be done in a fair manner (vault holders **_and_** token holders should get airdrops).

Concerning your question what will happen when prices drop below oracle prices I would suggest an "air-pick" (negative airdrop).

Anyway, I am on your side: Best would be to do nothing. On the other hand I understand that many people with little knowledge about economics (not understanding the difference between price and value) want the DEX prices the same as real world prices, just have a look on the discussion of uzyn's proposal. So (as I don't care about prices, but value) let's give them their real world prices. If this a way attracts noobs, great! From an economic point of view it absolutely doesn't make any sense, but if it makes people happy, the do it (but in a fair manner).

**Comment by webbgroup** [comment]
Agreed. Best tactic is to do nothing. Prices will rise or fall depending on the rewards pay off/ do not pay off. Right now the DEX prices are killing a true market. But it is what it is. It will self regulate with time.

**Comment by legendarytuna** [comment]
I dont think a difference in price between a dToken and their "real world counterpart" is a huge and longterm problem. People need to understand(!) that these are not the same. With the dToken you have access to a (right now) very high inflow of capital (=rewards). This alone differentiates these two asset and SHOULD be represented in the price, which it is right now. Other factors like Tax advantages (or disadvantages), lower transaction fess and so on do also play a role, but compared to the rewads a smaller one.

That beeing said, I do think DUSD beeing so far off of its meant-to-be price of 1$ should be adressed. It is the entrance door into the whole system and within this system it acts like a Utility token. 
The minting of DUSD does bind to much capital in my opinion. The premium of DUSD is a reflection of the opportunity costs. **Think about it like this**: IF some mechanisms/proposal/whatever puts the DUSD price to 1$. Why would you wanna mint it (and bind at least 1.5 times the capital) if you could easily buy it for 1$? 
It is illogical. Sure in a fully developed system with reasonable/sustainable/competitve rewards and other factors gain importance. But until time (block rewards will go down) or money (enough money overall is in the system to bring the rewards down) will change the rules, the root of the problem imho is the capital binding.

I therefore would like to see a solution with 
a) loan scheme around ~100%
b) ability to be backed by USDC USDT (=no DFI needed)
c) a flexible interest rate for DUSD mining (the interest rate could even be negative)
(bonus feature: by backing it with DFI it could get a discount on the interest. This is to compensate point b)

Your Airdrop solution doesnt fix the root of the problem at all. It might fix the situation at one specific but the mechanisms that lead to the current situtaion will still be in place.
Adding incentives and thereby trying to alter the behavior of the market participants could be a fix in the long run.

**Comment by defiprop** [comment]
@webbgroup note that this is only true for smart people like you.

> Agreed. Best tactic is to do nothing. Prices will rise or fall depending on the rewards pay off/ do not pay off. Right now the DEX prices are killing a true market. But it is what it is. It will self regulate with time.

Note that this is only true for smart people like you. The majority want DUSD to be 1 USD, dTSLA to be 1 TSLA and so on.

**Comment by legendarytuna** [comment]
> > Agreed. Best tactic is to do nothing. Prices will rise or fall depending on the rewards pay off/ do not pay off. Right now the DEX prices are killing a true market. But it is what it is. It will self regulate with time.
> 
> @webbgroup Note that this is only true for smart people like you. The majority want DUSD to be 1 USD, dTSLA to be 1 TSLA and so on.

jep. The lack of understanding dASSETS and the lack of knowledge how Supply & Demand work (and what drives them up or down) is by far the bigger "problem". 

But pointing the finger at a number like "See that, that should be 1$" is the easiest consensus.

**Comment by defiprop** [comment]
@legendarytuna You also got the point. However, have a look at Julians video [FREE DUSD TO ARBITRAGE PRICE TO 1 USD!!](https://www.youtube.com/watch?v=SfU2ugL7lfk&t=4s). Consensus: "Uhhh, I am so smart, I am an arbitrage trader right now! Those stupid people who pay that premium, hehehe, I will show you.."

**Comment by webbgroup** [comment]
This is going to royally screw folks who are DFI/dUSD liquity mining. DFI
Customers.

 Why would we want dUSD to drop by 1/4th dramatically? Screw that.

**Comment by goscha80** [comment]
> Concerning your question what will happen when prices drop below oracle prices I would suggest an "air-pick" (negative airdrop).

They will never do. There is an arbitrage-apportunity for that. Just take a loan to the oracle price and by in the dex at lower price. Payback the loan. You are done.

**Comment by defiprop** [comment]
@goscha80 The funny thing is: Many people think that by this arbitrage-mechanism the prices can be lowered significantly (to 1 USD). But it's not arbitrage to USD but rather to the **_value_** (not price!) of DUSD (which is currently >130% of USD due to the DFI-rewards obtained by LM).

**Comment by goscha80** [comment]
>@goscha80 The funny thing is: Many people think that by this arbitrage-mechanism the prices can be lowered significantly (to 1 USD). But it's not arbitrage to USD but rather to the value of DUSD (which is currently >130% of USD due to the DFI-rewards obtained by LM).

Correct. The money goes where the profit is. 
They cannot correct it but they make many gains.

As i described in the  issue#947 this is the only one way out of the dStock-system. If we would close it the prices would rise much higher. So we have two limitations in the current design: Oracle price is the bottom and min. col. ratio (150%) is the upper limit (the too much worth accumulates in the auctions).

>which is currently >130%

approx. 150% to get in dStock


Airdropping dStock/dUSD (manipulating the worth of them) is too dangerous in my opinion. Because you give them directly in the hands of people. Nobody knows how this will effect the market. Why I should sell anything. i can just put it to LM and get more and more airdrops and dfi rewards. The effects are incalculable
Worst case would be:  Airdropped dStocks/dUSD would really be putted to LM. The prices stay high, the rewards go down because of filled pools and only then we would see a effect on the prices.

**Comment by Rno123** [comment]
I have a question: what's the arbitrage mechanism if the dTokens and dUSD still trades at a premium after liquidity mining rewards?

**Comment by uzyn** [comment]
Closing this for https://github.com/DeFiCh/dfips/issues/99
