### ISSUE TITLE
Deviation of Oracles and Coinmarketcap > 1 %?

### ISSUE THREAD

**Issue by defiprop** [DeFiCh/ain#979]
#### What happened:

On Dec 12, 16:42 (European time) the oracle price deviated more than 1 % form the price on coinmarketcap.

![image](https://user-images.githubusercontent.com/95631913/145719098-3c7e436f-51c9-4f00-af50-4c3b6a7bef8f.png)

EDIT: here another screenshot, taken a few minutes later. The deviation is still there (although prices changed, just to show that this is not a connection frozen problem or s. th. like that):

![image](https://user-images.githubusercontent.com/95631913/145719314-272e38db-d1c1-4282-a299-854561cb9cf3.png)

#### What you expected to happen:

Check where this difference comes from. Do we have to pick more reliable oracle providers?

#### How to reproduce it (as minimally and precisely as possible):

No idea how to reproduce it, but I will keep an eye on that. Are there any data for comparison of oracle prices to coinmarketcap prices over time?

#### What are your environment parameters:

Firefox

**Comment by wmbst** [comment]
There are two questions for me.
1. Is the coinmarketcap price a fair price? They include and exclude price feeds as they want, so why should it be seen as an official price?
2. Is there a possibility to see where exactly the oracles get the prices from?

**Comment by shohamc1** [comment]
Does not seem related to this repo.
