### ISSUE TITLE
Loan Partial Payback Tracking Bug 

### ISSUE THREAD

**Issue by prasannavl** [DeFiCh/ain#983]
A tracker issue for all of the loan payback related bugs that were introduced during the emergency hard fork

## Context

- During the emergency hard fork, the code that prevents zero interest resulted in a few bugs, that made partial paybacks unreliable in many cases. 

- **Workaround:** Full payback continues to work as expected. However, depending on the block in which the tx actually gets mined, a slightly larger amount needs to be given to account for the interest in the extra blocks. (Note the extra is never deducted from the account). 

   - Example: if the full amount to payback is 1 dToken at 5% per year interest (assuming 0.00000005 fi as interest per block), paying ~= 1.00000100, would help ensure that the payment will be successful, as long as it's included in any of the next 15-20 blocks.  

## Key issue

- https://github.com/defich/ain/blob/master/src/masternodes/loan.cpp#L212 - While the interest is ceiled to 1 per block, `MultiplyAmounts` will result in 0 due to a mix of int256 math and FP math. However, on payback the interest is required to be over 1 fi due to this: https://github.com/defich/ain/blob/master/src/masternodes/mn_checks.cpp/#L2692-L2693. 

### Straight forward:

1. Check for `MultiplyAmounts` results and handle 0 case specifically to be ceiled to 1. 
    - **Considerations** 
        1. Still doesn't account for precision loss for non zero. However this shouldn't be an issue since this is the source of truth and the caller of the method `StoreInterest` ceils the value. 
        1. This makes it deviates from any standard calc, and makes it difficult to recreate this calc externally. 

1. Remove the use of COIN precision int256 calc, esp, `MultiplyAmounts` and simply use FP/double calculations for all of the values inside of the `InterestPerBlock`. This makes it easy, consistent and reproducible, while retaining the full precision (as long as it's within the precision parameters of FP)
    - **Considerations**
        1. This increases the surface area of float, and we ideally want to reduce it's surface area and keep it limited and in isolation only to specific areas. While it can be reasoned with, in a straight forward manner in this context, it's easy for float quirks to propagate making it difficult to maintain and test. 
        
While each of the above are simple, all of these solutions still do suffer from the limitation that the max precision is 8 digits of decimals, and as such minting of tokens will accrue a min. interest of 1 fi, regardless of the value.   

### Optimal solution

1. https://github.com/DeFiCh/ain/issues/984: Introduce higher than COIN precision for interest rate only utilizing the larger bytespace of the backing 256 int (instead of just using the low 64 bits, as today), allowing even 1 fi loans to have reasonable interest rates. 

While this solves all of the problems above, this also requires more extensive testing, since we're introducing larger precision, and calculations based on that.

**Comment by prasannavl** [comment]
Short status update: #984 and https://github.com/DeFiCh/ain/pull/991 resolves this. However, cannot be activated until next hard fork - which is now expected towards the end of Jan.

**Comment by prasannavl** [comment]
With a crypto prices going on a volatility ride - advice users to not rely on partial payback when it's a matter of liquidation - please be prepared to close positions in full and plan it accordingly. If partial payback works for you, good for you - but please do not rely on it until the next hard fork and these fixes are in.

**Comment by Kolibri1990** [comment]
Thanks @prasannavl for the update. We moderators will share this in the channels.

**Comment by felixdorner** [comment]
Sorry, I need some clarification on the consequences of this: Swapping DFI for BTC is not possible until the end of January?

**Comment by Kolibri1990** [comment]
> Sorry, I need some clarification on the consequences of this: Swapping DFI for BTC is not possible until the end of January?
hey @felixdorner

This issue has nothing to do with swaping DFI for dBTC. 
There was never a stop on the DEX to swap dBTC to DFI or DFI to dBTC.

**Comment by prasannavl** [comment]
Resolved by https://github.com/DeFiCh/ain/pull/991
