### ISSUE TITLE
New "emergency" update to triple master-node rewards

### ISSUE THREAD

**Issue by defiprop** [DeFiCh/ain#992]
#### What would you like to be added:

Another "emergency" update (like the one for the DUSD issue) to triple the rewards for master-node holders.

#### Why is this needed:

Well, why not? As the master-node holders will vote on that it's very likely that the proposal is approved. And the trust into CeFiChain is already destroyed by applying "emergency" updates on problems that are no emergencies (like the DUSD premium).

**Comment by wmbst** [comment]
How old are you? 16?
If you want to make a corresponding dFIP, than do it right. The masternode owners have shown to vote responsible.
But this whining is ridiculous.

**Comment by muirglacier** [comment]
Lol

**Comment by defiprop** [comment]
@wmbst But you agree that this is an emergency, right? Or at least as much of an "emergency" as the DUSD issue...

**Comment by John-Gee** [comment]
That's a pretty bad way to make your point.

**Comment by defiprop** [comment]
@John-Gee So what do you suggest? I took my consequences, leaving the dToken market completely. I thought that DeFiChain might solve some of my problems (go into the non-crypto market for surviving the crypto winter which I expect to start during Q1 of 2022, without KYC. I am tax free anyway, just don't wanna do any paper work in case I stay in any other country). I made my percentages during the bull-run AND by shorting DFI during the ultimate crash, so thaz not my point.

Now they come up with that "emergency" plan to make Julians (frankly spoken ridicolous) ["risk-free" and "no-brainer" "arbitrage"-Deal](https://www.youtube.com/watch?v=SfU2ugL7lfk&t=4s) come true. Thaz the way to go for DeFiChain? Categorizing the change "emergency" to make the dream of an over-worked-out Julian come true (to keep his face) as fast as possible? No way to await the normal procedure (which might take some more weeks)?

I respect the rules, but why does it need an "emergency" plan to artificially devaluate DUSD to overcome some misconceptions of the dToken space design (with which I b.t.w. do not have any problems with, as I know that there is a difference between price and value)? 

I do not have any master-node (could have some dozens) but I really dislike that Uzyn came up with some socialist idea to change the game significantly, Julian promoted it, and now they implement some "emergency"-workaround by Bathazar (who made a ridiculous "[7000% APR without risk](https://www.youtube.com/watch?v=lA1tO03ZgoU)"-video, and I hope that you do not want to tell me that it is not ridiculous) and DZ (who really seems to be a low level marketing gag with bummed around tooth, no idea about economics). WTF?

So, what do you suggest to prevent those things to happen in the future (and be sure the next thing will be that you can do with DUSD on other dTokens what is planned for DFI right now to be done with DUSD). I do not have any problem with that. Just with the "emergency" (which in my opinion should be kept for severe problems, not for a dream of Julian and his followers who do not think on their own).

Thaz my point. So what do you suggest? Are you one of those pseudo "arbitrage"-specialists fooled by blindely following Julian or do you see a (severe) problem in implementing changes of rules in an "emergency"-manner where there is no emergency?

**Comment by prasannavl** [comment]
I'm sorry for the way way you feel. However, personal attacks would not be tolerated and I'm deleted the above comment. If you would like to express it differently, you are welcome to. 

Additionally, your topic appears to be more relevant to the DFIPs or else where. This is not related to the node or the protocol. And as such I'm closing this thread.
