### ISSUE TITLE
Asynchronous Liquidity Mining for dTokens

### ISSUE THREAD

**Issue by Shentist** [DeFiCh/ain#993]
**#### What would you like to be added:**

Make it possible to add asynchronous Liquidity to dToken pools. 

**#### Why is this needed:**

The purpose of the dTokens is to track the real world asset as close as possible. Because the dTokens are so valuable this is not happening. But we need to understand the price for example dTesla is just fiction. There are no mechanisms to force the price to mirror the oracle price at the moment. 

For this purpose, I would like to discuss the following idea. 

- Normally we can only add both sides to the liquidity pool.
- To "arbitrage" the premium, we should allow to add only one side to the liquidity pool.
- The kicker should be that the poolshare will be calculated with the oracle price and not the pool price.

So, if I add liquidity on a not correct-priced pool on the needed side, I will get this premium as extrapoolshare. So the useres are incentiviced to "arbitrage" the missed price out of the pool. 

So I could mint dTesla and instead of selling I can now add just the dTesla Token to the Liquidity Pool. Because the pool price and the oracle price are not the same I will get the premium to my poolshares.
If I would do the same with only dUSD in the Tesla pool I would get fewer poolshares, becuase  the misprice is not on the dUSD side of the pool.

What do you think? Could this balance the pool on the long run out?

The advantage is, that we do not need to introduce untethered dTokens to balance the pool out and now we can arbitrage the premium out of the pool without the need to have a second pool or something else. This is only possible with healthy oracle prices!

**Comment by Jouzo** [comment]
Interesting idea. This should be discussed as a DFIP.
